### ISSUE TITLE
isLoggedIn function does not work

### ISSUE THREAD

**Issue by minizatic** [matrix-org/matrix-js-sdk#1]
I've been attempting to begin building an experimental web/mobile application on top of the matrix protocol using this  library and I've found that the `isLoggedIn` function does not work correctly, it simply returns false. I believe this is because the `login` function never saves the credentials it receives from the server.
 
Additionally, I believe that the `isLoggedIn` function checks for the wrong variables, eg: `userId` as opposed to `user_id`.

 I've temporarily solved this in my own code by manually saving the data and renaming the variables in the `login` callback.

**Comment by Kegsay** [comment]
The SDK in 0.0.2 does not currently modify any of the state given to it. In 0.0.3 it will handle API credentials.
