### ISSUE TITLE
How i set up it javascript (Not Node.js)

### ISSUE THREAD

**Issue by nhupv** [matrix-org/matrix-js-sdk#1003]
i'm not using node.js, so how can i set up matrix js sdk with a javascript project.

**Comment by jryans** [comment]
There are examples [in the repo](https://github.com/matrix-org/matrix-js-sdk/tree/develop/examples), including a browser based one. I would suggest joining [#matrix-dev:matrix.org](https://matrix.to/#/!jxlRxnrZCsjpjDubDX:matrix.org?via=matrix.org&via=utwente.io&via=sorunome.de) to ask questions interactively about this.

**Comment by nhupv** [comment]
i actually ran the example which in the repo, but i get an error : matrixcs is not defined. can you help me fix it? pleases.
