### ISSUE TITLE
[Doc] EventTimelineSet~getRelationsForEvent may return undefined

### ISSUE THREAD

**Issue by V02460** [matrix-org/matrix-js-sdk#1004]
This method might return undefined, but JSDoc says otherwise.

https://github.com/matrix-org/matrix-js-sdk/blob/9a8af05bfb6d01ddd835ee6f5104b3b7368d1273/src/models/event-timeline-set.js#L692-L695

**Comment by t3chguy** [comment]
Fixed by #1054
