### ISSUE TITLE
Custom logger

### ISSUE THREAD

**Issue by grigori-gru** [matrix-org/matrix-js-sdk#1059]
Hi!
Is there any way how I can use my custom logger for this sdk to manage logs?

**Comment by clokep** [comment]
This would help my integration into Thunderbird. In particular it would be nice if each instance of `MatrixClient` could have their own logger (we have the ability to do account specific logging, which is not currently possible with the matrix-js-sdk).

It could likely be done similar to how the store, scheduler, request, and cryptoStore backends can be overridden using `MatrixClient.createClient`.

**Comment by KB1RD** [comment]
@grigori-gru @clokep The JS SDK uses [Loglevel](https://www.npmjs.com/package/loglevel), which can be configured easily. It also supports plugins to expand functionality, so I would argue that it's a good choice already. I do agree that it would be helpful to separate logs for different clients. This could be done by passing a different logger object to the Matrix client constructor or something similar. Maybe it could be done like this:
```javascript
  var sdk = require("matrix-js-sdk");
  var loglevel = require("loglevel");
  var client = sdk.createClient({
    baseUrl: "https://matrix.org",
    logger: loglevel.getLogger("my-matrix-logger")
  });
  client.publicRooms(function(err, data) {
    console.log("Public Rooms: %s", JSON.stringify(data));
  });
```

**Comment by gergof** [comment]
Possible workaround that will work with [winston](https://www.npmjs.com/package/winston) for example.
```js
import Matrix from 'matrix-js-sdk';
import { logger as mxLogger } from 'matrix-js-sdk/lib/logger';

// rewrite matrix logger
mxLogger.info = (...msg) =>
	logger.log({ level: 'info', message: msg.join(' ') });
mxLogger.log = (...msg) =>
	logger.log({ level: 'info', message: msg.join(' ') });
mxLogger.warn = (...msg) =>
	logger.log({ level: 'warn', message: msg.join(' ') });
mxLogger.error = (...msg) =>
	logger.log({ level: 'error', message: msg.join(' ') });
mxLogger.trace = (...msg) =>
	logger.log({ level: 'debug', message: msg.join(' ') });

const client = Matrix.createClient();
// ....
```

**Comment by grigori-gru** [comment]
@gergof 
Thanks! It works!

**Comment by chris-aeviator** [comment]
> @grigori-gru @clokep The JS SDK uses [Loglevel](https://www.npmjs.com/package/loglevel), which can be configured easily. It also supports plugins to expand functionality, so I would argue that it's a good choice already. I do agree that it would be helpful to separate logs for different clients. This could be done by passing a different logger object to the Matrix client constructor or something similar. Maybe it could be done like this:
> 
> ```js
>   var sdk = require("matrix-js-sdk");
>   var loglevel = require("loglevel");
>   var client = sdk.createClient({
>     baseUrl: "https://matrix.org",
>     logger: loglevel.getLogger("my-matrix-logger")
>   });
>   client.publicRooms(function(err, data) {
>     console.log("Public Rooms: %s", JSON.stringify(data));
>   });
> ```

I don't see options for a logger in https://github.com/matrix-org/matrix-js-sdk/blob/e6af29df9468db172a4d172787a84812c5620c1e/src/matrix.ts#L148

**Comment by clokep** [comment]
@chris-aeviator The code snippet given there was an example of how this *could* be implemented, unfortunately support for this was never added. So, there's no option there at the moment. 😢
