### ISSUE TITLE
Sending Bot messages to Matrix that are not listed in Riot

### ISSUE THREAD

**Issue by grinono** [matrix-org/matrix-js-sdk#1065]
We would like to send bot messages to matrix that are not shown within the Riot client. This so we can deliver support from Riot without the need of seeing all messages send between client  (giftedchat) and the bot.
Is it possible to send a message with a different msgtype like below. That is not listed in the roit interface? 
When testing Riot listed all messages.

const message = {
        body: args.text,
        msgtype: "bot",
        localState: true
      };

**Comment by t3chguy** [comment]
You should send an event type which is not `m.room.message` in that case, e.g `custom.grinono.something`

**Comment by grinono** [comment]
thanks,
