### ISSUE TITLE
How to upload an image from a URL

### ISSUE THREAD

**Issue by BurnyBoi** [matrix-org/matrix-js-sdk#1107]
Similar to what is being done in #238, I am trying to take an image url, and pipe the image into uploadContent(). Here is what I am testing with:

```
var infoMatrix = {
		    "name": "test",
		    "type": "image/jpg",
		    "rawResponse": 0,
		    "onlyContentUri": 1
		};
		
		request.get("http://i3.ytimg.com/vi/J---aiyznGQ/mqdefault.jpg", function(err, res, body){
			
			matrixClient.uploadContent(body, infoMatrix).done(function(url) {
		                
				console.log(url);
				var content = {
		                    msgtype: "m.image",
		                    body: "difhsiudfhvos.jpg",
		                    url: url
		                };
		                matrixClient.sendMessage(room.roomId, content);
            		});
			
		});
```

When I run this, it runs the command without any errors, but the message does not have the image, just a blank file:

![2019-12-08_14-36-30_283x64_scrot](https://user-images.githubusercontent.com/41203525/70394931-c99e4300-19c7-11ea-8c9a-4054161d585e.png)
Attempting to click download does not show the file either. It just says: "The image <URL> cannot be displayed because it has errors." Could I get some clarification on how to accomplish this?

**Comment by turt2live** [comment]
This issue tracker is not a great place to get support - please visit [#matrix-dev:matrix.org](https://matrix.to/#/#matrix-dev:matrix.org) instead to get some help with the js-sdk.

**Comment by scottwestover** [comment]
@BurnyBoi I was also having the same issue. I was finally able to get the `uploadContent` method to work. Hopefully this helps you:

```
const axios = require('axios');
const MatrixJsSdk = require('matrix-js-sdk');

(async () => {
  const url = 'http://i3.ytimg.com/vi/J---aiyznGQ/mqdefault.jpg';
  try {
    const imageResponse = await axios.get(url, { responseType: 'arraybuffer' });
    const imageType = imageResponse.headers['content-type'];
    const matrixClient = MatrixJsSdk.createClient('http://localhost:8008');
    await matrixClient.login('m.login.password', {
      password: 'foo',
      user: '@bob:synapse',
    });
    const uploadResponse = await matrixClient.uploadContent(imageResponse.data, { rawResponse: false, type: imageType });
    const matrixUrl = uploadResponse.content_uri;
    console.log(matrixUrl);
    const sendImageResponse = await matrixClient.sendImageMessage('!JIsalWHQCskeFGvtZs:synapse', matrixUrl, {}, '');
    console.log(sendImageResponse);
  } catch (error) {
    console.log(error);
  }
})();
```

![Screen Shot 2019-12-11 at 12 22 53 PM](https://user-images.githubusercontent.com/9931822/70644431-fd1fde00-1c10-11ea-8027-7bbccf1575e9.png)

**Comment by mmeksasi** [comment]
You need to ad now in opts { onlyContentUri: false }
export const SendImageMessage = async ({ url, roomID, info, text }) => {
  try {
     const imageResponse = await axios.get(url, { responseType: 'arraybuffer' });
     const imageType = imageResponse.headers['content-type'];
     const uploadResponse = await matrixAlias.uploadContent(imageResponse.data, {
       rawResponse: false,
       type: imageType,
       onlyContentUri: false,
     });
    const matrixUrl = uploadResponse.content_uri;
    const result = await matrixAlias.sendImageMessage(
      roomID,
      matrixUrl,
      info,
      text
    );
    console.log('SEND MESSAGE IMAGE RESULT ', result);
  } catch (err) {
    console.log('SEND MESSAGE IMAGE ERROR ', err);
  }
};

**Comment by oelison** [comment]
Why give a hint to a chat group and not improve or at least check the documentation and close it?

**Comment by nukeop** [comment]
This is horrible. Why does it need so much manual work? The bot sdk is even worse. Why can't it be a single line to upload an image? That's a very common use case.

**Comment by t3chguy** [comment]
Because downloading an image isn't easy in certain Javascript environments. Like web with CORS.

**Comment by nukeop** [comment]
How does that influence poor sdk design?

**Comment by t3chguy** [comment]
The SDK has no consistent cross platform way to download an image that wasn't uploaded to matrix to begin with. So you need to download it yourself. As for why uploading content and sending an event is separate is that it's very different for encrypted events. So having a single method only usable for unencrypted events would be very inconsistent SDK design.

**Comment by nukeop** [comment]
You know in Discord it only takes a single line: https://discordjs.guide/popular-topics/embeds.html#using-the-embed-constructor

You only need to give it a link to the image you want to embed. Why can't matrix do it?

**Comment by t3chguy** [comment]
Discord doesn't support encryption. Discord can also have their server accept a url and just use that as media. Matrix doesn't support that. Makes for a much thicker SDK. They're not really comparable other than on the UX or surface level.

**Comment by nukeop** [comment]
I don't get it, what does encryption change here? It's unrelated to SDK or API design.

**Comment by t3chguy** [comment]
Encryption requires you to generate a thumbnail or poster frame client side which is very difficult to do in one way cross platform. Super easy to do in the web, hard to do in Node or Deno which can't render these medias. The SDK has wide Javascript runtime support which means it doesn't have web specific or node specific or any other specific code.

**Comment by t3chguy** [comment]
Unless you want an api which looks like

Client.sendImage(downloadFn, thumbnailFn, room Id)

Where you pass callbacks on how to perform the download and thumbnailing in your specific environment.

**Comment by nukeop** [comment]
Why can't the server do it? This is not my problem, as a consumer of the API.

**Comment by t3chguy** [comment]
The server can't generate thumbnails for encrypted media to which it has no keys. That's the whole point of end to end encryption.

**Comment by nukeop** [comment]
How about in rooms with no encryption? That seems like a serious anti-feature

**Comment by t3chguy** [comment]
@nukeop in such a case a one-liner doing both upload (local file/buffer) and send would be feasible, but having to use a very different API depending on if a room is encrypted or not sounds like poor SDK design. As for the case of wanting the SDK to handle uploading files from a URL it'd want something like https://github.com/matrix-org/matrix-spec-proposals/pull/2370
