### ISSUE TITLE
URL preview endpoint / Unhandled rejection Error: CORS request rejected

### ISSUE THREAD

**Issue by menturion** [matrix-org/matrix-js-sdk#1119]
I am getting the following unhandled rejection Error: CORS request rejected. 
This only occurs for the "/_matrix/media/r0/preview_url" endpoint on a localhost dev environment as well as for a server setup with different domains.

Below is the issue message based on localhost:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
(index):1 Access to XMLHttpRequest at 'http://localhost:8008/_matrix/media/r0/preview_url?url=[myurl]&ts=1576486679181&access_token=[myaccesstoken]' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
browser-matrix.min.js?v=1b6cf9d8641ecf718e165ead45b10bda:1 Unhandled rejection Error: CORS request rejected: http://localhost:8008/_matrix/media/r0/preview_url?url=[myurl]&ts=1576486679181&access_token=[myaccesstoken] at (.../browser-matrix.min.js?v=1b6cf9d8641ecf718e165ead45b10bda:1:576737) at XMLHttpRequest.o.onreadystatechange
```

**Comment by turt2live** [comment]
The server is returning 404 and not putting appropriate headers on the response. 404 is a normal error for this endpoint

**Comment by menturion** [comment]
Thanks for your reply.
Got it to work. I missed to enable 'url_preview_enabled' (and 'url_preview_ip_range_blacklist') within the homesever settings.
