### ISSUE TITLE
encryption with olm 

### ISSUE THREAD

**Issue by MadonnaEssam** [matrix-org/matrix-js-sdk#1136]
,I'm working with matrix-js-sdk version 2.4.6 and olm version 3.0.0 to make encryption and found this is issue
![1](https://user-images.githubusercontent.com/52240034/71614617-62824180-2bb5-11ea-9e2a-c0f6a8f58300.PNG)

**Comment by turt2live** [comment]
Your WASM is invalid for Olm. You should also consider using a newer version of Olm.

#matrix-dev:matrix.org is the best place for support.
