### ISSUE TITLE
unable to encrypt

### ISSUE THREAD

**Issue by MadonnaEssam** [matrix-org/matrix-js-sdk#1137]
I'm used 'olm' version '3.1.4' and 'matrix-js-sdk' version '2.4.6'
Trying use end to end encryption supported in matrix using olm

I'm using the following code snipping:
   ```
     const cryptoStore = new sdk.MemoryCryptoStore(window.localStorage);
        const webStorageSessionStore = new sdk.WebStorageSessionStore(window.localStorage);
        var matrixStore = new sdk.MatrixInMemoryStore();

        matrixClient = sdk.createClient({
          baseUrl: 'SERVER_HOME',
          accessToken: token,
          userId: 'USER_ID',
          store: matrixStore,
          sessionStore: webStorageSessionStore,
          cryptoStore: cryptoStore,
          deviceId: 'DEVICE_ID'});

matrixClient.initCrypto()
          .then(() => {
            matrixClient.startClient({ initialSyncLimit: 10 });
          })
```

1- I have error with post key/upload API bad request 

`
REQUEST: POST
Request URL: https://SERVER_HOME/_matrix/client/r0/keys/upload/DEVICE_ID?access_token=XXXX`

`RESPONSE: 400 Bad Request
{"errcode":"M_UNKNOWN","error":"One time key signed_curve25519:XXXX already exists. Old key: {\"key\":\"64zJVMH61Toei8Kaz2SRXEZ4VyNBjjG2vfaGjSXXXX\",\"signatures\":{\"@USER_ID\":{\"ed25519:869254020336060\":\"HBnlhazYGY+IrvImq5d4OcIYsXeo094St2p/SMYWobMfteML1gH1jMSUmAh9o7EYIXQMnshiPSh6FSdL4XXXXw\"}}}; new key: {'key': 'VSfPQ7NFzdPl0owA1pVK8CqTzLCyF6NQCuS8aTIIYmc', 'signatures': {'@USER_ID': {'ed25519:869254020336060': 'rIQHea/3kh5w8PaC91H83zsTKQDevbkPpnJ5Dpj7YHv3o4Jzq1O3AmgMzfhFzhlXBwn1N6gRPfC+jNMCIPXXXX'}}}"}
`

2- When I test it with encryption Roit room and try to send message from sdk to Roit  get this error
` Error sending event UnknownDeviceError: This room contains unknown devices which have not been verified. We strongly recommend you verify them before continuing.`

3- When I test it with encryption Roit room and send message from Roit to sdk I get this error 
` Error decrypting event (id=xxxx): DecryptionError[msg: The sender's device has not sent us the keys for this message., session: FoIZTb4W906iFiQofhzgyZlkjeR9XazjN9vfIC9uzFQ|nCwWvT+VU/FVz7uNLojW51+PtkrXj++eMC1d/Xxxxxxx]`

**Comment by select** [comment]
> 2- When I test it with encryption Roit room and try to send message from sdk to Roit get this error
Error sending event UnknownDeviceError: This room contains unknown devices which have not been verified. We strongly recommend you verify them before continuing.

@MadonnaEssam  How did you solve this?

**Comment by Varkal** [comment]
@select @MadonnaEssam  Did you find any solution ?

**Comment by select** [comment]
I got it to work with the latest version of the matrix sdk and olm library, see https://github.com/matrix-org/matrix-js-sdk/issues/731
