### ISSUE TITLE
backing up private part of one-time keys

### ISSUE THREAD

**Issue by cedricvanrompay** [matrix-org/matrix-js-sdk#1149]
I have a scenario similar to the following:
- Alice creates an account at a homeserver,
with E2E enabled so her Matrix client creates and upload some one-time keys;
She then goes offline.
- Bob creates an account and an encrypted room to send an encrypted message to Alice.
His client will claim one of the one-time keys of Alice, derive a key from it and send the room key to Alice using this key that was derived (right?); Bob then goes offline.
- Alice goes back online **from another, empty machine** and wants to read the (encrypted) message Bob sent to her.

**Question:** is there a way to back up Alice's client information (in order to transfer it to the new machine) using Matrix JS SDK to make the above scenario possible?

**Comment by cedricvanrompay** [comment]
What I had in mind would be export/import methods for the *whole* crypto store. Right now the only keys you seem to be able to export / import are room keys, but in my use case when Alice goes offline there are no rooms yet.

**Comment by turt2live** [comment]
Questions about usage of the SDK, and the Matrix API in general, are best asked in #matrix-dev:matrix.org and not in our issue tracker.
