### ISSUE TITLE
Example of how to implement e2ee

### ISSUE THREAD

**Issue by menturion** [matrix-org/matrix-js-sdk#1156]
Currently, there are a few examples of how to use the SDK (e.g. VoIP).
It would be very helpful if you would also provide a detailed example for implementing e2ee.

**Comment by Ishaan28malik** [comment]
I would like to work on the same, Can you suggest where am I supposed to push the detailed examples?

**Comment by cedricvanrompay** [comment]
I wrote https://github.com/matrix-org/matrix-js-sdk/blob/6aa5d39357c114490076dba00482e16abe03e5ee/examples/crypto-browser/olm-device-export-import.js

@menturion did you find this file during your research ? If not maybe we should add a link to it. If you did can you tell us which parts you don't understand or what you think is missing ?

**Comment by menturion** [comment]
@cedricvanrompay 

Many thanks for the info and the E2EE example. I tested it a while and I'm constantly getting the below error message ...

> Error sending event UnknownDeviceError: This room contains unknown devices which have not been verified. We strongly recommend you verify them before continuing.

... when sending e.g. a text message (`client.sendTextMessage()`) although the member devices of a given room should have been verified through that snippet ...

```
        // Marking all devices as verified
        let room = this.getRoom(roomId);
        let members = (await room.getEncryptionTargetMembers()).map(x => x["userId"])
        let memberkeys = await this.downloadKeys(members);
        for (const userId in memberkeys) {
          for (const deviceId in memberkeys[userId]) {
            await this.setDeviceVerified(userId, deviceId);
          }
        }
```

Does your code only work with certain (>=) release versions of Synapse and/or JS SDK?

**Comment by DhairyaBahl** [comment]
@menturion This issue seems to be inactive from a long time. Kindly assign me this issue if its still available.

**Comment by menturion** [comment]
@DhairyaBahl 

I think that this is still needed. 
IMHO, such an example should cover bootstrapping secure storage and cross-signing, DB startup, device listeners, cryptoCallbacks etc.

**Comment by DhairyaBahl** [comment]
@menturion OK I will work on this issue and make a PR asap. although i don't understand the issue but its docs labelled so i will give a try on this and will take help from the other comments. 

Thanks :)

**Comment by murlock1000** [comment]
In https://github.com/murlock1000/matrix-js-bootstrap I have implemented scripts on:

-  Bootstrapping Cross-signing
-  Bootstrapping Secure Storage
-  Cross-signing key recovery from Secure Storage
-  Signing a new version of Secure Storage using master key

**Comment by menturion** [comment]
@murlock1000 

Perhaps it would still be helpful to additionally include device hydration in your library. Device (re)hydration already works.

**Comment by Johennes** [comment]
Closing in favor of https://github.com/matrix-org/matrix-js-sdk/issues/437.
