### ISSUE TITLE
Missing function for getting the messages in a room

### ISSUE THREAD

**Issue by Alacho2** [matrix-org/matrix-js-sdk#1165]
Since the documentation isn't very clear about this. I think you're lacking a function to get the message in a Room. How is this done? Should the endpoint be used directly?

**Comment by t3chguy** [comment]
Its in the README:
```
Object.keys(client.store.rooms).forEach((roomId) => {
  client.getRoom(roomId).timeline.forEach(t => {
      console.log(t.event);
  });
});
```
https://github.com/matrix-org/matrix-js-sdk#in-nodejs

**Comment by Alacho2** [comment]
Thanks for the quick response, but this doesn't answer the question. It gets the stored message from the client, but not passed the point of the stored message. How do I get passed that point?

**Comment by t3chguy** [comment]
if you ran `startClient` as per the README then the client will long-poll the `/sync` API to get all changes from the server (unless you configured a filter then only the changes matching that filter)

**Comment by Alacho2** [comment]
The client's been started correctly: 

` 
this.client = sdk.createClient("https://tchncs.de");
    await this.client.login(
      "m.login.password",
      {
        "user": "username",
        "password": "password"
      }
    );

    this.client.startClient();

    this.client.on("Room.timeline", (event, room, toStartOfTime) => {
      if (event.getType() !== "m.room.message") {
        return;
      }

      if (event.getRoomId() === this.state.room) {
        this.setState(prevState => {
          const currentMessages = prevState.messages;
          const obj = {
            author: event.event.sender || event.event.user_id,
            body: event.event.content.body
          };
          currentMessages.unshift(obj);

          return {messages: currentMessages};
        });
      }
    });
`

It might be starting a long-polling, as per the README, but no new events are coming in. And no filter is configured.

**Comment by t3chguy** [comment]
I don't think `client.login` does what you think it does,
it just sends the login request, does not mutate the MatrixClient to attach the access token, etc to it, you must do that yourself. So you're waiting on an unauthenticated client to receive messages.

**Comment by Alacho2** [comment]
Not really, I'm able to send, receive and get the first 5-10 messages from the chat. It works perfectly and it's super easy and simple. The fact that there is no 
`const room = new Room({roomId}).getAllMessages({from: x, to: y})` is mindblowing to me.

**Comment by t3chguy** [comment]
It implemented, it's for paginating a room, it happens on a syncing client when you extend the size of the timeline window you wish to view: https://github.com/matrix-org/matrix-js-sdk/blob/bdd2a9e7e878358a5af345895a0297b6cc80777f/src/timeline-window.js#L263

**Comment by Yassir4** [comment]
For anyone else looking to get the previous messages in a room, you can use  the [createMessagesRequest](https://github.com/matrix-org/matrix-js-sdk/blob/b6d40078d9a13d8f4cf5d8e0725a1fe91a281904/src/client.ts#L5812)

**Comment by texuf** [comment]
Sorry for commenting on a closed issue, but I think you're looking for 
```
const events = matrixClient
    .getRoom(roomId)
    ?.getLiveTimeline()
    .getEvents()
```
Using this to load up your current messages, then listening to these events (and probably a few more) you can reliably render timeline items
```
ClientEvent.Room
RoomEvent.Timeline
RoomEvent.Redaction
MatrixEventEvent.Decrypted
MatrixEventEvent.Replaced
```

**Comment by StefanAmEnde** [comment]
> Sorry for commenting on a closed issue, but I think you're looking for
> 
> ```
> const events = matrixClient
>     .getRoom(roomId)
>     ?.getLiveTimeline()
>     .getEvents()
> ```
> 
> Using this to load up your current messages, then listening to these events (and probably a few more) you can reliably render timeline items
> 
> ```
> ClientEvent.Room
> RoomEvent.Timeline
> RoomEvent.Redaction
> MatrixEventEvent.Decrypted
> MatrixEventEvent.Replaced
> ```

@texuf Unfortunately this solution does not retrieve all messages that have been sent to the specified room. It always stops at some undetermined point in the past where it won't load older messages. The more recent messages are always there.



> For anyone else looking to get the previous messages in a room, you can use the [createMessagesRequest](https://github.com/matrix-org/matrix-js-sdk/blob/b6d40078d9a13d8f4cf5d8e0725a1fe91a281904/src/client.ts#L5812)

This approach does not work for encrypted messages since ```client.createMessagesRequest``` doesn't return MatrixEvents but some other datatype which I can't use for decryption.

Does anyone know a solution to retreive all messages from a room as MatrixEvents or why getLiveTimeline().getEvents() doesn't retrieve them all?

**Comment by StefanAmEnde** [comment]
Thanks to #3001 I found it. To retrieve all messages from a room:
```
const room = client.getRoom(roomId)
const scrollback = await client.scrollback(room, Number.MAX_SAFE_INTEGER)
const events = scrollback.getLiveTimeline().getEvents()
```
```events``` now contains all events.

**Comment by skylord123** [comment]
For others looking for a solution to paginating through a rooms event timeline I left a comment here with how to do this:
https://github.com/matrix-org/matrix-js-sdk/issues/3001#issuecomment-1868109829

Remember, sharing is caring!
