### ISSUE TITLE
docs: links to MatrixClient at global.createClient generated with '-' instead of '.'

### ISSUE THREAD

**Issue by salzig** [matrix-org/matrix-js-sdk#1179]
docs: links to MatrixClient at [global.createClient](http://matrix-org.github.io/matrix-js-sdk/4.0.0/global.html#createClient) generated with '-' instead of '.'

I'm not really sure if [module-client-MatrixClient.html](http://matrix-org.github.io/matrix-js-sdk/4.0.0/module-client-MatrixClient.html) or [module-client.MatrixClient.html](http://matrix-org.github.io/matrix-js-sdk/4.0.0/module-client.MatrixClient.html) is the right filename to be generated in the first place, but at least [module-store_memory.MemoryStore.html](http://matrix-org.github.io/matrix-js-sdk/4.0.0/module-store_memory.MemoryStore.html) also uses a '.' before the Class/Object-name. 

Sadly i don't seem to understand the problem here. Feel free to hint me to right direction so i can provide a merge request.

**Comment by turt2live** [comment]
Probably just need to fix the jsdoc comments in one of those places, whichever is more consistent.

**Comment by salzig** [comment]
Don't know why i didn't saw the difference at first. :-/
