### ISSUE TITLE
Room topic

### ISSUE THREAD

**Issue by grigori-gru** [matrix-org/matrix-js-sdk#1273]
How can I get room topic? I have found method named `setRoomTopic` but how can I get current?

**Comment by t3chguy** [comment]
`room.currentState.getStateEvents("m.room.topic", "")`

**Comment by grigori-gru** [comment]
@t3chguy 
Yes, I updated it in my issue, but maybe some easier way to get it exists?

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/77156917-48f7e400-6a98-11ea-8c9e-1962cfb385f5.png)
Does not appear so. You should be using:

```
room.currentState.getStateEvents("m.room.topic", "").getContent().topic
```

otherwise it'll break for encrypted rooms where `.event` is an encrypted blob.
