### ISSUE TITLE
Guests are not allowed to use TURN servers

### ISSUE THREAD

**Issue by awesome-michael** [matrix-org/matrix-js-sdk#1274]
Synapse allows to configure that TURN servers are available for guests. The matrix-js-sdk prevents all guests from requesting the TURN server from the server (Synapse) in the `checkTurnServers` function in the `client.js` file.

Is there a way to check the servers configuration before blocking TURN servers?

**Comment by t3chguy** [comment]
You could just try and get turnServer and if it fails with https://github.com/matrix-org/synapse/blob/9c1b83b0078aa9cc1bb902e14d3f7302625ba099/synapse/api/auth.py#L235-L240 then you know why.

**Comment by awesome-michael** [comment]
I would just remove the complete block

```
    if (client.isGuest()) {
        return; // guests can't access TURN servers
    }
```

then.

**Comment by t3chguy** [comment]
Yes, sounds reasonable to me.
