### ISSUE TITLE
Register new user from matrix-js-sdk

### ISSUE THREAD

**Issue by IProudNoob** [matrix-org/matrix-js-sdk#1316]
Hi :)
How to register a new user not on the site but using the library matrix-js-sdk?

Thx a lot.

**Comment by t3chguy** [comment]
You can use `client.register(...)` as per the docs: http://matrix-org.github.io/matrix-js-sdk/5.2.0/module-base-apis.MatrixBaseApis.html#register

Github issues are not a support forum, use https://matrix.to/#/#matrix-dev:matrix.org for future queries

**Comment by nikiforos-dev** [comment]
I would like to know how to do this and it looks like the above link is dead
