### ISSUE TITLE
Enable support for usage through a CDN

### ISSUE THREAD

**Issue by theawless** [matrix-org/matrix-js-sdk#1383]
Hi, I noticed that the browserify build was not showing up in any of the CDNs.
jsDeliver: https://www.jsdelivr.com/package/npm/matrix-js-sdk
unpkg: https://unpkg.com/matrix-js-sdk/

I think adding "dist" to the files section in package.json should enable it. Is there a reason why this is not being done? It would be really helpful if we can use a CDN to fetch the library. Thanks!

**Comment by t3chguy** [comment]
https://www.jsdelivr.com/package/npm/matrix-js-sdk has it?
https://cdn.jsdelivr.net/npm/matrix-js-sdk@6.1.0/lib/browser-index.min.js but it seems very short/nearly empty so not sure what's going on there

**Comment by t3chguy** [comment]
Indeed adding /dist/* may fix this.

**Comment by theawless** [comment]
Thanks a lot for the quick fix! 👍
