### ISSUE TITLE
Missing required field when sending `m.key.verification.accept`

### ISSUE THREAD

**Issue by Dominaezzz** [matrix-org/matrix-js-sdk#1390]
In [`m.key.verification.accept`](https://matrix.org/docs/spec/client_server/r0.6.0#m-key-verification-accept), `method` is a required field but when it is sent [here](https://github.com/matrix-org/matrix-js-sdk/blob/b29176507c7200f9bc3fa1598c6b8ba78aead010/src/crypto/verification/SAS.js#L384) the `method` field is not specified.

`transactionId` also isn't specified but it's injected [here](https://github.com/matrix-org/matrix-js-sdk/blob/b29176507c7200f9bc3fa1598c6b8ba78aead010/src/crypto/verification/request/ToDeviceChannel.js#L233).

Solution:
Add `method: SAS.NAME` like is done [here](https://github.com/matrix-org/matrix-js-sdk/blob/b29176507c7200f9bc3fa1598c6b8ba78aead010/src/crypto/verification/SAS.js#L247).

**Comment by uhoreg** [comment]
This was a spec bug (now fixed), rather than a bug in the implementation.
