### ISSUE TITLE
Error when loading the VOIP example

### ISSUE THREAD

**Issue by stevedanOgochu** [matrix-org/matrix-js-sdk#1396]
I am trying to run this example but cant seem to get it to work. Is there anything i am doing wrong 
This is the part i modified 

```
var BASE_URL = "https://matrix.org";
var TOKEN = "my own token i got when i signed up to matrix";
var USER_ID = "@my user name:matrix.org";
var ROOM_ID = "!OGEhHVWSdvArJzumhm:matrix.org";
```

![error token](https://user-images.githubusercontent.com/61468301/83687703-714da400-a5ec-11ea-8b9e-f6d1502278ea.png)

**Comment by t3chguy** [comment]
That error is from the server and looks like an invalid token.

**Comment by stevedanOgochu** [comment]
Isnt the token the one you get when you sign in to the matrix server?

**Comment by stevedanOgochu** [comment]
I don't know hoe to run the example, please can you help me, i first put the matrix.js code in the lib/matrix.js and inlcuded it in the index.html, and change the personal information for mine, the ones i got when I registered to the matrix server.

**Comment by t3chguy** [comment]
> Isnt the token the one you get when you sign in to the matrix server?

Yes, it is.

**Comment by stevedanOgochu** [comment]
running the npm run build command gave me this 
```
n build
npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/stevedan/.npm/_logs/2020-06-03T21_12_06_194Z-debug.log
stevedan@steve
```

So I copied the sdk code into the matrix.js, and ran the server but i got the error i showed at first

**Comment by t3chguy** [comment]
This issue tracker is for bugs, for support use #matrix-dev: https://matrix.to/#/#matrix-dev:matrix.org
