### ISSUE TITLE
Markdown parser

### ISSUE THREAD

**Issue by resynth1943** [matrix-org/matrix-js-sdk#1425]
I love Matrix and Element. I'm an avid user of both products.

Nevertheless, let's cut right down to the chase: the Markdown parser you seem to be using currently (commonmark) is incapable of rendering `~~` to a strike-through.

After Discord implemented this, I think it's an expected feature. I have done some research, and markdown-it *does* support strike-through (and seems to have a better ecosystem).

Would you be open to switching to another Markdown parser?

https://github.com/commonmark/commonmark.js/issues/120, an issue filed in 2017, asks for strike-through support. The maintainers seem to be oblivious to it. Perhaps this is the sign of poor maintenance / community?

Anyway, I'd love to have a discussion. If not markdown-it, perhaps something else?

Thanks,
Resynth

**Comment by t3chguy** [comment]
js-sdk doesn't do any Markdown parsing whatsoever.

**Comment by resynth1943** [comment]
> matrix-js-sdk doesn't do any Markdown parsing whatsoever. Perhaps you want [vector-im/riot-web#5940](https://github.com/vector-im/riot-web/issues/5940)

Wait, what? I found the Markdown parser here. I even grep'd the source code.

**Comment by t3chguy** [comment]
Its in matrix-*react*-sdk, not matrix-*js*-sdk: https://github.com/matrix-org/matrix-react-sdk/blob/96ba645cbd8774148f86e049222268cebd3638e2/package.json#L62

Not sure what you grep'd.
