### ISSUE TITLE
Add method to bootstrap Secure Secret Storage programmatically without user interaction

### ISSUE THREAD

**Issue by menturion** [matrix-org/matrix-js-sdk#1455]
Currently, the method `Crypto.prototype.bootstrapSecretStorage` requires a user interaction. 

For all clients that implement custom workflows a method is needed that supports passing a key backup passphrase programmatically.

**Comment by turt2live** [comment]
The function contract here doesn't require UI, just recommends it. Is tehre a reason why the programmatic interface can't use the callbacks?

**Comment by menturion** [comment]
@turt2live 

Many thanks for your reply and your hint about the `cryptoCallbacks` I wasn't aware of. 
The interface should work with them.
