### ISSUE TITLE
Support of a new content.format "org.matrix.custom.json"

### ISSUE THREAD

**Issue by menturion** [matrix-org/matrix-js-sdk#1460]
Are there efforts to introduce a content format of type `org.matrix.custom.json` to indicate that the `formatted_body` contains valid JSON?

Processing JSON would be more efficient (than parsing `org.matrix.custom.html`) e.g. with respect to current thread replies ... or future features. Every client should be able to parse JSON.

**Comment by turt2live** [comment]
Custom formats are permitted under the spec. A formalized specification would need an MSC.

**Comment by menturion** [comment]
Ok, thanks for the info. 
So, I'm free to define/add a `org.matrix.custom.json` content format.
