### ISSUE TITLE
Option for "MatrixBaseApis.prototype.fetchRoomEvent" to return object of class "MatrixEvent"

### ISSUE THREAD

**Issue by menturion** [matrix-org/matrix-js-sdk#1461]
For further processing it would be great if `MatrixBaseApis.prototype.fetchRoomEvent` would return an object of class `MatrixEvent`.

**Comment by turt2live** [comment]
the `MatrixBaseApis` class is meant to be as close to the http layer as possible.

**Comment by menturion** [comment]
@turt2live 

Thanks for your reply.
What would be the recommended way to fetch a single MatrixEvent that currently does not exist within the store? 
Fetching a timeline segment that contains the event breaks the existing live timeline of the room.
