### ISSUE TITLE
"_http.authedRequest" in case of "uploadDeviceSigningKeys" seems not to work with password providers

### ISSUE THREAD

**Issue by menturion** [matrix-org/matrix-js-sdk#1505]
matrix-js-sdk: v8.4.1
synapse: v1.20.1

I am trying to bootstrap cross-signing along with a 3pid login using a password provider ...

```
    const _doBootstrapAuth = async (makeRequest) => {
        await makeRequest({
            type: 'm.login.password',
            identifier: {
                type: 'm.id.thirdparty',
                medium: 'email',
                address: userMail,
            },
            password: userPwd,
        });
    };

    try {
        await Client.get().bootstrapCrossSigning({
            authUploadDeviceSigningKeys: _doBootstrapAuth,
            setupNewCrossSigning: forceReset,
        });
    } catch (e) {
        console.error('Error bootstrapping cross-signing', e);
    }
```

The `authedRequest` looks fine, sending the auth dict with the 3 cross-signing keys. The user is authenticated successfully and the password provider returns the `user_id` upon authentication.

However, the following errors are shown in ...

-1- console
```
POST http://localhost:8008/_matrix/client/unstable/keys/device_signing/upload 400 (Bad Request)
crypt.js:400 Error bootstrapping cross-signing M_MISSING_PARAM: Unknown message
    at parseErrorResponse ...
    at Object.callback ...
    at on_end ...
    at XMLHttpRequest.on_state_change ...
```

-2- homeserver.log
```
2020-10-12 07:46:47,277 - synapse.http.server - 76 - INFO - POST-112 - <XForwardedForRequest at 0x7f5dda580b70 method='POST' uri='/_matrix/client/unstable/keys/device_signing/upload' clientproto='HTTP/1.1' site=8008> SynapseError: 400 - 
2020-10-12 07:46:47,277 - synapse.access.http.8008 - 311 - INFO - POST-112 - - - 8008 - {@testuser:localhost} Processed request: 0.486sec/-0.000sec (0.000sec, 0.000sec) (0.001sec/0.483sec/2) 40B 400 "POST /_matrix/client/unstable/keys/device_signing/upload HTTP/1.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36 Edg/86.0.622.38" [0 dbevts]
```

I guess that on the level of the password provider the `M_MISSING_PARAM` is unknown and that this missing parameter isn't merged into the response on the level of the calling function when using a password provider. 

If this is a general issue cross-signing will currently not work with any password provider.

**Comment by jryans** [comment]
What do you mean by password provider here? Is it a Synapse extension for managing passwords and identity?

**Comment by menturion** [comment]
@jryans 

Thanks for your reply.

I meant the password providers you can specify within the `homeserver.yaml` (section: `password_providers`).
One example would be this one https://github.com/ma1uta/matrix-synapse-rest-password-provider/blob/master/rest_auth_provider.py.

**Comment by jryans** [comment]
Hmm, well for the password provider itself, cross-signing key upload should be roughly the same as any action that uses [UI auth](https://matrix.org/docs/spec/client_server/unstable#user-interactive-authentication-api).

It's true that `authedRequest` does not handle UI auth itself. That is typically integrated with a UI layer that can prompt the user as needed, etc.

Perhaps it would be good to discuss in a Synapse support room about UI auth and password providers?

**Comment by menturion** [comment]
@jryans 

I will file this bug in the Synapse repo. 
Could you pls tell me which `M_MISSING_PARAM` the SDK is likely expecting in the Synapse response.

**Comment by jryans** [comment]
> Could you pls tell me which `M_MISSING_PARAM` the SDK is likely expecting in the Synapse response.

Sorry, at first glance, I can't spot it from this info. It may help to trace which part of Synapse is triggering the error code.
