### ISSUE TITLE
"WebRTC is not supported in this environement" in nodejs

### ISSUE THREAD

**Issue by k2s** [matrix-org/matrix-js-sdk#1538]
**Describe the bug**
When using SDK v9 in nodejs following error is logged: `WebRTC is not supported in this environement`
The message originates from https://github.com/matrix-org/matrix-js-sdk/blob/34882cc4380d24f7670964f946fd628243800b71/src/webrtc/call.ts#L1572.

**To Reproduce**
1. use matrix.js-sdk v9.0.1
2. send message with `matrixClient.sendEvent(roomId, 'm.room.message', content, '')`
3. you will see error message `WebRTC is not supported in this environement` in console

**Expected behavior**
This should not be reported as error when running under nodejs.

**Desktop (please complete the following information):**
 - Linux
 - nodejs 12.15.0
 - matrix-js-sdk: ^9.0.1

**Comment by vractal** [comment]
Im also facing this problem, did you find a solution @k2s ?

**Comment by vractal** [comment]
ah sorry, I thought  the sdk wasnt working because of this error , but after looking in the sdk code I figured this is more like an warning, and could find the real error in my code...  so  yeah, for sure is a misleading "error" message to have

**Comment by erickgtzh** [comment]
When I'm using the sdk.CreateClient({ ... }) I'm getting this "WebRTC is not supported in this environement", has anyone fixed it??

**Comment by jryans** [comment]
This logging should no longer be happening as of 9.5.0.
