### ISSUE TITLE
createRoom() name property isnt working

### ISSUE THREAD

**Issue by KineticFox** [matrix-org/matrix-js-sdk#1540]
```javascript
client.createRoom({ name: 'somename', ...})
```
room has emtpy room name property

```javascript
client.createRoom({ room_alias_name: 'somename', ...})
```
room has name property but it includes 'somename:homeserver url'...

refering to this: http://matrix-org.github.io/matrix-js-sdk/8.5.0/module-base-apis.MatrixBaseApis.html#createRoom

**Comment by t3chguy** [comment]
Definitely works here:
![image](https://user-images.githubusercontent.com/2403652/99379881-23d6a200-28c1-11eb-8099-6273b140a775.png)

**Comment by KineticFox** [comment]
works for me too. seems like i had not made a correct async call. Thanks for the response.
