### ISSUE TITLE
Call errors are thrown (i.e. not caught) although "CallEvent.Error" listener is set

### ISSUE THREAD

**Issue by menturion** [matrix-org/matrix-js-sdk#1569]
Example (also tested with Element Web): Start a screen sharing session -> `placeScreenSharingCall` and press the 'Cancel' button of the browser's popup window. 

The following error is thrown ...
```
Uncaught (in promise) Error: Failed to get screen-sharing stream: : NotAllowedError: Permission denied
    at MatrixCall.placeScreenSharingCall
```

... although the error listener is attached to each call through `call.on(CallEvent.Error, (err) => {...});`.

In case of `placeScreenSharingCall` it is stated that `@throws If you have not specified a listener for 'error' events`. However, the `CallEvent.Error` listener doesn't fire if a call (of type `PlaceCallType.Voice`, `PlaceCallType.Video` or `PlaceCallType.ScreenSharing`) is canceled, not permitted etc.

**Comment by arnab15** [comment]
hello,
I have knowledge of javascript ,nodejs,reactjs,expressjs, Mongodb but I haven't contributed to any open-source project before so I'm a beginner. I would like to contribute to this project.
how should I start can anyone suggest to me the way should I start contributing.

**Comment by SimonBrandner** [comment]
[#16052](https://github.com/vector-im/element-web/issues/16052) is a duplicate. I'll close it later

**Comment by SimonBrandner** [comment]
I can't see any reason for this not working. I have a [workaround](https://github.com/SimonBrandner/matrix-js-sdk/tree/fix-16052) that changes `CallEvent.Error = 'error'` to `CallEvent.Error = 'callError'` but that is quite weird and hopefully unnecessary.

@dbkr seems to be the author of the file, maybe he can figure this out.

**Comment by menturion** [comment]
@SimonBrandner 

My workaround is as follows.
Due to some call related exceptions are emitted by a general `error` event and therefore are no longer bound to calls I added the general error listener, e.g. like this ...

```
    Client.get().on('error', (e) => {
        // Something went wrong
        if (DEBUG) {
            console.log(e);
        }
    });
```

To catch the webcam exception (e.g. in case a user rejects the access to the webcam) you can catch the PROMISE of the method `placeScreenSharingCall` : 

```
        try {
            await call.placeScreenSharingCall(remoteVideoObj, localVideoObj);
        } catch (e) {
            // Something went wrong
            if (DEBUG) {
                console.log(e);
            }

            // Do something

            return false;
        }
```
