### ISSUE TITLE
Authentication with keypairs

### ISSUE THREAD

**Issue by uonuon** [matrix-org/matrix-js-sdk#1603]
**Authenticate with keypairs**
Hello, is it possible to authenticate with matrix with keypairs, such as secure keys that can be used to authenticate a client to an SSH server? Each key pair consists of a public key and a private key. The private key is retained by the client and should be kept absolutely secure

**Comment by SimonBrandner** [comment]
@uonuon, this isn't a question forum. Chat rooms like [Matrix HQ](https://matrix.to/#/#matrix:matrix.org?via=matrix.org&via=privacytools.io&via=mozilla.org) are better for questions.
