### ISSUE TITLE
Uncaught (in promise) TypeError: client.store.getSavedSyncToken is not a function

### ISSUE THREAD

**Issue by niwla23** [matrix-org/matrix-js-sdk#1608]
```js
    let opts = {
      localStorage: window.localStorage,
      indexedDB: window.indexedDB,
    }
    let store = new sdk.IndexedDBStore(opts)
    let cryptoStore = new sdk.IndexedDBCryptoStore(window.indexedDB, "cryptostuff")
    await store.startup() // load from indexed db
    await cryptoStore.startup()
    const client = sdk.createClient({
      store: cryptoStore,
      baseUrl: 'https://matrix.example.click',
    })
    client.startClient()
    client.publicRooms(function (err2, data2) {
      console.log('Public Rooms: %s', JSON.stringify(data2))
    })
```

I do login the client like this:
```js

      let opts = {
        localStorage: window.localStorage,
        indexedDB: window.indexedDB,
      }
      let store = new sdk.IndexedDBStore(opts)
      await store.startup() // load from indexed db
      const client = sdk.createClient({
        store: store,
        cryptoStore: store,
        baseUrl: 'https://matrix.example.click',
      })
      await client.startClient()

      try {
        var data = await client.loginWithPassword(this.mxid, this.password)
        this.loading = false
        console.log(data)
      } catch {
        console.log('error')
        this.loading = false
        this.loginError = true
      }
```

But when I reload the page, this error gets printed:
Uncaught (in promise) TypeError: client.store.getSavedSyncToken is not a function

**Comment by t3chguy** [comment]
So in your first snippet you do the right thing and instantiate a `store` and a `cryptoStore`.
In your second you pass a `store` as both a `store` and a `cryptoStore`

For just logging in you do not need a cryptoStore.

Heck you do not need a cryptoStore if you are not going to run `startCrypto`.

**Comment by niwla23** [comment]
So a crypto store is for e2e encryption?

**Comment by t3chguy** [comment]
Yes. crypto being short for cryptography

**Comment by niwla23** [comment]
```js
    let store = new sdk.IndexedDBStore({ indexedDB: window.indexedDB })
    await store.startup() // load from indexed db

    const client = sdk.createClient({
      store: store,
      baseUrl: 'https://matrix.cloudserver.click',
    })

    client.startClient()
```

So I have this now in the vue mounted function, but it makes unauthenticated calls:
![grafik](https://user-images.githubusercontent.com/46248939/108283797-3db7a780-7184-11eb-9d9e-7a251d115ffe.png)

**Comment by t3chguy** [comment]
The stores don't store your credentials, that is up to the application layer. 
You have to pass them in as baseUrl, userId, accessToken etc.

**Comment by niwla23** [comment]
so the concept is to let the user login with id and password, then store the accessToken (never expiring?) in localstorage or something and then login with that accessToken on Startup? And the store will contain the rooms and all that stuff?

**Comment by t3chguy** [comment]
Precisely

**Comment by niwla23** [comment]
thank you

**Comment by jryans** [comment]
Is there a bug to fix here? If so, what is it?

**Comment by jryans** [comment]
My impression from the linked issue is that the situation has been resolved. I recommend asking similar questions in rooms like #matrix-dev:matrix.org or similar.
