### ISSUE TITLE
DesktopCapturerSource is not properly exported

### ISSUE THREAD

**Issue by SimonBrandner** [matrix-org/matrix-js-sdk#1645]
**Describe the bug**
Creating a new TS project and running `tsc` results in:
```ts
node_modules/matrix-js-sdk/lib/webrtc/call.d.ts:122:68 - error TS2304: Cannot find name 'DesktopCapturerSource'.

122 export declare function getDesktopCapturerSources(): Promise<Array<DesktopCapturerSource>>;
                                                                              ~~~~~~~~~~~~~~~~~~~~~

node_modules/matrix-js-sdk/lib/webrtc/call.d.ts:202:146 - error TS2304: Cannot find name 'DesktopCapturerSource'.

202     placeScreenSharingCall(remoteVideoElement: HTMLVideoElement, localVideoElement: HTMLVideoElement, selectDesktopCapturerSource: () => Promise<DesktopCapturerSource>): Promise<void>;
                                                                                                                                                                   ~~~~~~~~~~~~~~~~~~~~
```

**To Reproduce**
+ `npm init`
+ `npm install typescript matrix-js-sdk node @types/node`
+ Create file `main.ts` with `import * as sdk from "matrix-js-sdk"`
+ `npx tsc main.ts`
+ See errors

**Additional context**
This seems to be caused by the fact that [`DesktopCapturerSource` isn't properly exported.](https://github.com/matrix-org/matrix-js-sdk/blob/0b7b35f80084f5c46ac7a20bb4539049654106f3/src/%40types/global.d.ts#L59). I don't know how it should be exported. Some of the declarations in `global.d.ts` depend on it so it can't be moved to `call.ts`. Adding the export keyword before the declaration doesn't solve the problem. It used to be that way and the problem was present

**Comment by enekonieto** [comment]
Same happens to me with 9.9.0

**Comment by enekonieto** [comment]
I got it working! Changes I did:

Added in `src/polyfills.ts` of my Angular app:
```
(window as any)['global'] = window;
```

Added in `node_modules/matrix-js-sdk/lib/webrtc/call.d.ts`:
```
interface DesktopCapturerSource {
    id: string;
    name: string;
    thumbnailURL: string;
}
```

**Comment by jryans** [comment]
React SDK seems to avoid hitting this because it explicitly imports JS SDK's global types:

```js
import "matrix-js-sdk/src/@types/global"
```

It seems strange to make every downstream package do that though...

**Comment by jryans** [comment]
If anyone knows recommended / suggested ways to resolve this in TS community, I am quite curious to hear, as the "right" fix is not clear to me.

**Comment by turt2live** [comment]
ran into this too in a project I'm working on :( 

The `import` trick doesn't seem to work properly in the project's build setup either (might be a correctable problem though). 

A possible "right" way is to avoid monolithic classes that end up importing most of the repo, though with our MatrixClient structure it is inevitable that we'll end up doing this without an `index.js` to guide us into the problem. We could look at breaking that down a bit, but this starts to get into long-term refactoring territory. 

... will try to see what can be done about it, I guess.
