### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token when initializing Matrix client on Vite

### ISSUE THREAD

**Issue by jrlmontejo** [matrix-org/matrix-js-sdk#1650]
**Describe the bug**
Initializing the Matrix client returns the following error when using Vite instead of webpack:

```
Uncaught SyntaxError: Invalid or unexpected token
```

The error is emitted from this part of the code:

```
// node_modules/unhomoglyph/data.json
var require_data = __commonJS((exports, module) => {
  module.exports = {
    "0": "O",
    "1": "l",
    "\u05AD": "\u0596",
    "\u05AE": "\u0598",
    "\u05A8": "\u0599",
    "\u05A4": "\u059A",
    "\u1AB4": "\u06DB",
    "\u20DB": "\u06DB",
    "\u0619": "\u0313",
    "\u08F3": "\u0313",
    "\u0343": "\u0313",
    "\u0315": "\u0313",
    "\u064F": "\u0313",
    "\u065D": "\u0314",
    "\u059C": "\u0301",
    "\u059D": "\u0301",
    "\u0618": "\u0301",
    "\u0747": "\u0301",
    "\u0341": "\u0301",
    "\u0954": "\u0301",
    "\u064E": "\u0301",
    "\u0340": "\u0300",
    "\u0953": "\u0300",
    "\u030C": "\u0306",
    "\uA67C": "\u0306",
    "\u0658": "\u0306",
    "\u065A": "\u0306",
    "\u036E": "\u0306",
    "\u06E8": "\u0306\u0307",
    "\u0310": "\u0306\u0307",
    "\u0901": "\u0306\u0307",
    "\u0981": "\u0306\u0307",
    "\u0A81": "\u0306\u0307",
    "\u0B01": "\u0306\u0307",
    "\u0C00": "\u0306\u0307",
    "\u0C81": "\u0306\u0307",
    "\u0D01": "\u0306\u0307",
    \u{114BF}: "\u0306\u0307",
   ...
```

**To Reproduce**
1. Create a project using Vite.
```
yarn create @vitejs/app sample-project --template vanilla
cd sample-project
```
2. Add `matrix-js-sdk`.
```
yarn add matrix-js-sdk
```
3. Initialize client.
```
import * as sdk from 'matrix-js-sdk'
const client = sdk.createClient('https://matrix.org')
```

**Expected behavior**
There should be no errors upon initializing the Matrix client.

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 
 - Browser: Chrome
 - Version: 89.0

**Comment by jryans** [comment]
Is Vite actually related here...? What's the actual bit of syntax that is bad?

**Comment by jrlmontejo** [comment]
> Is Vite actually related here...?

I'm not sure, but I tried using webpack with vue-cli instead of Vite, and it worked fine.

> What's the actual bit of syntax that is bad?

![image](https://user-images.githubusercontent.com/7676338/113077983-d0784700-9204-11eb-842e-156e3c2fd5aa.png)
The error is on line 400 in the screenshot.

**Comment by jryans** [comment]
Seems like an issue with [ES2015 Unicode escapes](https://babeljs.io/docs/en/babel-plugin-transform-unicode-escapes). These seems to widely supported in many tools these days, but perhaps not in some stage of Vite...?

In any case, I don't see anything actionable for JS SDK here.

**Comment by jryans** [comment]
(If I have misunderstood, please reopen the issue.)

**Comment by ozancakir** [comment]
I have the same problem. SDK not working with vite
