### ISSUE TITLE
sync-browserify.spec.js failing if `yarn build` isn't run

### ISSUE THREAD

**Issue by germain-gg** [matrix-org/matrix-js-sdk#1656]
**Describe the bug**

`sync-browserify.spec.js` requires a prior call to `yarn build` in order to pass

**To Reproduce**
1. Clone the repo
2. Run `yarn && yarn test`

**Expected behavior**

For all tests in `sync-browserify.spec.js` to pass

**Actual behavior**

The `sync-browserify.spec.js` file fails because it imports `../../dist/browser-matrix`. That file is generated after a run to `yarn build`

**Comment by jryans** [comment]
Hmm, yeah that's a tricky one... 🤔 In some ways, that test is checking for "is the browser build importable", so we'd at least need to build it... I wouldn't want to forcing building on every test run though... maybe documentation is the answer?

**Comment by t3chguy** [comment]
The browserify stuff is gone
