### ISSUE TITLE
Best way to sort Rooms for is_direct

### ISSUE THREAD

**Issue by KineticFox** [matrix-org/matrix-js-sdk#1659]
Im trying to figure out how to filter rooms in DM's and normal public Rooms. for DM's i use this create:
```js
client.createRoom({
  preset: "trusted_private_chat", 
  invite: [user], 
  is_direct: true,
})
````
But i cant figure out how to filter for this is_direct...

**Comment by SimonBrandner** [comment]
Hopefully, [this](https://spec.matrix.org/unstable/client-server-api/#direct-messaging) can help

**Comment by KineticFox** [comment]
fixed it:
```js
room.timeline.getContent().is_direct
```
- loop through ur room.timelin object
- at the m.room.member event the flag is_direct = true and the above code will print true
