### ISSUE TITLE
Login with Token returns HTTP Error 403 "Getting filter failed M_FORBIDDEN: Cannot create filters for other users"

### ISSUE THREAD

**Issue by YourPenguin** [matrix-org/matrix-js-sdk#1682]
So basically, I'm able to authorize myself with username and password on my company's matrix server using this:

```
const matrixClient = matrixSDK.createClient(this.matrixServer)
      await matrixClient.login('m.login.password', {
        'user': this.matrixUser,
        'password': this.matrixPassword,
      }).then((response) => {
        console.log(response.access_token)
        LocalStorage.set('matrixToken', response.access_token)
        return matrixClient
      })
```

It works out just fine and all my listeners and stuff works. I also successfully get the access_token.
But of course I don't want to generate a new instance in my devices on every single login, so I tried logging in with my fresh access_token like this:

```
const matrixClient = matrixSDK.createClient({
        baseUrl: this.matrixServer,
        accessToken: String(LocalStorage.getItem('matrixToken')),
        userId: '@user.name:matrix.my_company_server.me'
      })
```

So it recognizes the access_token as valid, but won't let me login. All i get then in my Chrome Console is the following:

`logger.js?07ed:57 Getting filter failed M_FORBIDDEN: Cannot create filters for other users`

This is weird because i proceed with the exact same Matrix user.
Do any of you guys have a clue what that means. Sorry if I don't misunderstand some basics here. I'm new to Matrix Client Development and I also did not setup the server here.
Thanks in advance!

**Desktop:**
 - OS: macOS
 - Browser Vivaldi (Chrome/90.0.4430.95)

**Comment by t3chguy** [comment]
You should be reading the login response's `response.user_id` and passing that when you create later clients.

The error is from the server, not from the client. Best to look at the actual web requests being made to pinpoint the issue.

**Comment by YourPenguin** [comment]
> You should be reading the login response's `response.user_id` and passing that when you create later clients.
> 
> The error is from the server, not from the client. Best to look at the actual web requests being made to pinpoint the issue.

damn that did the trick. Logged the `response.user_id`. I just had to remove the "matrix." subdomain so it's not "matrix.company_name.me"

Thanks a lot !!
