### ISSUE TITLE
Provide olm.js via CDN

### ISSUE THREAD

**Issue by iamleek1337** [matrix-org/matrix-js-sdk#1691]
Hello everyone :blush: If I want to use matrix-js-sdk in the browser, I can get `browser-matrix.min.js` from various CDNs https://www.jsdelivr.com/package/npm/matrix-js-sdk, for example. However, for e2e support, I need to include `olm.js` and I couldn't find any CDN providing it.

**Comment by uhoreg** [comment]
This issue belongs in the olm repository, so closing this issue in favour of https://github.com/matrix-org/olm/issues/55
