### ISSUE TITLE
[Error: End-to-end encryption not supported in this js-sdk build: did you remember to load the olm library?]

### ISSUE THREAD

**Issue by akhilumapathe** [matrix-org/matrix-js-sdk#1726]
Console Printed with
[Error: End-to-end encryption not supported in this js-sdk build: did you remember to load the olm library?]

when tried on React Native - V0.64

Development on Mac, OS -v11

Will this SDK support react native and with end to end encryption?
It works without e2e encryption.

**Comment by laurensiusadi** [comment]
Install olm by adding this in package.json
`"@matrix-org/olm": "https://gitlab.matrix.org/api/v4/projects/27/packages/npm/@matrix-org/olm/-/@matrix-org/olm-3.2.3.tgz",`

Then load olm together with matrix client
```
import Olm from "@matrix-org/olm/olm_legacy"; // using legacy if default wasm doesn't load
window.Olm = Olm;
```

E2E should be enabled.

**Comment by stalgiag** [comment]
The olm package tries to fetch `olm.wasm` from the same directory but this doesn't work when you are building with something like webpack as it isn't going to read calls to fetch. Right now I am doing a workaround by manually moving the `olm.wasm` file to the appropriate dist folder.

**Comment by richvdh** [comment]
The legacy crypto stack (which depended on libolm) is now deprecated, so this should no longer happen.
