### ISSUE TITLE
Room title blinks while you hover the mouse cursor over a few pixels at a rounded corner

### ISSUE THREAD

**Issue by bkil** [matrix-org/matrix-js-sdk#1756]
**Describe the bug**
$SUBJECT

**To Reproduce**
1. Open Element Web in a browser
2. Find the room list on the left
3. Hover your mouse precisely over any corner of a room name right where the highlight is rounded
4. Let go of the mouse to make it perfectly still
5. The highlight will blink with ~1Hz

**Comment by SimonBrandner** [comment]
https://user-images.githubusercontent.com/25768714/123302086-9de89c80-d51c-11eb-8c98-2154cd09acaa.mp4

This really does look interesting, especially since it nicely syncs with the caret blinking :smile: 

Though, should be filed at: https://github.com/vector-im/element-web

**Comment by t3chguy** [comment]
Good spot, please re-file. Cannot transfer cross-org

**Comment by bkil** [comment]
@SimonBrandner Thank you for the screenshot. I've now opened an issue over there: https://github.com/vector-im/element-web/issues/17760
