### ISSUE TITLE
Send encrypted message (encrypt the content)

### ISSUE THREAD

**Issue by mmeksasi** [matrix-org/matrix-js-sdk#1767]
I'm trying to send a message to an encrypted room but I don't know if the event should send it as encrypted if the room is encrypted the content is being sent as :

```javascript
{
body: "awd"
msgtype: "m.text"
}
```
but it should be sent as:
```javascript
{
algorithm: "m.megolm.v1.aes-sha2"
ciphertext: "AwgAEoABQOtcxhnyiDr9cxt30p/aJmRKo+X9t8Ci+RNEgL3M6LDQqTCCD7IQgN0ycaJ06kYS+UUOX/5egx5wF52ZZKwcmsLX0UnSj0V4bWMmnUJ4V6jGtwmMmSgzUhOxHZn7TJAxK8f+hc570nKFStrgjCECo3cVuJY9jef/HYmWmWCgadqVMs/ccfEzmHxeSgQr8b0W3VQFQnGzqkATgc3EKAudEGUUgwpoJNUA+DwcHNzHdliQD9YTor7TFzRGclcjYg0+fdGs9JiBQwo"
device_id: "AOYIRWXKAX"
sender_key: "wjdd/u7lzUge/eXvNuNCBKpef/BGJSYoX3kWyXL0hSo"
session_id: "1M/hp/iwSJHbxTN+4B4vyTtJ8n4Pyv6ucMypfurJkQo"
}
```

Maybe i need to use MegolmEncryption.encryptMessage but i didn't know how to use it if someone can help

```javascript
export const sendMessageChat = async ({
  message,
  roomID,
}) => {
  const content = {
    body: message,
    msgtype: 'm.text',
  };

  try {
    const result = await matrixAlias.sendEvent(
      roomID,
      'm.room.encrypted',
      content
    );
  } catch (err) {
    console.log('SEND MESSAGE ERROR ', err);
    alert('sending error');
  }
};
```

**Comment by t3chguy** [comment]
Please share your full minimal example. For encryption to work you will need awaited call to `initCrypto` and `startClient`, and await the first initial sync so that the client even knows that the room is encrypted. 

https://github.com/matrix-org/matrix-js-sdk#end-to-end-encryption-support

**Comment by mmeksasi** [comment]
From element when i send a message in an encrypted room the decryptEvent is working and the message is being recieved properly on simulator so encryption should be working but when i send it from simulator i get this error on element ** Unable to decrypt: Unknown encryption algorithm "undefined". ** because the content is :
{
body: "awd"
msgtype: "m.text"
}
not 
{
algorithm: "m.megolm.v1.aes-sha2"
ciphertext: "AwgAEoABQOtcxhnyiDr9cxt30p/aJmRKo+X9t8Ci+RNEgL3M6LDQqTCCD7IQgN0ycaJ06kYS+UUOX/5egx5wF52ZZKwcmsLX0UnSj0V4bWMmnUJ4V6jGtwmMmSgzUhOxHZn7TJAxK8f+hc570nKFStrgjCECo3cVuJY9jef/HYmWmWCgadqVMs/ccfEzmHxeSgQr8b0W3VQFQnGzqkATgc3EKAudEGUUgwpoJNUA+DwcHNzHdliQD9YTor7TFzRGclcjYg0+fdGs9JiBQwo"
device_id: "AOYIRWXKAX"
sender_key: "wjdd/u7lzUge/eXvNuNCBKpef/BGJSYoX3kWyXL0hSo"
session_id: "1M/hp/iwSJHbxTN+4B4vyTtJ8n4Pyv6ucMypfurJkQo"
}

I don't know if I should encrypt the message or it should be encrypted automatically when using 

const content = {
    body: message,
    msgtype: 'm.text',
  };

  try {
    const result = await matrixAlias.sendEvent(
      roomID,
      'm.room.encrypted',
      content
    );
  } catch (err) {
    console.log('SEND MESSAGE ERROR ', err);
    alert('sending error');
  }

P.S I'm using react native so I can't add global.Olm = require('olm'); but everything related to crypto is working also I'm using
 await matrixClient.initCrypto();
 await matrixClient.startClient();

**Comment by t3chguy** [comment]
> and await the first initial sync so that the client even knows that the room is encrypted.

**Comment by mmeksasi** [comment]
I'm awaiting everything, the send event if the type is m.room.encrypted it should encrypt the message content automatically or i should encrypt it before using it?

**Comment by t3chguy** [comment]
You should be using event type `m.room.message` - the js-sdk will wrap it inside an `m.room.encrypted` event's payload if it sees the room is encrypted at send time.

**Comment by t3chguy** [comment]
If you do not provide a *COMPLETE* functional yet minimal example you cannot be helped.

**Comment by mmeksasi** [comment]
const BASE_URL = 'http://localhost:8008';
export const MATRIX_CLIENT_START_OPTIONS = {
  initialSyncLimit: 10,
  request: request,
  lazyLoadMembers: true,
  pendingEventOrdering: 'detached',
  timelineSupport: true,
  unstableClientRelationAggregation: true,
  store: new MemoryStore({
    localStorage: AsyncStorage,
  }),
  cryptoStore: new AsyncCryptoStore(AsyncStorage),
  sessionStore: {
    getLocalTrustedBackupPubKey: () => null,
  }, // js-sdk complains if this isn't supplied but it's only used for remembering a local trusted backup key
};
export var matrixAlias = {};

export const LoginToChat = async ({ register = false, callBack }) => {
  try {
    const registrationClient = await matrixSdk.createClient(BASE_URL);
    if (username && chatPassword) {
      try {
        userRegisterResult = await registrationClient.login(
          'm.login.password',
          {
            user: username,
            password: chatPassword,
          }
        );
      } catch (e) {
        console.log('error login', e);
      }
    } else {
      return;
    }

    const matrixClient = await matrixSdk.createClient({
      baseUrl: BASE_URL,
      userId: userRegisterResult.user_id,
      accessToken: userRegisterResult.access_token,
      deviceId: userRegisterResult.device_id,
      ...MATRIX_CLIENT_START_OPTIONS,
    });
    await matrixClient.initCrypto();
    await matrixClient.startClient();
    matrixAlias = matrixClient;

    await matrixClient.uploadKeys();
    matrixClient.exportRoomKeys();
    getTimeline();
    callBack && callBack();
  } catch (e) {
    printError(e);
  }
};

export const sendMessageChat = async ({
  message,
  roomID
}) => {
  autoVerify(roomID);

  const content = {
    body: message,
    msgtype: 'm.text',
  };

  try {
    const result = await matrixAlias.sendEvent(
      roomID,
      'm.room.message',
      content
    );
  } catch (err) {
    console.log('SEND MESSAGE ERROR ', err);
    alert('sending error');
  }
};

export const getTimeline = () => {
  matrixAlias.on('Room.timeline', async (message, room, toStartOfTimeline) => {
    let body = '';
    let event;
 
    try {
      if (message.event.type === 'm.room.encrypted') {
        autoVerify(message.event.room_id);
 
        event = await matrixAlias._crypto.decryptEvent(message);
        ({ body } = event?.clearEvent?.content ?? '');
      } else {
        ({ body } = message.event.content);
      }
  
      if (body) {
        console.log(body
      }
    } catch (error) {
      console.error('RECEIVE MESSAGE ERROR ', error);
};

export const autoVerify = async (room_id) => {
  let room = matrixAlias.getRoom(room_id);
  const e2eMembers = await room.getEncryptionTargetMembers();
  for (const member of e2eMembers) {
    const devices = matrixAlias.getStoredDevicesForUser(member.userId);
    for (const device of devices) {
      if (device.isUnverified()) {
        await verifyDevice(member.userId, device.deviceId);
      }
    }
  }
};

export async function verifyDevice(userId, deviceId) {
  if (!userId || typeof userId !== 'string') {
    throw new Error('"userId" is required and must be a string.');
  }
  if (!deviceId || typeof deviceId !== 'string') {
    throw new Error('"deviceId" is required and must be a string.');
  }
  await matrixAlias.setDeviceKnown(userId, deviceId, true);
  await matrixAlias.setDeviceVerified(userId, deviceId, true);
}

**Comment by t3chguy** [comment]
I don't see you awaiting the initial sync in there

> and await the first initial sync so that the client even knows that the room is encrypted.

`sendMessageChat` is also never called so you are clearly not sharing a complete example.

**Comment by mmeksasi** [comment]
Check the example now please and really thank you for your time really,  if it's not sufficient tomorrow i will try to make a better example

**Comment by mmeksasi** [comment]
> I don't see you awaiting the initial sync in there
> 
> > and await the first initial sync so that the client even knows that the room is encrypted.
> 
> `sendMessageChat` is also never called so you are clearly not sharing a complete example.

**Comment by mmeksasi** [comment]
turned out if i send a message from another device the message in timeline will be encrypted but when i send the message from the same device and see it in the timeline the event content will not be encrypted

**Comment by t3chguy** [comment]
Ah, so yes `getContent()` will try get the decrypted content, you can use `getWireContent()` to see the actual content in the event

**Comment by ppulwey** [comment]
@mmeksasi Thanks for sharing the code. Helped me a lot! Now I can't find you loading of the Olm library. RN is complaining about this `error on init [Error: End-to-end encryption not supported in this js-sdk build: did you remember to load the olm library?]`

I've downloaded from [here](https://gitlab.matrix.org/matrix-org/olm/) and run a build. I use the legacy version as the version with webassebly seems not to run in RN.

How did you solved this?
