### ISSUE TITLE
Notification counter is not working correctly

### ISSUE THREAD

**Issue by felics96** [matrix-org/matrix-js-sdk#1768]
**Describe the bug**
The problem is very strange and I have no idea how I got it, but the meaning is this, I have one of the 2 users in the room stopped receiving notification counter (to be more precise, it does not change and is always 0) but everything is fine with the other user

**To Reproduce**
I can't say exactly but I can describe what I did
1. Create room and invite another user in room
2. Write messages from one to another and read it
3. After i close room and send another few messages from user and suddenly, for one moment, I stopped receiving Notification counter from one of the two users, and now I don't receive them at all. 

This may be related to the event of sending the event readability

**Expected behavior**
It should count notifications

**Screenshots**
![image](https://user-images.githubusercontent.com/49606688/124472457-d1da8200-dda6-11eb-8ae7-1dd68c20693b.png)
![image](https://user-images.githubusercontent.com/49606688/124472543-ed458d00-dda6-11eb-9987-9aae2da78feb.png)
![image](https://user-images.githubusercontent.com/49606688/124472590-fafb1280-dda6-11eb-8fb8-7e9b4c736f8d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Last
 
 Matrix-js-sdk version: 12.0.0
 Synapse version: 1.36.0

**Additional context**

**Comment by felics96** [comment]
Additionally, I realized that the problem may be related to the fact that requests are sent quickly using setRoomReadMarkers, most likely at one point I sent several requests and it broke something with this room

**Comment by turt2live** [comment]
A read *marker* (`m.fully_read`) is used to tell the user where they left off at while a read *receipt* (`m.receipt` / `m.read`) is used to clear notification counts. Read receipts should be sent when the user has reasonably "seen" the message, such as when it's shown on screen. A read marker should only be changed if it's within the user's scrollable area (meaning the gap between a read marker and read receipt can be large, indicating that the user might have missed a lot of the traffic).

**Comment by felics96** [comment]
I fixed this bug for myself, the problem was that several reading events were sent to the server at once, which led to some bug on the server for this room, I hope this will help you if you solve this problem.

**Comment by SimonBrandner** [comment]
@felics96 seems to have fixed the issue, so I am going to close this. Please comment with `@SimonBrandner` in case I am missing something
