### ISSUE TITLE
 Caught /sync error decryptCriticalEvents

### ISSUE THREAD

**Issue by harry-dev98** [matrix-org/matrix-js-sdk#1809]
I have created a wrapper over this project, which implements some business logic. And I am using the wrapper in react native. Now the problem m facing is when i am logging in using `client.loginWithPassword` i am able to log in, sync event is also a success but still I get some error which is as follows:

 ERROR  Caught /sync error decryptCriticalEvents@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aossiep2p&modulesOnly=false&runModule=true:185667:30
_callee5$@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aossiep2p&modulesOnly=false&runModule=true:185182:49
tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aossiep2p&modulesOnly=false&runModule=true:149487:23
invoke@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aossiep2p&modulesOnly=false&runModule=true:149660:32
tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aossiep2p&modulesOnly=false&runModule=true:149487:23
invoke@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aossiep2p&modulesOnly=false&runModule=true:149560:30
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aossiep2p&modulesOnly=false&runModule=true:149570:21
tryCallOne@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aossiep2p&modulesOnly=false&runModule=true:29437:16
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aossiep2p&modulesOnly=false&runModule=true:29538:27
_callTimer@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aossiep2p&modulesOnly=false&runModule=true:29954:17
_callImmediatesPass@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aossiep2p&modulesOnly=false&runModule=true:29993:17
callImmediates@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aossiep2p&modulesOnly=false&runModule=true:30211:33
__callImmediates@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aossiep2p&modulesOnly=false&runModule=true:6465:35
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aossiep2p&modulesOnly=false&runModule=true:6243:34
__guard@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aossiep2p&modulesOnly=false&runModule=true:6448:15
flushedQueue@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aossiep2p&modulesOnly=false&runModule=true:6242:21
flushedQueue@[native code]
callFunctionReturnFlushedQueue@[native code]

**Smartphone (please complete the following information):**
 - Device: [Redmi Note 8 Pro]
 - OS: [Android 10]

**Comment by ppulwey** [comment]
Had the same issue. Getting everything up and running in RN is tricky.

You can do the following:
`yarn add promise.allsettled`

In index.js
```
import allsettled from 'promise.allsettled';
allsettled.shim();
```

Should solve your issue.

**Comment by harry-dev98** [comment]
yes, that solved my issue.
Thanks alot.

**Comment by harry-dev98** [comment]
And i would like to under stand how that solves my issue, like what was happening and how allsettled.shim() solved the problem.

Can you also tell how to get rid of "Setting a timer for long period of time..." waring also.

**Comment by ppulwey** [comment]
Glad I could help.

If you dig deeper you will find that the matrix SDK uses Promise.allSettled in the sycing process. RN does not know about this relative new [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled) method.
The package you installed and initiated resolves this issue with a polyfill.

The "Setting timer for ..." message is android specific. You cannot get rid of it, just hide it. In my `index.js` I have
```
// ! Disable Matrix SDK related warnings / errors
LogBox.ignoreLogs(['WebRTC is not supported', 'Setting a timer']);
```
So these messages will not cover you UI anymore though they still exist.
