### ISSUE TITLE
Getting wrong event_id in the timeline when sending a new message

### ISSUE THREAD

**Issue by mmeksasi** [matrix-org/matrix-js-sdk#1811]
hello something is weird when i send a new message and handle it in the timeline I'm getting the wrong eventId: ~!hUfENltFGscjFnHxaj:kubernetesMaster.dtp.ae:m1627366797630.2
I'm getting it as the roomId+_txnId
when I refresh and get the chat from history it gets correct any idea?
<img width="301" alt="Screen Shot 2021-07-27 at 9 23 55 AM" src="https://user-images.githubusercontent.com/84375595/127116193-5e041766-648a-44c2-b1f7-cabbcbaff796.png">

**Comment by t3chguy** [comment]
That's the temporary id before the send api request is complete. It's the local echo.

**Comment by mmeksasi** [comment]
If the user want to delete this message how i can retrieve the original event_id so i can use it

**Comment by t3chguy** [comment]
You should subscribe to `Event.status` or `Event.localEventIdReplaced` after which the eventId will be updated to the one the server gives it.

**Comment by mmeksasi** [comment]
http://matrix-org.github.io/matrix-js-sdk/12.1.0/module-client.html#~event:MatrixClient%2522Room.localEchoUpdated%2522
