### ISSUE TITLE
setPowerLevel seems to clobber existing power levels

### ISSUE THREAD

**Issue by reivilibre** [matrix-org/matrix-js-sdk#1844]
`setPowerLevel` (https://github.com/matrix-org/matrix-js-sdk/blob/696b3ef1ce15a8c2c88006f6d058b3da5c4e3b32/src/client.ts#L3327-L3357) is described as setting a user's power level.

However, when using it, it seemed to discard the remaining power levels.

I notice now that it takes a slightly underdocumented event parameter. Is this meant to be the prior power level state event?

**Comment by t3chguy** [comment]
> Is this meant to be the prior power level state event?

Yup

**Comment by dhk2** [comment]
> Usage example https://github.com/matrix-org/matrix-react-sdk/blob/390b05617c78168aa91d128d0e3f6e9aeb89b7bf/src/SlashCommands.tsx#L783-L785

Thank you! that usage example was just what I needed.
