### ISSUE TITLE
getUrlPreview issue

### ISSUE THREAD

**Issue by MadonnaEssam** [matrix-org/matrix-js-sdk#1881]
I'm  using matrix-js-SDK version "2.4.6" and vue-js

I'm trying to send file in chat using this code

```
const uploadResponse =Client.uploadContent(file).then(function (data) {
                    const matrixUrl = data;
                    console.log(matrixUrl);

                  Client.getUrlPreview(matrixUrl, Date.now()).then((response) => {
                        Client.sendMessage(roomId, {
                            msgtype: "m.file",
                            body: response["og:title"],
                            url: matrixUrl,
                        });
                    })
```
every time I got 404 not found 
`https://xxxx/_matrix/media/r0/preview_url?url=mxc%3A%2F%2Fensofiaop.cv19.app%2FbqCPnnyMSXSdCDxYwZgHgwBa&ts=1630957741501&access_token=MDAyMGxvYxxxxxxxx `
404 (Not Found)
How can I fix it?

**Comment by t3chguy** [comment]
You'd need to check server logs and figure out why its returning a 404. Not a client issue.
