### ISSUE TITLE
How can i know that the user received the message sent!

### ISSUE THREAD

**Issue by mmeksasi** [matrix-org/matrix-js-sdk#1883]
I'm working on the double ticks when the user received the message, I tried to use the event m.receipt but it only work when the user read the message and not receive it, I need to know when the message is delivered.

**Comment by SimonBrandner** [comment]
You can't know if the message has been delivered to a specific user, afaik. You should be able to find out a message has been received by the server, though. I think the [#matrix-dev room](https://matrix.to/#/#matrix-dev:matrix.org) would be ideal for this conversation. 

I am going to close this as this isn't an issue
