### ISSUE TITLE
Ability to have a a logger per MatrixClient

### ISSUE THREAD

**Issue by clokep** [matrix-org/matrix-js-sdk#1899]
For a client that wishes to support multiple Matrix accounts it is useful to keep the logging separate for each account (for debugging purposes). Currently this is not possible since the matrix-js-sdk uses a single global logger.

I think a reasonable implementation of this would be for the `createClient` call to have a `logger` parameter, if not provided it falls back to a global logger.

I had briefly mentioned this as part of #1059, but that was closed. This would be particularly useful for Thunderbird (which does support multiple accounts).

A workaround for this could be to load the matrix-js-sdk multiple times into different scopes, but that feels icky.

This is filed with my community hat on. 🎩 

CC @freaktechnik

**Comment by clokep** [comment]
It looks like #1435 might need fixing too for full advantage of this.

**Comment by skylord123** [comment]
I would love for this to be added. I maintain node-red-contrib-matrix-chat that lets you build chat bots using simple functional block programming via Node-RED.

Currently it just logs to the console and is quite messy with multiple accounts. Most node-red log messages are prefixed with information about what node the message came from, but not having this feature makes me break that standard. This implementation would also allow me to turn debug messages on/off per matrix-client making my debugging much easier while running multiple clients.

**Comment by clokep** [comment]
I was poking at this the other day (with a community hat on) and would be curious to get validation on a plan of attack. I was thinking something along the lines of:

1. Add a `ClientOpt` named `logger` of a type (I think `PrefixedLogger`, but maybe something that doesn't depend on an external dependency).
2. Store this as a public, readonly property on `MatrixClient`, falling back to the current global `logger` if it doesn't exist on `ClientOpts`.
3. Start using it everywhere:
	1. Quite a few places have reference to `MatrixClient` so these are mostly a tedious `s/logger/this.client.logger/g`.
	2. A few other places don't have easy access to this:
		1. If the class/function is private, add a logger parameter/property and start using it.
		2. If the class/function is public, add a logger parameter/property, falling back to the global logger if not provided, and start using it.
4. There's also a few odd `debuglog(...)` functions which would need to be replaced somehow.

I think the above doesn't need to be all done in a single massive PR, I'd suggest:

1. Steps 1 & 2 and a few usages (maybe inside of `MatrixClient` itself) as an initial PR.
2. Then updating things on a module level (or whatever makes sense and keeps PRs a reasonable size).

----

Any thoughts on if this is a reasonable plan which maintains backwards compatibility?
