### ISSUE TITLE
What is this exactly?

### ISSUE THREAD

**Issue by damiantoczek** [matrix-org/matrix-js-sdk#1905]
Hello, sorry for creating a issue but discussions aren't  available here and I haven't seen any links here, Reddit, slack etc to ask it.

What is this "matrix" and SDK exactly?
Is this just a node that allows people to connect to the matrix nodes or is it for creating own matrix "blockchain"?
Is matrix a blockchain?
Is it possible to create accounts with this SDK or login only?

**Comment by SimonBrandner** [comment]
@damiantoczek, I would recommend reading some info on https://matrix.org/ and visiting the [Matrix HQ room](https://matrix.to/#/#matrix:matrix.org) and the [#matrix-dev room](https://matrix.to/#/#matrix-dev:matrix.org)

I am going to close this as this isn't an issue and the above-mentioned places should be sufficient to answer your questions

**Comment by damiantoczek** [comment]
Then maybe invest in a community and give them a platform to chat or ask question?

**Comment by MTRNord** [comment]
> 
> 
> Then maybe invest in a community and give them a platform to chat or ask question?

What do you mean? Matrix is a chat community and above is linked a Chat for it as well as the Website of the Project. What more is missing? Slack and similiar arent needed considering Matrix is already a chat. So there is no real point in having another chat used than the one of the project itself?

**Comment by SimonBrandner** [comment]
@damiantoczek, there is a place for the community to chat - the Matrix rooms I've linked :)

**Comment by damiantoczek** [comment]
Oh I was using matrix just with Element like private messaging didn't know you could talk to groups of people. Nice, I guess thanks then?

**Comment by MTRNord** [comment]
> 
> 
> Oh I was using matrix just with Element like private messaging didn't know you could talk to groups of people. Nice, I guess thanks then?

Yes Element is a Client for the Matrix Network :) As long as you know an address of a Room you usually can talk to anyone on the network including Groups :)
