### ISSUE TITLE
Call events for inbound calls only fire in the event the incoming call ended

### ISSUE THREAD

**Issue by menturion** [matrix-org/matrix-js-sdk#1912]
matrix-js-sdk:` v12.4.0` & `v12.5.0-rc.1`
synapse: `v12.4.0`

Hi,

I am adding call listeners for the receiving call party (= inbound call) immediately upon a new incoming call, like ...

```
cli.get().on('Call.incoming', (call) => {
   ...
   Call.setListeners(call);
   ...
});
```

`SetListeners` adds among others the following call listeners ...

```
call.on(CallEvent.State, (newState, oldState) => {
   ...
});

call.on(CallEvent.FeedsChanged, (feeds) => {
   ...
});
```

With the new updates (s. above) I am experiencing the issue that these listeners fire for inbound calls only in the event the incoming call ended, i.e. `oldState = 'ringing'` && `newState = 'ended'`. For outbound calls all events still fire as expected.

The result is that I am not able to process incoming calls anymore.

**Comment by SimonBrandner** [comment]
I think what you're experiencing here is a change we made to fix glare resolution. Right now we await the call init before emitting `Call.incoming`. You should manually run your event handlers on `Call.incoming` to make things work again

**Comment by menturion** [comment]
@SimonBrandner 

Thanks for your reply.
I am not sure whether I understand you correctly.

Currently, I set the listeners upon the `'Call.incoming'` event. This obviously seems to be too late, so that some events gets lost on the call receiver side.

When I try to set the listeners upon the 'Room.timeline' `'m.call.invite'` event the call ID is known, however, the call object has not been created yet and thus isn't set in the `callEventHandler.calls`. 

So both ways seems not to work. 

Is there any event that would work?

**Comment by SimonBrandner** [comment]
> Thanks for your reply.

No problem :)

> Currently, I set the listeners upon the `Call.incoming` event. This obviously seems to be too late, so that some events gets lost on the call receiver side.

It is too late but the fact that you miss some events isn't necessarily a problem if you init stuff correctly.

> When I try to set the listeners upon the `Room.timeline` `m.call.invite` event the call ID is known, however, the call object has not been created yet and thus isn't set in the callEventHandler.calls.

Yeah, that isn't the way to do it. We had a similar issue with emitting `Call.incoming` earlier and therefore it changed to await `MatrixCall::initWithInvite()`

You should be probably doing something like:

```ts
const onStateChanged = (newState: CallState, oldState?: CallState): void => {
	...
}

const onFeedsChanged = (feeds: Array<CallFeed>): void => {
	...
}

const setCallListeners = (call: MatrixCall): void => {
	call.addEventListener(CallEvent.FeedsChanged, onFeedsChanged);
	call.addEventListener(CallEvent.CallState, onStateChanged);
	...
}

client.addEventListner("Call.incoming", (call: MatrixCall) => {
	setCallListners(call);

	// Manually call handlers to init stuff
	onFeedsChanged(call.getFeeds());
	onStateChanged(call.state);
});
```

Does that make sense to you?

**Comment by menturion** [comment]
@SimonBrandner 

`client.addEventListener()` and `call.addEventListener()` result in `TypeError: ....addEventListener is not a function`. Only `client.on()` and `call.on()` work. 

The manual initialization calls the handlers once (-> `newState = 'ringing'`). Subsequent events (w/ the exception of the hangup event -> `oldState = 'ringing' && newState = 'ended'`) are not fired on the side of the call receiver, as originally reported here above.

I would be really happy if it worked, but it doesn`t. I have no clue how to overcome this breaking issue.

**Comment by menturion** [comment]
Addition:

For testing purposes, I have just rolled back to `matrix-js-sdk` to `v12.3.1` to exclude any side effects. This is the last version where calls still work.

**Comment by SimonBrandner** [comment]
Ah, could you perhaps share a bit more of your code so that we have a bit more to work with?

**Comment by SimonBrandner** [comment]
Also, sorry for the type, it was supposed to be `addListner()` but `on()` should work just fine

**Comment by menturion** [comment]
> Also, sorry for the typo, it was supposed to be `addListener()` but `on()` should work just fine

Yes, both work ` .on()` and `.addListener()`.

The reported issue could be fixed by replacing line 173 in the callEventHandler, see ...
https://github.com/matrix-org/matrix-js-sdk/blob/775e85a2e84e734d018cd0910a325dec9ba775c1/src/webrtc/callEventHandler.ts#L173 

by ...

`const initWithInvitePromise = call.initWithInvite(event);`

and adding ...

`await initWithInvitePromise;`

before line https://github.com/matrix-org/matrix-js-sdk/blob/775e85a2e84e734d018cd0910a325dec9ba775c1/src/webrtc/callEventHandler.ts#L214

With these changes all inbound call events are fired e.g. of the `onStateChanged` handler. 
I don't know what impact that would have on the rest of the code, but this part is causing this reported issue.

**Comment by SimonBrandner** [comment]
@menturion, things work just fine in Element... Could you please share some of your code, so that we could perhaps see what exactly is the issue?

**Comment by menturion** [comment]
@SimonBrandner 

Many thanks for your help!

In my last post I just wanted to point to the code that causes this changed behavior on my side.

Meanwhile I think that the changed behavior isn't an issue but the intended behavior (i.e. same as in Element).  This ...
```
	// Manually call handlers to init stuff
	onFeedsChanged(call.getFeeds());
	onStateChanged(call.state);
```
... did the trick to generate the missing initial event on the call receiver side. The other lost events do not appear to be relevant to the further proper processing of the incoming call.

In addition with some changes in the conditions within the state handler it seems to work now.

**Comment by SimonBrandner** [comment]
Great!
