### ISSUE TITLE
Use of deprecated setCodecPreferences prevents typescript upgrade

### ISSUE THREAD

**Issue by dbkr** [matrix-org/matrix-js-sdk#1921]
We use `RTCRtpTransceiver.setCodecPreferences` to disable RTX codecs on screen sharing to avoid chrome crashing: https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/webrtc/call.ts#L1502

MDN claims this is only supported by Safari though, and typescript have removed it (https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1029).

We should work out whether our supported chrome versions still crash here, or if they even expose this method, and if not, remove this workaround. If it is still needed, we'll have to add the method to the type in our types override.

**Comment by SimonBrandner** [comment]
/me will have a look. Would be great if we could remove that code...

**Comment by SimonBrandner** [comment]
Very much to my surprise, I seem to be no longer able to repro on `90.0.4430.212` :tada:

**Comment by SimonBrandner** [comment]
Argh, still seems to be an issue with Chrome 93 on Windows :sob: , the other tests were done on Linux.

**Comment by dbkr** [comment]
Does chrome 93 support `setCodecPreferences` though? Does the workaround still work?

**Comment by SimonBrandner** [comment]
> Does chrome 93 support `setCodecPreferences` though? Does the workaround still work?

Let's find out

**Comment by SimonBrandner** [comment]
The hack seems to work on Chrome 93

**Comment by SimonBrandner** [comment]
Continuation at https://github.com/matrix-org/matrix-js-sdk/issues/1926
