### ISSUE TITLE
Make our own base EventEmitter class to always handle Enum events instead of strings

### ISSUE THREAD

**Issue by Palid** [matrix-org/matrix-js-sdk#1931]
Wonder if we can do this with a generic base class or something, as this is kinda boilerplatey, e.g `EventEmitter<ThreadEvents>` etc

_Originally posted by @t3chguy in https://github.com/matrix-org/matrix-js-sdk/pull/1930#discussion_r710162015_

**Comment by t3chguy** [comment]
We have already done this, [TypedEventEmitter](https://github.com/matrix-org/matrix-js-sdk/blob/e492a44ddec89d4627c5a2cda646cb909d70796b/src/models/typed-event-emitter.ts#L44)
