### ISSUE TITLE
Build errors (e.g. TS2688: Cannot find type definition file for 'request') depending on the import source

### ISSUE THREAD

**Issue by menturion** [matrix-org/matrix-js-sdk#1976]
matrix-js-sdk: v14.0.1

TypeScript -> Imports from matrix-js-sdk

-1-
When I import something from the `/lib/` of `mxtris-js-sdk` , e.g. ...
`import {IndexedDBStore} from 'matrix-js-sdk/lib/store/indexeddb';`
within a TypeScript file I am getting the below build error:

```
node_modules/matrix-js-sdk/lib/client.d.ts:1:23 - error TS2688: Cannot find type definition file for 'request'.

1 /// <reference types="request" />
```

The build process is completed successfully when I remove the first line `/// <reference types="request" />` from the file `node_modules/matrix-js-sdk/lib/client.d.ts`. I guess that this line is added due to the package dependencies reference `"request": "^2.88.2"`.

-2- 
When I import something from the `/src/` of `mxtris-js-sdk` instead, e.g. ...
`import {IndexedDBStore} from 'matrix-js-sdk/src/store/indexeddb';`
I am getting a bunch of build errors, like (excerpt) ...

```
node_modules/matrix-js-sdk/src/client.ts:962:13 - error TS2322: Type 'Timeout' is not assignable to type 'number'.
962             this.checkTurnServersIntervalID = setInterval(() => {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/matrix-js-sdk/src/client.ts:988:13 - error TS2322: Type 'Timeout' is not assignable to type 'number'.
988             this.clientWellKnownIntervalID = setInterval(() => {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/matrix-js-sdk/src/crypto/aes.ts:23:44 - error TS2339: Property 'webkitSubtle' does not exist on type 'Crypto'.
23     (window.crypto.subtle || window.crypto.webkitSubtle) : null;
                                              ~~~~~~~~~~~~

node_modules/matrix-js-sdk/src/crypto/DeviceList.ts:200:13 - error TS2322: Type 'Timeout' is not assignable to type 'number'.
200             this.saveTimer = setTimeout(() => {
                ~~~~~~~~~~~~~~

node_modules/matrix-js-sdk/src/crypto/OutgoingRoomKeyRequestManager.ts:365:9 - error TS2322: Type 'Timeout' is not assignable to type 'number'.
365         this.sendOutgoingRoomKeyRequestsTimer = setTimeout(

...
```

... which could be fixed e.g. in case of the Timeout issue by replacing type `number` by `null | ReturnType<typeof setTimeout>`.

I am wondering why I am getting these issues. Do I have to change anything in my setup?

**Comment by menturion** [comment]
Solved by a different bundling setup.

**Comment by eiclu** [comment]
> Solved by a different bundling setup.

@menturion what was the issue? I have the same problem

**Comment by menturion** [comment]
@eiclu 

As far as I remember I had to setup a complete different build process, similar to the one of the `matrix-react-sdk` (https://github.com/matrix-org/matrix-react-sdk). 

With this change you can import from `/src` instead of `/lib`.

**Comment by menturion** [comment]
Addendum: 

Sorry, I meant `Element Web` https://github.com/vector-im/element-web, not the `matrix-react-sdk`, which is part of Element. See the relevant Webpack config here ...
https://github.com/vector-im/element-web/blob/develop/webpack.config.js

**Comment by t3chguy** [comment]
`request` was removed in v21 FTR
