### ISSUE TITLE
Handle spec CS version check correctly

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/matrix-js-sdk#1984]
**Describe the bug**
matrix-js-sdk does not seem to check for the spec version correctly

The spec says

> Only the latest Z value will be reported for each supported X.Y value. i.e. if the server implements r0.0.0, r0.0.1, and r1.2.0, it will report r0.0.1 and r1.2.0.

If you bump the version the server supports from r0.6.0 to r0.6.1, Element will think that the server doesn't support r0.6.0 because the version check is very simplistic.
https://github.com/matrix-org/matrix-js-sdk/blob/bbc547fd7f8c7a69e5045f50bbc87c22a9c225bf/src/client.ts#L5806-L5814
https://github.com/matrix-org/matrix-js-sdk/blob/bbc547fd7f8c7a69e5045f50bbc87c22a9c225bf/src/client.ts#L5827
https://github.com/matrix-org/matrix-js-sdk/blob/bbc547fd7f8c7a69e5045f50bbc87c22a9c225bf/src/client.ts#L5843

**To Reproduce**
1. Bump version supported by Synapse from r0.6.0 to r0.6.1
2. Call `client.isVersionSupported("r0.6.0");`

Result is false

**Expected behavior**
Should be true

**Additional context**
https://github.com/matrix-org/synapse/issues/11064

**Comment by turt2live** [comment]
Matrix 1.1 changes this behaviour, and the spec has always been inaccurate in practice on how versions are advertised. 

See https://github.com/vector-im/element-web/issues/16876 for more details.
