### ISSUE TITLE
Video call freezes on mobile

### ISSUE THREAD

**Issue by ipostu** [matrix-org/matrix-js-sdk#2052]
**Describe the bug**
Local Video stream on mobile freezes on first frame.

**To Reproduce**
In order to reproduce this bug I used 2 instances of VOIP example, one on mobile and one in a browser
1. Video call from instance1 -> Answer in instance 2-> wait 5 seconds -> close call from instance2
2. Call from instance2 -> Answer in instance1 -> wait 5 seconds -> close call from instance1
3. Repeat this steps 2-3 times and the local video from instance1(mobile) freezes on first frame

**Expected behavior**
The video should not freeze, but work correctly

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge 
 - Version  96.0.1054.34 

**Smartphone (please complete the following information):**
 - Device: Redmi Note 10 Pro
 - OS: Android 11
 - Browser: Chrome
 - Version 96.0.4664.45

**Additional context**
The last working version seems to be 12.4.1 all the newer versions don't seem to work

**Comment by richvdh** [comment]
Given this was filed 3 years ago, and much of the voip stack is being replaced, I think we can consider this outdated.
