### ISSUE TITLE
VOIP connection not established in demo code

### ISSUE THREAD

**Issue by appbasehamburg** [matrix-org/matrix-js-sdk#2083]
In the current version of the matrix-js-sdk the VOIP demo code can't establish a call between two room members.
(https://github.com/matrix-org/matrix-js-sdk/tree/develop/examples/voip)
The incoming call is recognized and even the call answering event is handled correctly, but the remote streams are not connected successfully.

1. Checkout the voip demo code: https://github.com/matrix-org/matrix-js-sdk/tree/develop/examples/voip
2. Setup two demo accounts on matrix.org
3. Connect them and chat on the same, unencrypted room
4. Add the credentials and the room-id to the demo code
5. Start a demo web server providing this code
6. Use two clients (different browsers, different clients on the same network..)
7. Open the web demo on both using the two different users
8. Call the other member using the provided buttons

**Expected behavior**
The call is displayed on the receiver side and even the answering works. Both clients are now in an active call state, but the streams are never connected.

Tested on an iPad using Firefox and Safari, on a Samsung Galaxy S21 Ultra using Chrome and Firefox, on a Macbook Pro 2020 using Safari, Chrome and Firefox

**Additional context**
We started downgrading the library step by step to see, if this issue came up recently.
Tested versions that **don't** work:

- 15.3.0
- 15.0.0
- 14.0.1
- 12.5.0
- 12.3.0
- 12.3.0-rc1
- 9.8.0

Tested version that **do** work:

- 11.0.0
- 12.0.0
- 12.2.0

The connection issue appeared in version 12.3.0-rc1. **Version 12.2.0** is the last (released) working version.

Edit: Tested versions added

**Comment by SimonBrandner** [comment]
Will investigate over Christmas

**Comment by SimonBrandner** [comment]
I can confirm the calls work between Element Web <-> demo code but no between demo code <-> demo code

**Comment by appbasehamburg** [comment]
I don't if the hint is helpful, but every client (Android Element / iOS Element / Element Web) <-> Demo Code works

**Comment by SimonBrandner** [comment]
Ha! This has an actually interesting cause - we use the `MatrixClient::deviceId` as `ourPartyId` but for the demo, it's not set, so it just sends `null` which breaks answering calls

**Comment by appbasehamburg** [comment]
I just tried to use the deviceId in your demo code. We adjusted the code to use the login method and username + password with demo accounts on matrix.org.

```
var client = matrixcs.createClient({
    baseUrl: BASE_URL,
    timelineSupport: true,
    deviceId: "web-demo",
})

const login = (userNo) => {
    client.login("m.login.password", getExternalMatrixTestLogin(userNo)).then((resp) => {
        if (resp.user_id) {
            console.log("Login succeeded - starting client")
            client.startClient()
        } else {
            console.log("Login failed", resp)
        }
    })
}
```


where `getExternalMetrixTextLogin(userNo) ` returns and `{ user: xxx, password: xxx } `

Using the deviceId as you mentioned doesn't fix the issue in our case.

**Comment by appbasehamburg** [comment]
Okay **it's working now**: The deviceId must not be the same for both clients. I just randomized it and now the streams connect and the call is working flawlessly.

**Comment by SimonBrandner** [comment]
> Okay **it's working now**: The deviceId must not be the same for both clients. I just randomized it and now the streams connect and the call is working flawlessly.

Yes, it must be different for all devices :)

**Comment by appbasehamburg** [comment]
Just to clarify: ALL devices in a group chat must have different ids? Isn't there a high possibility, that there are more devices using the same id (like "iPhone", "web", "Android"...) in the same room?

**Comment by SimonBrandner** [comment]
> Just to clarify: ALL devices in a group chat must have different ids? Isn't there a high possibility, that there are more devices using the same id (like "iPhone", "web", "Android"...) in the same room?

The spec says this: https://github.com/matrix-org/matrix-doc/blob/dbkr/msc2746/proposals/2746-reliable-voip.md#add-party_id-to-all-voip-events

**Comment by appbasehamburg** [comment]
@SimonBrandner The spec just says the partyId should be unique for call events, but is using the deviceId as the partyId implicitly a good idea?

**Comment by SimonBrandner** [comment]
> @SimonBrandner The spec just says the partyId should be unique for call events, but is using the deviceId as the partyId implicitly a good idea?

It says:

> A client implementation may choose to use the device ID used in end-to-end cryptography for this purpose, or it may choose, for example, to use a different one for each call to avoid lekaing information on which devices were used in a call (in an unencrypted room) or if a single device (ie. access token were used to send signalling for more than one call party.

So I believe it is

**Comment by jayeshhhh** [comment]
Hello @appbasehamburg 
I'm still facing the established Issue can you please help!
The error is: "Uncaught ReferenceError: matrixcs is not defined"

**Comment by SimonBrandner** [comment]
> Hello @appbasehamburg I'm still facing the established Issue can you please help! The error is: "Uncaught ReferenceError: matrixcs is not defined"

Sounds like a different issue, I would suggest visiting https://matrix.to/#/#matrix-dev:matrix.org, did you run `yarn build`?
