### ISSUE TITLE
Incorrect work with Vite bundler

### ISSUE THREAD

**Issue by ayndqy** [matrix-org/matrix-js-sdk#2087]
**Describe the bug**
A runtime error occurs when trying to import and create a matrix client.

**To Reproduce**
- Initialize Vite project (`$ npm init vite@latest; npm i`)
- Install matrix-js-sdk (`$ npm i matrix-js-sdk`)
- Import sdk in main.js and call `createClient` method
- Run Vite in dev mode (`$ vite`)

**Expected behavior**
Correct work with Vite bundler.

**Screenshots**
main.js:
<img width="593" alt="Screenshot 2021-12-22 at 16 03 24" src="https://user-images.githubusercontent.com/59361040/147104743-40b075bd-1cbe-4360-b1bb-06b0ed7b4714.png">

Runtime error:
<img width="532" alt="Screenshot 2021-12-22 at 15 52 53" src="https://user-images.githubusercontent.com/59361040/147103328-d4d484e1-bb1a-49b6-941c-a6ade3068eb3.png">

user.js in Chrome devtools:
<img width="668" alt="Screenshot 2021-12-22 at 15 55 44" src="https://user-images.githubusercontent.com/59361040/147103726-f9cf71a0-0700-4109-af79-5c8f10831923.png">

**Desktop**
 - OS: macOS 12.1 (21C52)
 - Browser: Chrome 96.0.4664.110

**Comment by Zettexe** [comment]
Is there a workaround or a fix for this? This issue makes me unable to use this package

**Comment by t3chguy** [comment]
You would need to polyfill `events` https://www.npmjs.com/package/events it is standard in Node and many other environments.
