### ISSUE TITLE
Missing 'lib' directory inside the examples directory

### ISSUE THREAD

**Issue by y0n1** [matrix-org/matrix-js-sdk#21]
After installing matrix-js-sdk with npm, the 'lib' directory is missing within the examples directory. As a result the examples didn't work.

**My workaround**: I've created  the mising 'lib' directory, placed there a symlink called matrix.js to ../../../dist/browser-matrix-dev.js

**Comment by Kegsay** [comment]
Thanks for this. Indeed the git repo has a symlink to that file https://github.com/matrix-org/matrix-js-sdk/tree/master/examples/browser/lib - I wouldn't be surprised if NPM is dropping symlinked files on upload. Will figure out a way to get the examples working without the need for symlinks.

**Comment by fred-wang** [comment]
@Kegsay An additional note here: when I tried #287 the example worked in Chrome but not in Firefox, probably because of https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy

**Comment by Kegsay** [comment]
Hmm, are you sure that's due to same-origin? I thought Chrome/FF had the same policy here. Which example did you try?

**Comment by fred-wang** [comment]
browser/lib/

**Comment by turt2live** [comment]
Looks like this is fixed.
