### ISSUE TITLE
Have js-sdk pass `strictNullChecks: true`

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix-js-sdk#2112]
When checking https://github.com/matrix-org/matrix-js-sdk/pull/1817, and then looking at https://github.com/matrix-org/matrix-js-sdk/issues/983, i decided to take it upon myself to add a little bit more null-safety to the library.

When i added `strictNullChecks` to the config, 1147 errors popped up, most of these cascading from other errors.

**Comment by turt2live** [comment]
Why is the flag important? What sorts of issues/benefit arise from [without] it?

**Comment by ShadowJonathan** [comment]
Short version;

```ts
function thing(): number {
  return null;
}
```

Without this flag, TS will not raise an error on this.

Long version;

Typescript does not do a bunch of checks by default, as I've noted in https://github.com/matrix-org/matrix-js-sdk/issues/2116, `strict` checks seem to be that they should be enabled by default, lest the codebase creating erratic, non-deterministic, and unchecked behaviour.

One such erroneous behaviour is breaking upholding type-safety, this is the basis of TS, and nullability is a large part of this.

In above example you can see what'd happen if this promise is not upheld, a callee could grab this "number", TS would recognise the return value as such, and while everything would look right while checking the program, at runtime, the program would crash or display weird behaviour (such as `null` coercing to `NaN` after some operations).

This rule is not enabled in js-sdk, and an example of the consequences could be https://github.com/matrix-org/matrix-js-sdk/issues/2035.

The alternative to checking nullability would be that this nulls are be unchecked, such behaviour would then break the basics of TS' type safety, creating a false sense of security, and leading to headaches, programmer bugs, runtime nullability problems (propagated undefined and errors on calling undefined as a function), and at worst, vulnerabilities.
