### ISSUE TITLE
Maybe enable `unified-signatures`

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix-js-sdk#2123]
https://typescript-eslint.io/rules/unified-signatures

This'll make sure that any two signatures of the same name is coalesced into one;

```ts
function x(x: number): void;
function x(x: string): void;
```

to

```ts
function x(x: number | string): void;
```

This could make functions easier to reason about, but it's up to style.

**Comment by ShadowJonathan** [comment]
This may not be desirable, I just had a thought that, as there are some backwards-compatible APIs in the SDK, these could then be defined "above" the new API, and marked as deprecated, while forcing type-checking to deal with both cases correctly.

**Comment by t3chguy** [comment]
> This may not be desirable, I just had a thought that, as there are some backwards-compatible APIs in the SDK, these could then be defined "above" the new API, and marked as deprecated, while forcing type-checking to deal with both cases correctly.

I'd presume TS would be smart enough to only merge the types if the param names match too, so for backwards-compatible overloads it shouldn't kick in

**Comment by ShadowJonathan** [comment]
It may not, as that deprecation functionality would not necessarily be part of the lint engine, and there's no mention of it in the docs.

**Comment by turt2live** [comment]
Can we get more information for what benefit this serves to the workflow?

**Comment by ShadowJonathan** [comment]
This issue was more or less a suggestion, though the longer i look at this, the more i'm unsure if it gives any concrete improvement.

My initial take was that this'd possibly reduce code boilerplate, but now i'm sure it does so at the expense of syntactical complexity and non-readability.

Besides, it would not help with some invariants that functions could/would have;

```ts
function thing(parseable: string): void;
function thing(buffer: ArrayBuffer, offset: number): void;
```

TS would error if this would ever be called with `("string", 1)`, or likewise with `(ArrayBuffer(), undefined)`, even those two would be valid under the function signature that TS would coerce this to for the callee;

`(a: string | ArrayBuffer, b?: number)`

The above would then also be enforced by this lint, while it would allow "contract-breaching" combinations to slip through.

So I think I'll close this, there's more merit to split out these signatures, and enforce more invariants.
