### ISSUE TITLE
`IContent` checking

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix-js-sdk#2125]
A lot of parts in the SDK treat `IContent` contextually as "any valid type", i.e. it'll treat it as if it has already been checked.

Some of these assumed bits are on public functions, so it is definitely not always correctly assumed if a programmer can call the function at any time.

For this, I suggest checking if it is safe to subtype `IContent` to a different Content type (such as `IEncryptedContent`), for this i recommend `ts-interface-checker`, which i used like the following to make a little checker for `IEncryptedContent`:

```ts
export interface IEncryptedContent extends IContent {
    algorithm: string;
    sender_key: string;
    ciphertext: Record<string, string>;
}
```

```ts
import { iface, indexKey, createCheckers, CheckerT } from "ts-interface-checker";

import { IEncryptedContent } from "./algorithms/megolm";

export const { IEncryptedContentTI } = createCheckers({
    IEncryptedContentTI: iface([], {
        "algorithm": "string",
        "sender_key": "string",
        "ciphertext": iface([], {
            [indexKey]: "string",
        }),
    }),
}) as { IEncryptedContentTI: CheckerT<IEncryptedContent> };
```

Calling `test` on `IEncryptedContentTI` (being `CheckerT<IEncryptedContent>`), and getting a positive branch, will make `TS` assume that whatever input it's given is now `IEncryptedContent`;

```ts
const wireContent: IContent = this.getWireContent();
if (!IEncryptedContentTI.test(wireContent)) {
    throw new Error("wire content is not an encrypted message");
}
// wireContent is now assumed IEncryptedContent
```

**Comment by ShadowJonathan** [comment]
This purpose seems partially filled by https://github.com/matrix-org/matrix-events-sdk, though it's not so certain if any and all events (i.e. state events and to_device) will also be handled by it.

**Comment by turt2live** [comment]
Much of this will be handled by the events-sdk, though is tracked in multiple other (external) places.

Closing in favour of internal issue tracking.
