### ISSUE TITLE
[process] How to introduce changes brought by `strict: true`

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix-js-sdk#2127]
This is more of a meta-issue, but I want to work on https://github.com/matrix-org/matrix-js-sdk/issues/2116, I can propose PRs against the main branch, but likely every change i'll make (as i'll be adjusting public function signatures to better match their returns and correct behaviour) would be considered a "breaking" one.

Thus, I thought it'd be better if I would merge all of these individual changes against a "parking" branch, and then have that parking branch be merged into the main one in one go (and one major version change), with the changes pre-approved.

Any feedback on how to best approach this?

**Comment by turt2live** [comment]
First we need to determine if it's a config change we even want, which is best discussed on the issue. Once we have more information about what the changes are then we can discuss how best to convert those to contributions.

I'm going to close this for now as it's essentially asking how to introduce a large change, but we don't know if we want that change.
