### ISSUE TITLE
Using modules in browser

### ISSUE THREAD

**Issue by doronnac** [matrix-org/matrix-js-sdk#2168]
**Is your feature request related to a problem? Please describe.**
Currently the official way of using matrix-js-sdk in the browser is linking the bundled version via a script tag.
This presents obvious issues such as lack of types, global pollution and of course downloading a relatively large 785 KB bundle even when requiring some functionality.
From what I see, this problem stems from the use of node specific api and then porting to browser at build time using browserify's polyfill, allowing for a browser friendly bundle.
There are ways to make the bundle work but this can be made unnecessarily hard depending on the environment (a huge selection of build tools + languages compiling to js).

**Describe the solution you'd like**
I think this issue can be solved more elegantly and easily via Inversion of Control (dependency injection) that will allow users of this library to inject the appropriate correct environment specific dependencies (fs, buffer, crypto etc). It will also easily allow the use of Olm via modules in any environment.
You may also then choose to wrap the library with your own implementations of node and browser.

**Describe alternatives you've considered**

**Additional context**
[Esbuild example](https://github.com/doronnac/matrix-esbuild-issue), part of my attempt to convert an existing working project from webpack to esbuild. This library made it unnecessarily hard, and I finally gave up after getting `global is not defined` error in runtime and not being able to fix it in a reasonable time.

**Comment by texuf** [comment]
I was trying to use the matrix js sdk in a project using vite and was getting hte same `global is not defined`. Adding this to my index.html fixed it for now, would be nice if the build system just worked

```
    <script>
      if (global === undefined) {
        var global = window;
      }
    </script>
```
