### ISSUE TITLE
How to refresh MemoryStore when logging in another account?

### ISSUE THREAD

**Issue by tunm1228** [matrix-org/matrix-js-sdk#2197]
EventTimelineSet.addLiveEvent: ignoring duplicate event ***
![image](https://user-images.githubusercontent.com/42457760/155478761-430bdcf4-b5de-4f0e-b860-080647ae6f5f.png)

**Comment by kishandaka** [comment]
find any solution ?

**Comment by bloor** [comment]
Isn't recreating the whole client instance working for you ?

Also there are these:
`
MatrixService.client?.store.deleteAllData()
MatrixService.client?.store.destroy()
`

**Comment by t3chguy** [comment]
This isn't a support forum, you can seek help at #matrix-dev:matrix.org
