### ISSUE TITLE
How to enable to end-to-end encryption in react-native using the matrix-js-sdk? 

### ISSUE THREAD

**Issue by AbdullahQureshi1080** [matrix-org/matrix-js-sdk#2205]
The sdk is working without encryption for react-native version v64.2 both on IOS and Android and a guide to making encryption work would be really awesome. The docs do not provide much support that could help with a minimal working example. Any help or support would be appreciated. 

The only issue thread that offer some insight or makes some understanding is [issue](https://github.com/matrix-org/matrix-js-sdk/issues/731)

**Comment by dimitri-bourreau** [comment]
@AbdullahQureshi1080 Hi! Have you figure out anything since your last post? Thanks!

**Comment by AbdullahQureshi1080** [comment]
@dimitri-bourreau Hey, how's it going? Have you been able to achieve this for two separate clients?

**Comment by dimitri-bourreau** [comment]
@AbdullahQureshi1080 Hi! We dropped the encryption feature for now (I'm no longer working for this client, so I do not follow this).

**Comment by AbdullahQureshi1080** [comment]
@dimitri-bourreau Okay that's understandable. Can you suggest some alternatives youve experimented with. That'd he helpful.

**Comment by greynewell** [comment]
I'm in the same boat. Nothing I've tried has worked for E2EE on react native, there's alwaus a missing Node or browser library at some point in the chain. Also had to drop the encryption feature.

**Comment by nitesh-habilelabs** [comment]
i am having issue with decryption and cross signing of device. is there any update ?

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix-js-sdk/pull/4503 updated the documentation, so this is hopefully better now.
