### ISSUE TITLE
Set room avatar  

### ISSUE THREAD

**Issue by HiteshKachhadiya** [matrix-org/matrix-js-sdk#2259]
**Set room avatar feature not working**
If we send event for "m.room.avatar" it changing room avatar even it's temporary changing. when refresh matrix data then it's not showing room image.

**Comment by t3chguy** [comment]
You're using the wrong method, its `sendStateEvent` not `sendEvent`

**Comment by HiteshKachhadiya** [comment]
> 

i am using this from sdk

/**
 * @param {string} roomId
 * @param {string} eventType
 * @param {Object} content
 * @param {string} txnId Optional.
 * @param {module:client.callback} callback Optional.
 * @return {Promise} Resolves: TODO
 * @return {module:http-api.MatrixError} Rejects: with an error response.
 */
MatrixClient.prototype.sendEvent = function(roomId, eventType, content, txnId,
                                            callback) {
    return this._sendCompleteEvent(roomId, {
        type: eventType,
        content: content,
    }, txnId, callback);
};

**Comment by HiteshKachhadiya** [comment]
i am using this for setName of room it's working fine.. same as we need to room avatar

/**
 * @param {string} roomId
 * @param {string} name
 * @param {module:client.callback} callback Optional.
 * @return {Promise} Resolves: TODO
 * @return {module:http-api.MatrixError} Rejects: with an error response.
 */
MatrixClient.prototype.setRoomName = function(roomId, name, callback) {
    return this.sendStateEvent(roomId, "m.room.name", {name: name},
                               undefined, callback);
};

**Comment by HiteshKachhadiya** [comment]
> You're using the wrong method, its `sendStateEvent` not `sendEvent`
> 
> ```
> sendStateEvent(roomId, "m.room.avatar", { url });
> ```

i am using this from sdk

/**

@param {string} roomId
@param {string} eventType
@param {Object} content
@param {string} txnId Optional.
@param {module:client.callback} callback Optional.
@return {Promise} Resolves: TODO
@return {module:http-api.MatrixError} Rejects: with an error response.
*/
MatrixClient.prototype.sendEvent = function(roomId, eventType, content, txnId,
callback) {
return this._sendCompleteEvent(roomId, {
type: eventType,
content: content,
}, txnId, callback);
};

**Comment by t3chguy** [comment]
`sendEvent` sends a timeline event, `m.room.avatar` is a State event, not a timeline event.

**Comment by MarinaFedy** [comment]
I've tried different methods, but only this one works:
sendStateEvent(roomId, "m.room.avatar", { url: matrixAvatarUri }
matrixAvatarUri  is the uri of the uploaded image to the server
