### ISSUE TITLE
Sub filtering of events

### ISSUE THREAD

**Issue by japhex** [matrix-org/matrix-js-sdk#2265]
**Is your feature request related to a problem? Please describe.**
We're using matrix on a comprehensive conversations solution and desperately want to be able to paginate results with nested filtering.

i.e. we absolute need this functionality:

- request events for a room that are NOT replies and paginate
- request replies for an event separately one a user interacts with that event

**Describe the solution you'd like**
filtering to be nested to include sub-level events as well, e.g. `not_types: ['m.in_reply_to']`

**Describe alternatives you've considered**
there aren't any.

**Comment by t3chguy** [comment]
Filtering is defined by the Matrix Spec, I would recommend opening an issue there.

**Comment by japhex** [comment]
Thank you - apologies if this isn't the right place, can you point me in the direction of the spec?

**Comment by japhex** [comment]
found it - thank you!

**Comment by t3chguy** [comment]
https://spec.matrix.org/latest/ - https://github.com/matrix-org/matrix-spec-proposals

**Comment by t3chguy** [comment]
> request replies for an event separately one a user interacts with that event

You can already do this using `MatrixClient::relations`

e.g `await client.relations(roomId, eventId, RelationType.Replace);`

**Comment by t3chguy** [comment]
> request replies for an event separately one a user interacts with that event

As for this, unfortunately replies pre-date relations so the /relations API does not work for them, another one to ask the Matrix spec for.
