### ISSUE TITLE
WebRTC is not supported in this environment

### ISSUE THREAD

**Issue by HalilFocic** [matrix-org/matrix-js-sdk#2328]
# Help needed

I am developing matrix in React Native and I am constantly getting error **WebRTC is not supported in this environment**

Real time messaging works fine on React Native but making/receiving calls doesn't.

Calling ```client.createCall``` returns null ( probably because it is not supported in that environment ).

Is there a way to make it work on React Native using ```matrix-js-sdk``` since there is not matrix library for react native yet.

**Comment by jpschw** [comment]
Bump!

**Comment by texuf** [comment]
I get this running my integration tests as well, we already have  a check around this error, maybe we can either make a global to disable, or downgrade the error to a warning? 
`call.ts`:
```
    if (!supported) {
            /* istanbul ignore if */ // Adds a lot of noise to test runs, so disable logging there.
            if (process.env.NODE_ENV !== "test") {
                logger.error("WebRTC is not supported in this browser / environment");
            }
            return false;
        }
```

**Comment by ajaykolekar9559** [comment]
Getting same error, any solution? @HalilFocic

**Comment by HalilFocic** [comment]
No,I swapped this library with Agora. Has better documentation and support

**Comment by msl2000** [comment]
Bringing this back to life. Anybody found a solution to this problem?

**Comment by greynewell** [comment]
I'm also having this issue while attempting to init crypto inside of a React Native app. I've tried everything I can think of, but don't even know why WebRTC would be required.
