### ISSUE TITLE
TypeError: this.opts.request is not a function when running client in Node.js; reopen issue #1191

### ISSUE THREAD

**Issue by jt0in3e** [matrix-org/matrix-js-sdk#2415]
I would like to reopen the issue #1191 since there is a similar error.
I've installed ```matrix-sdk-js``` using ```Node.js v16.15.0``` and initiated client as per example. Received ```TypeError: this.opts.request is not a function```. Also tried with nodejs v12, ```import``` or ```require``` of SDK, using ```async ... await``` function, but the same issue.
any ideas?

_Originally posted by @jt0in3e in https://github.com/matrix-org/matrix-js-sdk/issues/1191#issuecomment-1141020280_

**Comment by t3chguy** [comment]
@jt0in3e please provide an actual snippet and error

![image](https://user-images.githubusercontent.com/2403652/170980505-6e4f950d-712a-423e-9c9a-41241c0c4f16.png)

**Comment by jt0in3e** [comment]
@t3chguy 

OS - linux (VoidLinux, 5.15.41_1)
node.js -> v16.5.0
npm/v.8.5.5, yarn/v.1.22.18

steps to reproduce:
- mkdir "matrix-node-client" && cd
- yarn init 
- yarn add matrix-sdk-js
- touch index.js && vim index.js
   code snippet:
```
const sdk = require("matrix-js-sdk");

const client = sdk.createClient({
  baseUrl: "https://matrix.org",
  accessToken: "st_x.x.x.x.x.x.x.x.x.x.x",
  userId: "@yyyyyyyyyyyy:matrix.org"
});

client.startClient();
```
- node index.js

**ERROR** ->

```
Getting saved sync token...
Getting push rules...
Got saved sync token
Getting saved sync...
Getting push rules failed TypeError: this.opts.request is not a function
    at MatrixHttpApi.doRequest (/home/user/matrix-node-client/node_modules/matrix-js-sdk/lib/http-api.js:731:23)
    at MatrixHttpApi.requestOtherUrl (/home/user/matrix-node-client/node_modules/matrix-js-sdk/lib/http-api.js:610:17)
    at MatrixHttpApi.request (/home/user/matrix-node-client/node_modules/matrix-js-sdk/lib/http-api.js:566:17)
    at MatrixHttpApi.authedRequest (/home/user/matrix-node-client/node_modules/matrix-js-sdk/lib/http-api.js:515:33)
    at MatrixClient.getPushRules (/home/user/matrix-node-client/node_modules/matrix-js-sdk/lib/client.js:7099:22)
    at getPushRules (/home/user/matrix-node-client/node_modules/matrix-js-sdk/lib/sync.js:523:37)
    at SyncApi.sync (/home/user/matrix-node-client/node_modules/matrix-js-sdk/lib/sync.js:683:7)
    at MatrixClient.startClient (/home/user/matrix-node-client/node_modules/matrix-js-sdk/lib/client.js:470:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Waiting for saved sync before retrying push rules...
Got reply from saved sync, exists? false
```
- running without ```client.startClient()``` and with ```console.log(client.http.opts.request)``` gives no Errors and this response (cut):

```
{
  get: [Function (anonymous)],
  head: [Function (anonymous)],
  options: [Function (anonymous)],
  post: [Function (anonymous)],
  put: [Function (anonymous)],
  patch: [Function (anonymous)],
  del: [Function (anonymous)],
  delete: [Function (anonymous)],
  jar: [Function (anonymous)],
  cookie: [Function (anonymous)],
  defaults: [Function (anonymous)],
  forever: [Function (anonymous)],
  Request: [Function: Request] {
    debug: undefined,
    defaultProxyHeaderWhiteList: [
      'accept',           'accept-charset',
      'accept-encoding',  'accept-language',
      'accept-ranges',    'cache-control',
      'content-encoding', 'content-language',
      'content-location', 'content-md5',
      'content-range',    'content-type',
      'connection',       'date',
      'expect',           'max-forwards',
      'pragma',           'referer',
      'te',               'user-agent',
      'via'
    ],
    defaultProxyHeaderExclusiveList: [ 'proxy-authorization' ]
  },
  initParams: [Function: initParams],
  debug: [Getter/Setter],
  default: [Function: request] {
    get: [Function (anonymous)],
    head: [Function (anonymous)],
    options: [Function (anonymous)],
    post: [Function (anonymous)],
    put: [Function (anonymous)],
    patch: [Function (anonymous)],
    del: [Function (anonymous)],
    delete: [Function (anonymous)],
    jar: [Function (anonymous)],
    cookie: [Function (anonymous)],
    defaults: [Function (anonymous)],
    forever: [Function (anonymous)],
    Request: [Function: Request] {
      debug: undefined,
      defaultProxyHeaderWhiteList: [Array],
      defaultProxyHeaderExclusiveList: [Array]
    },
    initParams: [Function: initParams],
    debug: [Getter/Setter]
  }
}

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-js-sdk/issues/2415 fixes this

**Comment by jt0in3e** [comment]
> #2415 fixes this

@t3chguy nope, doesn't work. I've tried the fix with no success. the same problem (

**Comment by t3chguy** [comment]
@jt0in3e how are you testing it?

v18.0.0
![image](https://user-images.githubusercontent.com/2403652/171005481-42cc3a9d-dd70-4bd4-90aa-31989d1ffe0e.png)


https://github.com/matrix-org/matrix-js-sdk/pull/2414
![image](https://user-images.githubusercontent.com/2403652/171005535-a4dc94a9-6276-4a99-83d5-869de1541db0.png)

**Comment by reesericci** [comment]
I just ran into this same error

**Comment by reesericci** [comment]
```
import * as sdk from "matrix-js-sdk";

const client = sdk.createClient("https://matrix.org");

client.publicRooms(function(err, data) {
  console.log("Public Rooms: %s", JSON.stringify(data));
});


client.once('sync', function(state, prevState, res) {
    if(state === 'PREPARED') {
        console.log("prepared");
    } else {
        console.log(state);
        process.exit(1);
    }
});

await client.startClient({initialSyncLimit: 10});
```
Node.js v17.3.0

Logs:

```
Public Rooms: undefined
Getting saved sync token...
Getting push rules...
Got saved sync token
Getting saved sync...
Getting push rules failed TypeError: this.opts.request is not a function
    at MatrixHttpApi.doRequest (/var/home/reesericci/js/node/internet-fax-machine/node_modules/matrix-js-sdk/lib/http-api.js:731:23)
    at MatrixHttpApi.requestOtherUrl (/var/home/reesericci/js/node/internet-fax-machine/node_modules/matrix-js-sdk/lib/http-api.js:610:17)
    at MatrixHttpApi.request (/var/home/reesericci/js/node/internet-fax-machine/node_modules/matrix-js-sdk/lib/http-api.js:566:17)
    at MatrixHttpApi.authedRequest (/var/home/reesericci/js/node/internet-fax-machine/node_modules/matrix-js-sdk/lib/http-api.js:515:33)
    at MatrixClient.getPushRules (/var/home/reesericci/js/node/internet-fax-machine/node_modules/matrix-js-sdk/lib/client.js:7099:22)
    at getPushRules (/var/home/reesericci/js/node/internet-fax-machine/node_modules/matrix-js-sdk/lib/sync.js:523:37)
    at SyncApi.sync (/var/home/reesericci/js/node/internet-fax-machine/node_modules/matrix-js-sdk/lib/sync.js:683:7)
    at MatrixClient.startClient (/var/home/reesericci/js/node/internet-fax-machine/node_modules/matrix-js-sdk/lib/client.js:470:18)
    at async file:///var/home/reesericci/js/node/internet-fax-machine/index.js:19:1
Waiting for saved sync before retrying push rules...
Got reply from saved sync, exists? false
ERROR
```

**Comment by t3chguy** [comment]
`import * as sdk from "matrix-js-sdk";` How are you installing matrix-js-sdk from that PR here?

**Comment by reesericci** [comment]
I just did `npm i -S matrix-js-sdk`

**Comment by t3chguy** [comment]
@reesericci that'll be js-sdk v18.0.0 - not the changes in the PR.

**Comment by reesericci** [comment]
So then how do I install the fix? I'd like to continue using NPM if possible

**Comment by t3chguy** [comment]
Either wait for the next release or install it via a github dependency https://www.pluralsight.com/guides/install-npm-packages-from-gitgithub

**Comment by reesericci** [comment]
What's the timeline for the next release?

**Comment by t3chguy** [comment]
Next tuesday but the fix caused other issues downstream so has to be backed out. https://github.com/matrix-org/matrix-react-sdk/runs/6656911557?check_suite_focus=true

**Comment by reesericci** [comment]
I guess I'll wait for the release if the patch is causing issues.

Thanks!

**Comment by t3chguy** [comment]
You can workaround it using

```
const matrixcs = require("matrix-js-sdk/lib/matrix");
const request = require("request");
matrixcs.request(request);
```

**Comment by reesericci** [comment]
Will do - thanks for the workaround!

**Comment by jt0in3e** [comment]
@t3chguy I see you reverted back changes. I've tried workarond and it works. Do I need to keep this workarond persistent?

**Comment by t3chguy** [comment]
@jt0in3e see https://github.com/matrix-org/matrix-js-sdk/issues/2415#issuecomment-1141239882 for why the changes were reverted

**Comment by jt0in3e** [comment]
@t3chguy ok, will stay with workaround for now, maybe smth will change in the future. Thank you for your help

**Comment by reesericci** [comment]
Why is this issue closed? A workaround is not a fix, this issue should stay open until a real fix is merged and validated.

**Comment by jt0in3e** [comment]
> Why is this issue closed? A workaround is not a fix, this issue should stay open until a real fix is merged and validated.

accidentally clicked on "close with comment" o_0

**Comment by EgeKaanGurkan** [comment]
Has any fix to this issue been committed? I am getting the same error while trying to register a user.

**Comment by reesericci** [comment]
Is there any way to open a bounty on this issue? I'd be glad to throw some money your way if it meant that a fix would arrive,

**Comment by andreidiaconescu** [comment]
> #2415 fixes this

PR 2415 seems to not exist ?
is there a fix for this issue, or is the js SDK not usable at the moment ?

thank you,
Andrei

**Comment by MTRNord** [comment]
Getting this with a vitejs + preact + typescript setup as well when I try to login with password :/

**Comment by dcolley** [comment]
It was not clear whether you're in ts or js? 
Anyway, using the responses from this post I am able to get this working on node v16.15.0

**test.js**
```js
import * as sdk from 'matrix-js-sdk'
import matrixcs from 'matrix-js-sdk'
import request from 'request'
matrixcs.request(request)

console.log('starting...')

const client = sdk.createClient('https://matrix.org')
console.log('we have a client...')

client.login('m.login.password', {
    'user': '@metaspan:matrix.org',
    'password': '123456'
})
  .then((response) => {
      console.log(response)
      console.log(response.access_token)
  })
  .catch(err => {
      console.warn('caught an error!')
      console.error(err)
  })
  .finally(() => {
      console.log('we\'re done')
  })

console.debug('all done...')
```
**produces**
```console
node test.js
starting...
we have a client...
all done...
{
  user_id: '@metaspan:matrix.org',
  access_token: 'syt_asdfasdf_asdfasdf_3b2yjA',
  home_server: 'matrix.org',
  device_id: 'asdfJJasdf',
  well_known: { 'm.homeserver': { base_url: 'https://matrix-client.matrix.org/' } }
}
syt_asdfasdf_asdfasdf_3b2yjA
we're done
```

**Comment by reesericci** [comment]
I was using TypeScript + Rollup.js

**Comment by tearfulnumpty** [comment]
Is it possible there is another workaround that doesn't use the request package?  I understand that [work is being done to move from request to fetch](https://github.com/matrix-org/matrix-js-sdk/issues/801#issuecomment-1132597051) but I'm just not sure how long that will take, especially since the idea of moving away from request has been around since 2018.  

I don't mean to be impatient or ungrateful for the work put into projects like this, I'm just hoping to find a more immediate solution to the OP problem described here without relying on requests, if it's possible.

**Comment by t3chguy** [comment]
Given you can pass any method which fulfils the contract, you could write a `request` shim based on fetch, using async-await before calling the callback function.

**Comment by reesericci** [comment]
I can't use the SDK at the moment because of this - this needs to be top priority

**Comment by universalappfactory** [comment]
Hi, I had the same issue.

Setting ICreateClientOpts.request did the trick for me.

`
const request = require("request");

// ...

const client = sdk.createClient({
 baseUrl: 'https://matrix.org',
 request: request
})

// ...
`

**Comment by tearfulnumpty** [comment]
But you're still using the requests package, which doesn't really help the rest of things out.  This package has been deprecated for about 2 years already - this sdk really needs to move away from it altogether.

**Comment by universalappfactory** [comment]
Yes that's a good point.

But you can also use another library as workaround as long as https://github.com/matrix-org/matrix-js-sdk/issues/801 is ongoing I think.

@ghost stated an axios example there.

I'm still in an dev setup and tried a little modified version just as an example if anyone is interested in.

`const request = async function(opts, callback) {
    opts.url = opts.uri;  
    opts.data = opts.body;  
    
    if (opts.method === 'GET' && opts.useQuerystring) {      
      opts.params = opts.qs
    } else {      
      if (opts._matrix_opts.accessToken) {        
        opts.headers['Authorization'] = `Bearer ${opts._matrix_opts.accessToken}`
      }
    }
    
    const response = await axios.request(opts)
    callback(null, response, JSON.stringify(response.data));  
}`

**Comment by andreidiaconescu** [comment]
any update on this issue please ? 
this seems really blocking: usage of the JS SDK is blocked by this error .

**Comment by t3chguy** [comment]
@andreidiaconescu there is a workaround above by passing `request`.

**Comment by sushantdhiman** [comment]
Following works for me :- 

```ts
import * as sdk from "matrix-js-sdk";
import request from "request";

const matrixClient = sdk.createClient({
  baseUrl: "https://matrix.org",
  request,
});

const starting = matrixClient.startClient();

export async function notifications() {
  await starting;

  await matrixClient.sendMessage(<ROOM_ID>, {
    body: message,
    msgtype: "m.text",
  });
}
```

**Comment by Pythran331** [comment]
I suspect this might be of help to you



https://nodejser.space/questions/is-arraypush-not-functioning-properly
