### ISSUE TITLE
Error in console in sveltekit

### ISSUE THREAD

**Issue by ralyodio** [matrix-org/matrix-js-sdk#2438]
```
Uncaught (in promise) TypeError: super.off is not a function
    off typed-event-emitter.js:64
    MatrixClient client.js:228
    emitThree events.js:104
    emit events.js:177
    emit typed-event-emitter.js:48
    updateSyncState sync.js:1766
    doSync sync.js:866
typed-event-emitter.js:64:17
```

**Comment by t3chguy** [comment]
https://nodejs.org/api/events.html#emitteroffeventname-listener was added in v10.0.0
https://github.com/matrix-org/matrix-js-sdk#in-nodejs requires >=12.0.0

**Comment by ralyodio** [comment]
you saying node v12+? I'm on v18

**Comment by ralyodio** [comment]
...also this is browser not node.

**Comment by t3chguy** [comment]
https://www.npmjs.com/package/events matches `11.13.0` which also has `off` support and *should* be plenty
