### ISSUE TITLE
Reduce dep tree

### ISSUE THREAD

**Issue by kegsay** [matrix-org/matrix-js-sdk#244]
This problem seems to almost entirely be down to 'request' which is pulling in things like har-validator

https://matrix.org/jira/browse/SYJS-10

**Comment by Kegsay** [comment]
Short of using a different request library, there isn't much we can do about this.

**Comment by Kegsay** [comment]
Matthew says: This is a major problem for running on constrained devices like Tessels. I'd rather we didn't resolve valid bugs as won't-fix, especially when there's a solution ('using a different request library'). Will bump down the priority instead.

**Comment by fred-wang** [comment]
I think it would indeed be great to reduce dependencies! In https://bugzilla.mozilla.org/show_bug.cgi?id=1199855, I'm using browser-request for now. In addition, I see the following deps:
- browserify: events, punycode, querystring and url (I haven't tried to see if they can be replaced with native support)
- q (see #290 for native support)
- another-json (see #291 for native support)

**Comment by fred-wang** [comment]
cc'ing @clokep , this is about patch "Part 1 - Import Matrix JS SDK from github.com/matrix-org"

**Comment by t3chguy** [comment]
We killed all of the deps mentioned above except browserify which is leaving in October
