### ISSUE TITLE
Add an option to disable AGC (automatic gain control)

### ISSUE THREAD

**Issue by Skyliegirl33** [matrix-org/matrix-js-sdk#2451]
**Is your feature request related to a problem? Please describe.**
It's very annoying that there's no way to disable AGC. This is a default in Chromium, and it's up to each app to disable/add a toggle for it. Since Element relies on this SDK for calls, both projects need to add support for this. 

**Describe the solution you'd like**
When calling `getUserMedia()`, you can specify an audio object with constraints. `autoGainControl` being set to false should resolve it, but ideally this will be a function parameter or something similar.

**Describe alternatives you've considered**
There is no alternative, considering this is a Chromium limitation.

**Additional context**
It's a trivial change, so please don't just shove this issue off. This is a feature a *lot* of people would appreciate. If there's any help needed to implement it, I'll see what I can do.

**Comment by MrAnno** [comment]
Fixed by #2434.
