### ISSUE TITLE
If you rapidly send messages on react-sdk against a slow HS the local timeline can get out of order until you refresh

### ISSUE THREAD

**Issue by kegsay** [matrix-org/matrix-js-sdk#255]
https://matrix.org/jira/browse/SYJS-18

**Comment by MadLittleMods** [comment]
Closing in favor of these issues:

 - https://github.com/vector-im/element-web/issues/1173
 - https://github.com/vector-im/element-web/issues/3153
 - https://github.com/vector-im/element-web/issues/639
 - https://github.com/matrix-org/synapse/issues/14539
