### ISSUE TITLE
matrix-js-sdk uses unstable `/relations` endpoint (and its unspecced `original_event` field)

### ISSUE THREAD

**Issue by clokep** [matrix-org/matrix-js-sdk#2725]
The [`/relations` endpoint](https://spec.matrix.org/v1.4/client-server-api/#get_matrixclientv1roomsroomidrelationseventid) does not return an `original_event` field, yet the [matrix-js-sdk uses it](https://github.com/matrix-org/matrix-js-sdk/search?q=original_event&type=code).

We would like to remove support for this from Synapse in < 6 months. See matrix-org/synapse#12930 for more context.

**Comment by clokep** [comment]
According to @turt2live:

![image](https://user-images.githubusercontent.com/517124/193608392-5a051060-3641-4d64-a48c-85756a4d40b5.png)

> looks like web largely uses it in tests fwiw
> the code which actually uses it treats it as optional

----

Although it treats it as optional, it is unclear to me that it will do the *correct* thing if it is missing.

**Comment by t3chguy** [comment]
This will regress https://github.com/vector-im/element-web/issues/10200 or add an extra API call.

**Comment by clokep** [comment]
> This will regress [vector-im/element-web#10200](https://github.com/vector-im/element-web/issues/10200)

@richvdh @turt2live  Any thoughts on this? Are the solutions either:

* Take the extra API call.
* Write a separate MSC?

**Comment by richvdh** [comment]
sounds like an extra API call wouldn't be that bad?

**Comment by turt2live** [comment]
An extra API call is the least of that dialog's worries. If we put more effort into edits, we can always write an MSC. 

----

As an aside, is there a specific team we're expecting to action this? The js-sdk issue tracker tends to get, err, forgotten about.

**Comment by richvdh** [comment]
> As an aside, is there a specific team we're expecting to action this? The js-sdk issue tracker tends to get, err, forgotten about.

It feels like the EW platform team would be best placed to deal with it? I know EW isn't the *only* user of the js-sdk, but EW is by far the biggest driver for the js-sdk's development.

(And, frankly, it'll be EW who get bitten hardest when Synapse stops grandfathering this.)

**Comment by t3chguy** [comment]
The WAT is very unlikely to have bandwidth to do this in this quarter, the quarter plan is already somewhat assuming we get more bodies

**Comment by richvdh** [comment]
@justjanne has volunteered to take a look at switching this over to the stable endpoint.
