### ISSUE TITLE
a way to get a "sent receipt" for messages?

### ISSUE THREAD

**Issue by evakdev** [matrix-org/matrix-js-sdk#2737]
Hey. I was wondering if I can somehow get such receipt using the sdk. I'm using Element and it shows a "sent" badge next to messages sent to telegram, and I would like to get that in code somehow. I found a read receipt, but not a 'sent' one. Is that possible?

**Comment by SimonBrandner** [comment]
You can call `MatrixEvent::getAssociatedStatus()`

**Comment by t3chguy** [comment]
http://matrix-org.github.io/matrix-js-sdk/20.0.2/module-models_event.MatrixEvent.html `status` property
