### ISSUE TITLE
room.currentState does not always get updated with new state

### ISSUE THREAD

**Issue by freelock** [matrix-org/matrix-js-sdk#275]
Reported in #matrix-dev at https://matrix.to/#/!XqBunHwQIXUiqCaoxq:matrix.org/$14787151541517PqIir:matrix.freelock.com :

My bot calls matrixClient.startClient({initialSyncLimit: 1}) when it's started, and correctly sets the room.currentState on all the rooms it's a member of.

It listens to events on matrixClient.on("Room.timeline", ...), and reacts to some of them using matrixClient.sendStateEvent() to set new states, sometimes many in a row.

I have seen rate-limit errors, and have an error callback on the promise that waits for the specified timeout and then retries.

Then, at some later point, new messages trigger the bot again -- but when it attempts to check the state previously set in sendStateEvent(), using room.currentState.getStateEvents(), sometimes it returns the value previously set, and not the new value.

This is not consistent -- most of the time it's working just fine, but we do see some states where the bot shows the old value.

Restarting the bot results in it loading the state from the room in the /sync, and then it's showing the expected state -- this makes me think that the room state is getting set correctly, always, but the room.currentState is somehow caching the old value. Almost feels like a race condition.

Dave suggests checking for the state event coming through sync immediately after setting the state, to make sure that's all coming through -- I'll try to spend some time in the next week or two instrumenting this to find the problem.

**Comment by richvdh** [comment]
This is very odd. It would be great if you can figure out what is going on.

I *suspect* that the server is failing to send the correct state delta over /sync. My first port of call would be to log everything that arrives via /sync to confirm this.

**Comment by freelock** [comment]
I'll set something up to diagnose further, but just had a thought about a possible race condition here.

I am sending multiple setState events, with different keys, several in a row to the same room. I'm wondering if the issue might be something like:

[script] matrixClient.sendStateEvent(stateA);
[sdk] (caches currentState for this room after updating stateA)
[script] matrixClient.sendStateEvent(stateB);
[sdk] (discards previously cached currentState and caches oldstate + stateB)
[matrix] /sync event sends updated state for stateA and stateB, but stateA was already discarded
[sdk] updates cached stateB, but ignores stateA

I think it's some sort of race condition along these lines -- it at least matches what I'm currently seeing (not sure whether it's stateA or stateB that is discarded, or exactly when this happens, but it's something along these lines).

There's also the rate limit that I hit sometimes -- it does seem like the retries are successful, as the actual room state does end up correct, but this might also be a factor in something in the cached currentState getting out of sync (and could be why it's not easily observed).

I'll see if I can carve out some time to better instrument this and get to the bottom of it...

**Comment by freelock** [comment]
... I wonder if there's a closure in my retry code that is somehow overriding the room.currentState when it retries, while only sending the changed state event key to the room...

**Comment by richvdh** [comment]
`currentState` is only updated from the `/sync` response, not on `sendStateEvent`. So I don't think the race you suggest is possible.

**Comment by freelock** [comment]
ok. So I'm logging my custom event type using matrixClient.on('Room.timeline' ...) and seeing these events come through... so basically I'm looking for a state that I set that does not come back through the timeline?

**Comment by richvdh** [comment]
No, state does not always come back in the timeline.

You could listen on `event` instead; that should show everything, and 
yes you're looking for events that don't come back.

**Comment by freelock** [comment]
Ok, I'm seeing the same state events coming via both room.Timeline and event, so far...

... and I do see one instance (so far) where the state events came through in the wrong sequence...

First: 

```
event: { event: 
   { origin_server_ts: 1478808466519,
     sender: '@watney:matrix.freelock.com',
     event_id: '$14788084662466JNISW:matrix.freelock.com',
     unsigned: 
      { prev_content: [Object],
        prev_sender: '@watney:matrix.freelock.com',
        replaces_state: '$14788077432437hkBsx:matrix.freelock.com',
        age: 133 },
     state_key: 'state',
     content: { state: 'clean' },
     type: 'com.freelock.project',
     room_id: '!kcBWdBQItiUPIWZFrV:matrix.freelock.com' },
```

Next:
```
event: { event: 
   { origin_server_ts: 1478807743620,
     sender: '@watney:matrix.freelock.com',
     event_id: '$14788077432437hkBsx:matrix.freelock.com',
     unsigned: 
      { prev_content: [Object],
        prev_sender: '@watney:matrix.freelock.com',
        replaces_state: '$14787396252151fPNiA:matrix.freelock.com',
        age: 723114 },
     state_key: 'state',
     content: { state: 'released' },
     type: 'com.freelock.project',
     room_id: '!kcBWdBQItiUPIWZFrV:matrix.freelock.com' },
```

... I am seeing that the origin_server_ts is in the correct order, and the event.unsigned.replaces_state value is showing the correct order as well.

This state has already been further updated, so I can't confirm whether this state change was an affected one, but I'm certainly seeing that the change events are coming through the event listener in the wrong sequence. Would this lead to the previous state getting cached?

**Comment by richvdh** [comment]
Right, that's a bit odd. It does look like the server is sending the 
earlier state after the later one, for some reason.

I suspect we're going to have to get a capture of the sync requests and 
responses to make any progress on this. That would probably mean 
modifying `_sync` in `lib/sync.js` in the js-sdk. Of particular interest 
would be how the responses correlate to the syncToken. Would you be able 
to have a go at that?

**Comment by freelock** [comment]
Are the listeners called after a tick? Could a listener somehow block the internal state getting updated? If not, then I think it might be synapse returning the events out of sequence. But Synapse should be allowed to do that, right?

If the server can return events out of order, then maybe a quick fix is to use the origin_server_ts as a highwater, and discard state events with an older timestamp for that particular state key? Though that wouldn't solve an issue of the same state being changed based on the same "replaces_state" -- is there a spec for what should happen in this case? (it's not a case that would be relevant in my usage, but it seems appropriate to specify this).

I can certainly dig deeper, and I think I have a pretty reproduceable test case (though it runs at 3am, and takes a bit of setup). But I think the core issue here is whether the server can return states in any sequence, as long as the time stamps and replaces_state keys are "eventually consistent" (which as I understand Matrix, is the stated approach). And if that's true, then I think the issue is in the SDK, that it should observe those and make currentState always reflect the current state...

**Comment by richvdh** [comment]
> Are the listeners called after a tick? 

The `event` listeners? No, they are called inline: 

```
        stateEvents.forEach(function(e) { client.emit("event", e); });
        timelineEvents.forEach(function(e) { client.emit("event", e); });
        ephemeralEvents.forEach(function(e) { client.emit("event", e); });
        accountDataEvents.forEach(function(e) { client.emit("event", e); });
```

(see also https://nodejs.org/api/events.html#events_emitter_emit_eventname_args: "Synchronously calls each of the listeners...")

> Could a listener somehow block the internal state getting updated? 

Not really; it could block indefinitely, but then you'd see all sorts of other problems.

> If not, then I think it might be synapse returning the events out of sequence. But Synapse should be allowed to do that, right?

Not really. In the case of a state event B which replaces state event A according to the `replaces_state` field, synapse should never return event B before event A from `/sync`.

> If the server can return events out of order, then maybe a quick fix is to use the origin_server_ts as a highwater, and discard state events with an older timestamp for that particular state key?

That would be solving the problem in the wrong place; more problematically, it will break down when there is more than one server involved, with clocks which aren't quite synchronised.

> Though that wouldn't solve an issue of the same state being changed based on the same "replaces_state" -- is there a spec for what should happen in this case? (it's not a case that would be relevant in my usage, but it seems appropriate to specify this).

I'm not sure I understand the circumstances you describe here.

>  But I think the core issue here is whether the server can return states in any sequence, as long as the time stamps and replaces_state keys are "eventually consistent"

Nope, it's not for the client to unpick the ordering mess. The server is supposed to linearise the state. It gets complicated if different state is set on two homeservers at the same time, but even then the servers are supposed to resolve the conflict and send the clients the final state. It's possible there are some edge conditions in which Synapse doesn't get that process right, but in this situation (where there is only one server involved), I'm surprised to see it going wrong.

So yes, if you can repeat this and capture the sync responses from synapse, that would be very helpful :).

**Comment by freelock** [comment]
Hmm I wonder if this PR (landed on 0.18.4-rc1) fixes the issue? https://github.com/matrix-org/synapse/pull/1624

**Comment by richvdh** [comment]
> Hmm I wonder if this PR (landed on 0.18.4-rc1) fixes the issue?

That, AIUI, is about de-duplicating retries of events sent with transaction IDs (ie, message events, as opposed to state events). In any case if that were the problem then you would expect to see multiple events arriving with the replaces_state in the same order as you receive them.

**Comment by freelock** [comment]
Ok. I just noticed that it looks like the state is not coming down through /sync until there's an event in the room. So it looks to me like the sequence goes like this:

- set state 1
- set state 2
- send message
- receive message
- receive state 2
- receive state 1

(haven't instrumented to be sure, but definitely not getting anything to the "event" stream after using setState until something triggers the state to get sent, and if the same state has been set more than once, it does not come through in the right order).

**Comment by freelock** [comment]
Ok. I've dropped a console.log into lib/sync.js, line 712:

```
console.log(new Date(), syncToken, stateEvents, timelineEvents);
```

... this is in the _processSyncResponse.

Will add more detail when I next hit this -- we're seeing it happen a lot...

**Comment by freelock** [comment]
Ok, more data:

```
state set: !zNWluAfXafDgUWYyqk:matrix.freelock.com com.freelock.project { state: 'released' } state

Wed Nov 16 2016 17:30:42 GMT-0800 (PST) 's646424_7425681_2872_912069_696_21_1508' [] [ { event: 
     { origin_server_ts: 1479346241902,
       sender: '@watney:matrix.freelock.com',
       event_id: '$1479346241811jfXFH:matrix.freelock.com',
       unsigned: [Object],
       state_key: 'state',
       content: [Object],
       type: 'com.freelock.project',
       room_id: '!zNWluAfXafDgUWYyqk:matrix.freelock.com' },
    sender: null,
    target: null,
    status: null,
    forwardLooking: true,
    _clearEvent: {},
    _pushActions: null,
    _keysProved: {},
    _keysClaimed: {} } ]
timeline: { event: 
   { origin_server_ts: 1479346241902,
     sender: '@watney:matrix.freelock.com',
     event_id: '$1479346241811jfXFH:matrix.freelock.com',
     unsigned: 
      { prev_content: [Object],
        prev_sender: '@watney:matrix.freelock.com',
        replaces_state: '$14787247621699OchED:matrix.freelock.com',
        age: 177 },
     state_key: 'state',
     content: { state: 'released' },
     type: 'com.freelock.project',
     room_id: '!zNWluAfXafDgUWYyqk:matrix.freelock.com' },
  sender: 
   RoomMember {
     roomId: '!zNWluAfXafDgUWYyqk:matrix.freelock.com',
     userId: '@watney:matrix.freelock.com',
     typing: false,
     name: '@watney:matrix.freelock.com',
     powerLevel: 99,
     powerLevelNorm: 99,
     user: null,
     membership: 'join',
     events: { member: [Object] },
     _modified: 1479324226623 },
  target: null,
  status: null,
  forwardLooking: true,
  _clearEvent: {},
  _pushActions: null,
  _keysProved: {},
  _keysClaimed: {} }
event: { event: 
   { origin_server_ts: 1479346241902,
     sender: '@watney:matrix.freelock.com',
     event_id: '$1479346241811jfXFH:matrix.freelock.com',
     unsigned: 
      { prev_content: [Object],
        prev_sender: '@watney:matrix.freelock.com',
        replaces_state: '$14787247621699OchED:matrix.freelock.com',
        age: 177 },
     state_key: 'state',
     content: { state: 'released' },
     type: 'com.freelock.project',
     room_id: '!zNWluAfXafDgUWYyqk:matrix.freelock.com' },
  sender: 
   RoomMember {
     roomId: '!zNWluAfXafDgUWYyqk:matrix.freelock.com',
     userId: '@watney:matrix.freelock.com',
     typing: false,
     name: '@watney:matrix.freelock.com',
     powerLevel: 99,
     powerLevelNorm: 99,
     user: null,
     membership: 'join',
     events: { member: [Object] },
     _modified: 1479324226623 },
  target: null,
  status: null,
  forwardLooking: true,
  _clearEvent: {},
  _pushActions: null,
  _keysProved: {},
  _keysClaimed: {} }
Wed Nov 16 2016 17:30:42 GMT-0800 (PST) 's646425_7425681_2872_912069_696_21_1508' [ { event: 
     { origin_server_ts: 1478724762052,
       sender: '@watney:matrix.freelock.com',
       event_id: '$14787247621699OchED:matrix.freelock.com',
       unsigned: [Object],
       state_key: 'state',
       content: [Object],
       type: 'com.freelock.project',
       room_id: '!zNWluAfXafDgUWYyqk:matrix.freelock.com' },
    sender: null,
    target: null,
    status: null,
    forwardLooking: true,
    _clearEvent: {},
    _pushActions: null,
    _keysProved: {},
    _keysClaimed: {} } ] [ { event: 
     { origin_server_ts: 1479346241949,
       sender: '@watney:matrix.freelock.com',
       event_id: '$1479346241813Scmce:matrix.freelock.com',
       unsigned: [Object],
       content: [Object],
       type: 'm.room.message',
       room_id: '!zNWluAfXafDgUWYyqk:matrix.freelock.com' },
    sender: null,
    target: null,
    status: null,
    forwardLooking: true,
    _clearEvent: {},
    _pushActions: null,
    _keysProved: {},
    _keysClaimed: {} } ]
Already have event $1479346241813Scmce:matrix.freelock.com in limited sync - not resetting
event: { event: 
   { origin_server_ts: 1478724762052,
     sender: '@watney:matrix.freelock.com',
     event_id: '$14787247621699OchED:matrix.freelock.com',
     unsigned: 
      { age: 621480135,
        replaces_state: '$14787215861601GRoHl:matrix.freelock.com' },
     state_key: 'state',
     content: { state: 'stage' },
     type: 'com.freelock.project',
     room_id: '!zNWluAfXafDgUWYyqk:matrix.freelock.com' },
  sender: null,
  target: null,
  status: null,
  forwardLooking: true,
  _clearEvent: {},
  _pushActions: null,
  _keysProved: {},
  _keysClaimed: {} }
```

... so this is logging 4 different parts of the app/sdk: the timestamp shows the actual sync request, with the sync token, the "timeline: " is what my app logs coming through mxc.on('room.timeline'), "event:" is what it sees through mxc.on('event'), and there's also a log on('sync'), with state ERROR.

So it does look like Synapse is returning things out of order:

1. The bot sends a state event with key "state", value "released".
2. The state $1479346241811jfXFH:matrix.freelock.com comes through Sync with sync token s646424_7425681_2872_912069_696_21_1508, and is sent to the Room.timeline stream, and then the Event stream.
3. This state replaces state $14787247621699OchED:matrix.freelock.com which was never received previously, so the next sync retrieves that, and it comes back in sync token s646425_7425681_2872_912069_696_21_1508.
4. The sync system recognizes it has already been replaced and sends an error to the "sync" screen. It is suppressed from the Room.timeline stream, but it does send it to the event stream and updates the room.currentState object.

The original event was sent in the initial sync. So I'm not sure why it needed to get sent again... but it's obviously coming in through the sync a second time.

I have also seen cases that after sending a state event, I don't see a corresponding state event come in through the sync -- I think in these cases, there are multiple state events sent with different message types, it appears that one of the state events comes through, and the other doesn't appear to be in the stream.

**Comment by t3chguy** [comment]
This is a Synapse issue and not one of the js-sdk
