### ISSUE TITLE
[ISSUE] utils.ts?61cd:83 Uncaught (in promise) M_MISSING_PARAM: MatrixError: [400] 1 validation error for PutBody device_id field required

### ISSUE THREAD

**Issue by menturion** [matrix-org/matrix-js-sdk#2809]
synapse: v1.70.0
matrix-js-sdk:  v21.0.0

After I updated to `Synapse  v1.70.0` I get the below issue shown in the console: 

```
fetch.ts?12e2:62 PUT /_matrix/client/unstable/org.matrix.msc2697.v2/dehydrated_device 400 (Bad Request)
utils.ts?61cd:83 Uncaught (in promise) M_MISSING_PARAM: MatrixError: [400] 1 validation error for PutBody device_id field required (type=value_error.missing) (/_matrix/client/unstable/org.matrix.msc2697.v2/dehydrated_device)
    at parseErrorResponse (webpack-internal:///319:89:12)
    at MatrixHttpApi.requestOtherUrl (webpack-internal:///315:289:78)
```

... and the following error msg in `homeserver.log`: 

`2022-10-26 14:16:56,492 - synapse.http.server - 108 - INFO - PUT-625 - <SynapseRequest at 0x7fd1fef34100 method='PUT' uri='/_matrix/client/unstable/org.matrix.msc2697.v2/dehydrated_device' clientproto='HTTP/1.1' site='8448'> SynapseError: 400 - 1 validation error for PutBody device_id  field required (type=value_error.missing)`

**Comment by t3chguy** [comment]
This looks like a bug in Synapse, the MSC doesn't say anything about a request param of `device_id` for the PUT request.
https://github.com/uhoreg/matrix-doc/blob/dehydration/proposals/2697-device-dehydration.md#dehydrating-a-device

Tracked in https://github.com/matrix-org/synapse/issues/14334

**Comment by menturion** [comment]
Many thanks!
