### ISSUE TITLE
Cannot start threads from an event with a relation

### ISSUE THREAD

**Issue by abhilash-linkites** [matrix-org/matrix-js-sdk#2820]
I am trying to call sendEmoteMessage in the thread message so the user can react to thread messages using emojis. when I am creating a thread for a thread message I am getting an error "Cannot start threads from an event with a relation". how I can call the sendEmoteMessage function for thread messages?

![Screenshot 2022-10-28 at 12 17 15 PM](https://user-images.githubusercontent.com/98375367/198521852-4f76d643-22fa-4a14-8cf8-eee860da9e6c.png)

**Comment by t3chguy** [comment]
Please share the code you are trying. From the surface it looks like you're providing a value to `threadId` which is the ID of an event which is in the thread, whereas it must be the ID of the root event of the thread

**Comment by abhilash-linkites** [comment]
Hello,
Thank for your reply. If I will pass root event of ID it will react on root event or on the thread event? right now I am passing the thread id of the event in a thread. I want to react to the thread event. please check below code I am using.

Note: here data is thread event 

 var threadId = get(data, "threadId", "") || get(data, "thread.id", "");
    if (!threadId) {
      const thread = new Thread(get(data, "event.event_id", ""), data, {
        initialEvents: [data],
        room,
        client,
      });
      threadId = thread.id;
      thread.addEvents([data], false);
    }
    client.sendEmoteMessage(get(data, "event.room_id", ""), threadId, e);

**Comment by t3chguy** [comment]
Emote != React

Emote is a message of type `m.emote` - looks like:

<img width="283" alt="image" src="https://user-images.githubusercontent.com/2403652/199007379-94164dc3-44cc-4e4e-a7c6-116877e8392d.png">

So it is a message of its own right, which can be sent into a thread, but is not a reaction to a specific message.

**Comment by t3chguy** [comment]
To react, you'll want something like

```
client.sendEvent(roomId, EventType.Reaction, {
    "m.relates_to": {
        "rel_type": RelationType.Annotation,
        "event_id": eventId,
        "key": reaction,
    },
});

**Comment by abhilash-linkites** [comment]
Hii,
Thanks for the quick reply. I will try it and close this issue.
