### ISSUE TITLE
Broken `uploadContent` method

### ISSUE THREAD

**Issue by kfiven** [matrix-org/matrix-js-sdk#2824]
After v21, `uploadContent`'s `onlyContentUri: true` doesn't do anything.

**Comment by t3chguy** [comment]
`onlyContentUri` was removed, it is suggested you use Typescript which would have shown you this is no longer available. As per the breaking changes note in the changelog:

> Changes the uploadContent API

**Comment by kfiven** [comment]
Well, seems like you forgot to update JSDoc https://matrix-org.github.io/matrix-js-sdk/21.0.0/module-client.MatrixClient.html#uploadContent
