### ISSUE TITLE
Consider replacing another-json dependency with native JSON

### ISSUE THREAD

**Issue by fred-wang** [matrix-org/matrix-js-sdk#291]
It seems that the another-json dependency is only used in the matrix-js-sdk/lib/crypto/index.js file. Modern web engines have native support for JSON:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON#Browser_compatibility

I think it would be great to provide an option to use native JSON instead of native-json, similar to what is done for "request". That will allow to reduce a bit the dep tree, see #244

**Comment by fred-wang** [comment]
Interestingly, other core files in matrix-js-sdk/lib/crypto/ already uses native JSON support, so I'm not sure why it is different for matrix-js-sdk/lib/crypto/index.js

**Comment by fred-wang** [comment]
OK, I guess the rationale to use another-json is to have a "canonical form":
"Properties of non-array objects are not guaranteed to be stringified in any particular order. Do not rely on ordering of properties within the same object within the stringification."
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Description

**Comment by Kegsay** [comment]
Yup, this is exactly why we use `another-json`.
