### ISSUE TITLE
No documentation for viewing an event and paginate the timeline forward or backward from there

### ISSUE THREAD

**Issue by pau-ww** [matrix-org/matrix-js-sdk#2931]
Having trouble figuring out how to implement viewing an event. 
There's a `getEventTimeline` function for getting the event timeline for the event, but how do we set that this event timeline is the current event timeline of the room so that when using the `paginateEventTimeline` I can get the events before and after it?

**Comment by pau-ww** [comment]
When I used the event timeline returned by `getEventTimeline` as a parameter to `paginateEventTimeline`, the function returned false (no more event) when direction is forward but i haven't reached the latest events. Why did it returned false if there are more events expected?

**Comment by AbdullahQureshi1080** [comment]
@pau-ww Hey, how's it going? Do you want to achieve pagination for your chat use-case?

**Comment by wwdevops** [comment]
> @pau-ww Hey, how's it going? Do you want to achieve pagination for your chat use-case?

hi! yes, i would like to have pagination. Paginating backwards is working fine but i'm having trouble paginating forwards because the function returns false even if it didn't reach the latest events

**Comment by pau-ww** [comment]
> @pau-ww Hey, how's it going? Do you want to achieve pagination for your chat use-case?

hi! yes, i would like to have pagination. Paginating backwards is working fine but i'm having trouble paginating forwards because the function returns false even if it didn't reach the latest events

**Comment by AbdullahQureshi1080** [comment]
@pau-ww
 https://github.com/matrix-org/matrix-js-sdk/issues/3001

I also had trouble with pagination, a sort of working but not ideal solution I have given there it i basically updating the UI state manually but use the scrollback funtion to get the events. 

You can check it out, I hope this helps.

**Comment by pau-ww** [comment]
> @pau-ww #3001
> 
> I also had trouble with pagination, a sort of working but not ideal solution I have given there. It is basically updating the UI state manually but using the scrollback function to get the events.
> 
> You can check it out, I hope this helps.

i found a solution, and that is to get the neighboring timeline...

thank you for this anyways! :D

**Comment by AbdullahQureshi1080** [comment]
> 

Would be awesome, if you can share some snippets on how you made it work. Maybe I can update mine based on your solution, in a comparative way your solution can be better.
