### ISSUE TITLE
Matrix/Element denied notification permission

### ISSUE THREAD

**Issue by htouqeer938** [matrix-org/matrix-js-sdk#2932]
Hy Matrix denied notification permission. My browser's notification permission (Allow). I am using element.io in iframe.
I am also changing Notifier.ts.

window.Notification.requestPermission().then(
                        (permission) => {
                            if (permission === "granted") {
                                const notification = new Notification(
                                    "Hi there from Notify after permission!"
                                );
                                dis.dispatch({
                                    action: "notifier_enabled",
                                    value: true,
                                });
                            } else {
                                console.log("not_granted", permission);
                            }
                        }
                    );

But instead of asking me, he directly denies it۔ I am writing my custom code here۔
I am leaving a link to my site and a login here.
Please tell me any solution. It will be blessed

SiteLink: https://www.wejoinlife.com
Email: buytree@yopmail.com
Password: a123123BBB

Login and click on message button in right bottom cornor, and iframe will open.

either contact me in Email: htouqeer938@gmail.com

**Comment by t3chguy** [comment]
Browsers removed ability for apps inside iframes to request notification permissions

https://chromestatus.com/feature/6451284559265792

**Comment by htouqeer938** [comment]
> Browsers removed ability for apps inside iframes to request notification permissions
> 
> https://chromestatus.com/feature/6451284559265792

ok thanks It's mean issue in my Iframe :(
