### ISSUE TITLE
Cant use sdk

### ISSUE THREAD

**Issue by nadeocfg** [matrix-org/matrix-js-sdk#2956]
Hello! Can someone help me? I try to build a RN application and trying to connect via matrix-js-sdk.

```
Node version: v18.12.1
matrix-js-sdk: 22.0.0
```

```
const matrixClient = sdk.createClient({
  baseUrl: 'https://matrix.org/',
});

matrixClient
    .login('m.login.password', {
      type: 'm.login.password',
      password,
      identifier: {
        type: 'm.id.user',
        user,
      },
    })
    .then(response => {
      console.log(response.access_token)
    });
```

And i get error:
`{"errcode":"M_UNRECOGNIZED","error":"Unrecognized request"}`
It's same when i use different methods like: `publicRooms()`, `once()`

When i use axios for request and dont add `"/?"` in the end of url `"https://matrix.org/_matrix/client/r0/login"`, it's ok. But matrixClient from matrix-js-sdk add "/?" by himself
What i'm doing wrong?

**Comment by AbdullahQureshi1080** [comment]
@nadeocfg Have you found a fix? This is happening for every version after 20.0.0. 

Issue is present on v21, v22, v23 

Any update on this. 

@Yoric @jotto @bradtgmurray @brettz9

**Comment by nadeocfg** [comment]
> @nadeocfg Have you found a fix? This is happening for every version after 20.0.0.
> 
> Issue is present on v21, v22, v23
> 
> Any update on this.
> 
> @Yoric @jotto @bradtgmurray @brettz9

No, i dont found any fixes. So i just downgrade to 20.1.0. All i can found is old message on dev chat:
```
That is weird 😅 so I added fetchFn when creating client to get url before it's called, to replace those new, unnamed query params to make from
http://localhost:8008/_matrix/client/v3/room_keys/version?_=1668162216128 -> http://localhost:8008/_matrix/client/v3/room_keys/version
something like:
fetchFn(url, args) => { const uri = new URL(url); const searchParams = new URLSearchParams(uri); searchParams.delete('_'); return fetch(url, args) }

But then I realised I need to polyfill URL
Once I added import 'react-native-url-polyfill/auto';
All requests are passing :D no more M_UNRECOGNIZED maybe this will help someone trying to incorporate matrix to react-native, peace! ✌️
```
But it doesnt help me.

**Comment by AbdullahQureshi1080** [comment]
@nadeocfg I made it work on v23.1.1 using the

> > @nadeocfg Have you found a fix? This is happening for every version after 20.0.0.
> > Issue is present on v21, v22, v23
> > Any update on this.
> > @Yoric @jotto @bradtgmurray @brettz9
> 
> No, i dont found any fixes. So i just downgrade to 20.1.0. All i can found is old message on dev chat:
> 
> ```
> That is weird 😅 so I added fetchFn when creating client to get url before it's called, to replace those new, unnamed query params to make from
> http://localhost:8008/_matrix/client/v3/room_keys/version?_=1668162216128 -> http://localhost:8008/_matrix/client/v3/room_keys/version
> something like:
> fetchFn(url, args) => { const uri = new URL(url); const searchParams = new URLSearchParams(uri); searchParams.delete('_'); return fetch(url, args) }
> 
> But then I realised I need to polyfill URL
> Once I added import 'react-native-url-polyfill/auto';
> All requests are passing :D no more M_UNRECOGNIZED maybe this will help someone trying to incorporate matrix to react-native, peace! ✌️
> ```
> 
> But it doesnt help me.


@nadeocfg This is helpful. I think with this, errors resolves and it works. I tested on an unencrypted room, messages go through between our two clients. Thanks 🙌🏻

I made changes in my matrix service and my app source file. 

**Client Initialization** 

Try adding this callback fucntion to matrix clients fetchFn 

 ```
const client = sdk.createClient({
      baseUrl: this.host,
      accessToken: matrixCredentials.accessToken,
      userId: matrixCredentials.userId,
      deviceId: matrixCredentials.deviceId,
      ...MATRIX_CLIENT_START_OPTIONS,
      fetchFn: (url, args) => {
        const uri = new URL(url);
        const searchParams = new URLSearchParams(uri);
        searchParams.delete('_');
        return fetch(url, args);
      },
    });
      
```
**First install the polyfill package**

`npm  i  react-native-url-polyfill`

 The version I am using is 
 
 `react-native-url-polyfill": "^1.3.0`

**Index.js**

The polyfill import and the global initialization of fetch helped me. You can comment out other polyfills as I have they were being used when I did not think of the fetch issue. So a quick sim is that fetch is not present globally on node 16 and I was using that so I had to add polyfills to make things work but when I initialized fetch global I didn't need the other polyfills. 

```
import 'react-native-url-polyfill/auto';

// if (typeof BigInt === 'undefined') global.BigInt = require('big-integer');
// window.Buffer = window.Buffer || require('buffer').Buffer;
// polyfillGlobal('Buffer', () => require('buffer').Buffer);
// polyfillGlobal('SharedArrayBuffer', () => SharedArrayBuffer.prototype);
// polyfillGlobal('URL', () => require('whatwg-url').URL);
// SharedArrayBuffer = ArrayBuffer;

// try this also, maybe this helps you get things working. 
global.fetch = fetch;
```

I hope this helps you also. Let me know if it works. 

Also just a quick question, was the **dev chat** the matrix org chat room or something else, can you please share the link for that.

**Comment by nadeocfg** [comment]
> 

Looks interesting, i will try it on monday. Anyway thank you!

**Comment by richvdh** [comment]
sounds like this got resolved

**Comment by jpcastro4** [comment]
@AbdullahQureshi1080 working for me
