### ISSUE TITLE
registration of new user without multiple user verification

### ISSUE THREAD

**Issue by prashil-vaishnani** [matrix-org/matrix-js-sdk#2989]
Hi there , 
we are currently building web platform in which we use matrix-js-sdk for on of the chat app feature. our application start with the login/register page provided by the auth0. now we use this credentials for the matrix-chat login/registration. but when we try this then matrix-chat walk threw all the user verification step (m.login.recaptcha ,m.login.terms,"m.login.email.identity"). so this will make bad user experience as user have to do verification again for use the chat feature. 

**ASK:**
Is there any way to register new user without this verification step(m.login.recaptcha, m.login.terms, m.login.email.identity). specially for the email verification.

Thank You....

**Comment by t3chguy** [comment]
Yes, you disable the flows you do not wish for in your Matrix Server config, it is up to the server which flows are mandated.

**Comment by prashil-vaishnani** [comment]
Thanks For your kind help.
can you please share some code snippet so that we get more idea about it.
currently we are trying this for registering user 
> `
 let client = sdk.createClient("https://matrix.org"); 

    client.registerRequest({
      username: username,
      password: password,
      auth: {
        value:
          "reference definitions/auth_data.yaml not found in the OpenAPI spec",
      },
    });
    console.log(client);
  });
`

**Comment by t3chguy** [comment]
If you disable all required UIA flows on the server it won't need any `auth` in theory. Or maybe dummy - https://spec.matrix.org/v1.5/client-server-api/#dummy-auth - everything is documented in https://spec.matrix.org/v1.5/client-server-api/#user-interactive-authentication-api
