### ISSUE TITLE
Improve documentation credentials object

### ISSUE THREAD

**Issue by thijstriemstra** [matrix-org/matrix-js-sdk#3]
The readme should add a reference to https://localhost:8448/_matrix/client/#/settings where you can find `userId` and `accessToken`.

**Comment by thijstriemstra** [comment]
Hmm, that accessToken doesn't seem to be right. Creating a room with it throws this error:

```python
2015-04-20 17:55:57,538 - synapse.storage._base - 266 - ERROR - POST-138 - [TXN FAIL] {get_user_by_token-131}
Traceback (most recent call last):
  File "synapse/storage/_base.py", line 264, in inner_func
    return func(LoggingTransaction(txn, name), *args, **kwargs)
  File "synapse/storage/registration.py", line 141, in _query_for_auth
    raise StoreError(404, "Token not found.")
StoreError: 404: Token not found.
2015-04-20 17:55:57,578 - synapse.api.errors - 47 - INFO - POST-138 - AuthError: 403, Unrecognised access token.
```

**Comment by ara4n** [comment]
Agreed that the doc could be clearer here.

There are two ways of logging in - passing a credentials object to the sdk when you create a client:

  client = sdk.createClient({ url: "http://bar.com", user_id: "@foo:bar.com", access_token: "13489r29e8298r3...12398y19873" });

... or logging in with username and password:

        client = sdk.createClient("http://bar.com");
        client.loginWithPassword(userId, password, function(err, data) {
          if (err) {
            // do something
          }
          client.credentials.accessToken = data.access_token;
          client.credentials.userId = data.user_id;
        });

Note that currently you have to explicitly set the accessToken and userId on the client.credentials object based on the response from loginWithPassword.  This will be fixed in the next version

**Comment by thijstriemstra** [comment]
Thanks for the details. Before reading your reply I tried this:

```javascript
var url = 'https://localhost:8448';
var client = matrixcs.createClient(url);

// login
var credentials = {
    "type": "m.login.password",
    "user": "foo",
    "password": "pass"
};

client.login(credentials, function (err, data)
{
    if (data)
    {
        console.log('Logged in: %s', JSON.stringify(data));
    }

    if (err)
    {
        console.log('error: %s', JSON.stringify(err));
    }
});
```

but `loginWithPassword` worked.

**Comment by ara4n** [comment]
Right - looking at the code, client.login() takes 3 params: type, data 
and callback.  So you'll have wanted to do:

client.login("m.login.password", {
    "user": "foo",
    "password": "pass"
}, function (err, data) {...});

It's unfortunate that the JS API doesn't map literally to the HTTP API 
one here.  We're fixing up the doc currently to make it less cryptic :)

It may be easier to chat about problems like this in 
#matrix-dev:matrix.org btw :)
