### ISSUE TITLE
Errror building matrix-js-sdk, type declaration errors

### ISSUE THREAD

**Issue by selankon** [matrix-org/matrix-js-sdk#3027]
Using node `16.18.0` I added to my project the `matrix-js-sdk` as usual, using `npm i matrix-js-sdk`. 

When I run `npm run build` (that does `npx tsc --build`), it throws 314 errors when trying to compile the matrix-js-sdk node module. The errors are like this ones:

```
node_modules/matrix-js-sdk/src/models/event-timeline.ts:131:39 - error TS2345: Argument of type 'string | null' is not assignable to parameter of type 'string'.
  Type 'null' is not assignable to type 'string'.
node_modules/matrix-js-sdk/src/models/room-state.ts:840:29 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
  No index signature with a parameter of type 'string' was found on type '{}'.
node_modules/matrix-js-sdk/src/utils.ts:439:14 - error TS2322: Type 'undefined' is not assignable to type '(value: T | Promise<T>) => void'.
```

And much more errors. I don't know if is a Typescript miss configuration error or what. This is the only module that breaks.

This is my `tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "es2016",                                  /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */

    "module": "commonjs",                                /* Specify what module code is generated. */
    "outDir": "./dist",                                   /* Specify an output folder for all emitted files. */
    "esModuleInterop": true,                             /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables 'allowSyntheticDefaultImports' for type compatibility. */
    "forceConsistentCasingInFileNames": true,            /* Ensure that casing is correct in imports. */

    "strict": true,                                      /* Enable all strict type-checking options. */
    "skipLibCheck": true                                 /* Skip type checking all .d.ts files. */
  }
}
```

Thanks in advance

**Comment by Dainiu5** [comment]
Hi @selankon, were you able to find a fix or workaround for this issue?

**Comment by t3chguy** [comment]
This project now uses strict mode so such type errors should not be possible. The errors listed in the OP can no longer be reproduced, if you have new errors please open a new issue, we're keen to get them fixed.

**Comment by Dainiu5** [comment]
I have tried upgrading the matrix SDK and checked the errors, but they are still there. The main problem seems to be a mismatch between tsconfig which is used by Matrix JS SDK and our project. As an example, we do prevent any types. Currently, there is no easy solution to fix typescript build errors on our side unless we are missing something.

**Comment by t3chguy** [comment]
@Dainiu5 https://www.typescriptlang.org/tsconfig#skipLibCheck sounds like what you want

**Comment by mutantcornholio** [comment]
I'm also getting same problem. Can we reopen the issue please?

**Comment by t3chguy** [comment]
@Dainiu5 @mutantcornholio which tsconfig property are you using to prevent `any`?

**Comment by mutantcornholio** [comment]
Okay, I'm taking it back. In all those >360 errors, there were couple that were related to my code, not to `matrix-js-sdk`. 
And after fixing errors in my code, `tsc` stopped showing errors for `matrix-js-sdk`.
