### ISSUE TITLE
Video and Image upload results in incorrect data format

### ISSUE THREAD

**Issue by tearfulnumpty** [matrix-org/matrix-js-sdk#3032]
Hello, 

The developer of the Shinobi CCTV project is currently working towards integrating support for CCTV notifications for Matrix using this matrix-js-sdk.  Shinobi CCTV is a self hosted NVR type solution for security cameras (primarily IP cameras).  The idea for using Matrix and matrix-js-sdk is to upload notifications to users over Matrix.  For example, if an event (motion) is detected on a security camera by Shinobi, a short video clip, image, and text description can be uploaded to Matrix to alert the appropriate group.  Most of the work for the integration is complete, but presently there are some abnormalities with uploading video clips and images to a Matrix server.  

[Here's the relevant file that is being worked with, from the Shinobi Developer.](https://gitlab.com/Shinobi-Systems/Shinobi/-/blob/matrix-notifications/libs/notifications/matrix.js)

Text uploads seemingly work fine at the moment.  

Images and videos are unable to be read when uploaded through matrix-js-sdk to a Matrix server, and their raw data appears modified significantly.  Using an image upload as an example, the opening raw characters of the file should read as something resembling: `ÿØÿà` and continue as seemingly gibberish to human reading for the remainder of the file.  Instead, the image uploaded using the matrix-js-sdk opens with the following: `{"file":{"type":"Buffer","data":[255,216,255,224,0,16,74,70,73,` and continues with seemingly decimal versions of 8 bit numbers (0-255) comma separated.   In addition, the file closes with, `,"opts":{"name":"motion_cameraname_cameraname_ShinobiID_2023-01-05T16-19-43.jpg"}}`

The matrix-js-sdk uploaded files are also significantly larger than the expected files, somewhere around 3-4 times larger varying by the specific file.  

Shinobi generates some logs from the matrix-js-sdk usage when a notification is being sent.  In the following logs, 3 uploads should be occurring to Matrix.  The first should be a text message, the second, an image, and the third, a video.  I've removed/replaced sensitive information, if it's a problem please let me know (the `undefined` is not my doing):

```
0|camera  | sendEvent of type m.room.message in !roomID:URL with txnId mID1.0
0|camera  | sendEvent of type m.room.message in !roomID:URL with txnId mID2.1
0|camera  | setting pendingEvent status to queued in !roomID:URL event ID ~!roomID:URL:mID2.1 -> undefined
0|camera  | Event sent to !roomID:URL with event id $eventID1
0|camera  | setting pendingEvent status to sent in !roomID:URL event ID ~!roomID:URL:mID1.0 -> $eventID1
0|camera  | setting pendingEvent status to sending in !roomID:URL event ID ~!roomID:URL:mID2.1 -> undefined
0|camera  | Sync no longer running: exiting.
0|camera  | Got remote echo for event $eventID1 -> $eventID1 old status sent
0|camera  | Event sent to !roomID:URL with event id eventID2
0|camera  | setting pendingEvent status to sent in !roomID:URL event ID ~!roomID:URL:mID2.1 -> eventID2
0|camera  | Got remote echo for event eventID2 -> eventID2 old status sent
0|camera  | sendEvent of type m.room.message in !roomID:URL with txnId mID3.2
0|camera  | Event sent to !roomID:URL with event id eventID3
0|camera  | setting pendingEvent status to sent in !roomID:URL event ID ~!roomID:URL:mID3.2 -> eventID3
0|camera  | Got remote echo for event eventID3 -> eventID3 old status sent
```

___

Now I certainly don't claim to be an expert at this, but it appears to me that the data is being reformatted into some unknown format.  Is this a user error in some capacity?  Or is something wrong with the matrix-js-sdk?  [This documentation was used as reference for the above matrix.js implementation.](http://matrix-org.github.io/matrix-js-sdk/23.0.0/classes/MatrixClient.html#uploadContent)  

Both myself and the Shinobi developer would love to get Matrix support integrated into the Shinobi project.  I am personally not familiar with javascript, and programming in general was never my biggest strength.  I would greatly appreciate it if someone could take a look at the above file, and perhaps provide some assistance on where the error is originating.  I'll be happy to provide any additional information that I can, or help in any way I can.  

Thank you very much

**Comment by t3chguy** [comment]
`MatrixClient::uploadContent` takes a file and an optional opts object - http://matrix-org.github.io/matrix-js-sdk/23.0.0/classes/MatrixClient.html#uploadContent

https://gitlab.com/Shinobi-Systems/Shinobi/-/blob/matrix-notifications/libs/notifications/matrix.js#L19-24 passes an object

This invocation is incorrect. It should be changed to

```javascript
client.uploadContent(buffer, {
	name: name,
})
```
