### ISSUE TITLE
Adding the lint via https://github.com/matrix-org/eslint-plugin-matrix-org/pull/33

### ISSUE THREAD

**Issue by Morris05** [matrix-org/matrix-js-sdk#3041]
Adding the lint via https://github.com/matrix-org/eslint-plugin-matrix-org/pull/33

_Originally posted by @MadLittleMods in https://github.com/matrix-org/matrix-js-sdk/pull/2856#discussion_r1018442689_

**Comment by MadLittleMods** [comment]
Closing as this issue is very odd and probably spam.

Jest linting is being added to this repo via https://github.com/matrix-org/matrix-js-sdk/pull/2973
