### ISSUE TITLE
[Question] Is there a way to create admin users?

### ISSUE THREAD

**Issue by selankon** [matrix-org/matrix-js-sdk#3046]
Hi,

I'm following this tutorial to create admin users:

https://matrix-org.github.io/synapse/latest/admin_api/register_api.html

Is there any method exposed to register an admin user using the `/_synapse/admin/v1/register` endpoint? 

Thanks

**Comment by t3chguy** [comment]
matrix-js-sdk is a Matrix client, so doesn't really support Synapse-specific features like Admin API/Admin users, and the `/_synapse/` URL space
