### ISSUE TITLE
basic typescript sample breaks, update docs please

### ISSUE THREAD

**Issue by vladimir-sironja** [matrix-org/matrix-js-sdk#3124]
Hello!
someone should update the docs with at least a simple working example in typescript, because basic stuff like:

```
import * as sdk from "matrix-js-sdk";

const client = sdk.createClient({ baseUrl: "https://localhost" });
client.on("event", (event: any) => {});

```

breaks with

TypeScript error in ...
Argument of type '"event"' is not assignable to parameter of type 'EmittedEvents | EventEmitterEvents'.  TS2345

Instead, narrowed string types must be used (thx for riddles, how to decipher the semantics of"T extends string" !?) :

```
import { MatrixClient, RoomEvent, ClientEvent } from "matrix-js-sdk";
client.addListener(RoomEvent.Timeline, (event: any) => {});
client.on(ClientEvent.Event, (event: any) => {});
```

Bye

**Comment by abhijain2003** [comment]
can I work on this?

there is no much work I see right here, we just need to change * with extraction of required imports, 

thanks for providing solutions
