### ISSUE TITLE
Error uploading device keys

### ISSUE THREAD

**Issue by viral32111** [matrix-org/matrix-js-sdk#3128]
Hey, I'm trying to get E2E encryption working on a Node.js client, but I'm running into an issue.

I get the following error on startup shortly after `.startClient()` is called _(`HOME_SERVER_URL` is the URL to my Dendrite instance)_:

```
Error uploading device keys Unknown error code: MatrixError: [400] Unknown message (https://HOME_SERVER_URL/_matrix/client/r0/keys/upload)
    at parseErrorResponse (.\node_modules\matrix-js-sdk\lib\http-api\utils.js:81:12)
    at MatrixHttpApi.requestOtherUrl (.\node_modules\matrix-js-sdk\lib\http-api\fetch.js:246:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  httpStatus: 400,
  url: 'https://HOME_SERVER_URL/_matrix/client/r0/keys/upload',
  event: undefined,
  errcode: undefined,
  data: { '@user:HOME_SERVER_URL': { kcVlbUdR: [Object] } }
}
```

The following error also appears in Dendrite's logs:

```
time="2023-02-05T22:43:59.277784182Z" level=error msg="Failed to upload one or more keys" key_errors="map[@user:HOME_SERVER_URL:map[kcVlbUdR:user_id or device_id mismatch: users: @user:HOME_SERVER_URL - @user:HOME_SERVER_URL, devices: matrix-bot - kcVlbUdR]]" req.id=bo7Ygw0bmkEA req.method=POST req.path=/_matrix/client/r0/keys/upload user_id="@user:HOME_SERVER_URL"
```

My environment:
 * Node.js: 18.11.0
 * NPM: 9.1.3
 * matrix-js-sdk: 23.1.1
 * @matrix-org/olm: 3.2.14

Code: https://github.com/viral32111/matrix-bot/tree/0de566c8c597e2b8f759db99a36282e57471db0a/source

I'm not sure if this is an issue with the SDK, how I'm using it, or because I'm using a Dendrite homeserver? There doesn't seem to be much documentation around setting up E2E encryption on Node.js...

**Comment by t3chguy** [comment]
https://github.com/viral32111/matrix-bot/blob/0de566c8c597e2b8f759db99a36282e57471db0a/source/main.ts#L38

The `deviceId` is a value you get from the server during login/registration rather than a value you just make up

**Comment by viral32111** [comment]
Oh I assumed `deviceId` was the human-readable name of the device/session (e.g., the name you see when you go to session management in Element).

I'll try this out later, thank you!

**Comment by t3chguy** [comment]
No, that'd be `initial_device_display_name` during /registration and there are APIs to update it later on (/devices)

https://spec.matrix.org/latest/#devices

https://spec.matrix.org/v1.5/client-server-api/#post_matrixclientv3register `device_id`

**Comment by viral32111** [comment]
Am I right to assume that API can be called via [`MatrixClient.setDeviceDetails()`](https://matrix-org.github.io/matrix-js-sdk/23.1.1/classes/MatrixClient.html#setDeviceDetails) in this SDK?

**Comment by viral32111** [comment]
This worked, thanks!
