### ISSUE TITLE
Updating to latest matrix-js-sdk 23.2.0 type loader issues webpack

### ISSUE THREAD

**Issue by 0xM4m4n** [matrix-org/matrix-js-sdk#3135]
Hey team it seems I am running into a loader issue for the latest matrix release when building my applicaiton
![image](https://user-images.githubusercontent.com/107433287/217343481-b2867ec0-6799-4c81-a192-b7609c05916c.png)

I believe it is related to [this change](https://github.com/matrix-org/matrix-js-sdk/pull/3051) but not sure what loader Ill need in my webpack config to compile the sdk properly. 

here's a piece from webpack:
```
plugins: [
      new TsconfigPathsPlugin({
        baseUrl: __dirname,
        configFile: "./tsconfig.json",
        extensions: [".js", ".ts", ".tsx"],
      }),
    ]
  },
  node: {
    global: true,
  },
  module: {
    rules: [
      {
        test: /\.(js|mjs|jsx|ts|tsx)$/,
        exclude: /(node_modules|bower_components)/,
        use: [{
            loader: "babel-loader",
            options: {
              presets: [
                '@babel/preset-env',
                '@babel/preset-react',
                "@babel/preset-typescript",
              ],
            },

          },
        "ts-loader"]
      },
      {
        enforce: 'pre',
        test: /\.js$/,
        loader: 'source-map-loader'
      },
      {
        test: /\.html$/,
        use: ['html-loader'],
      },
      {
        test: /\.(png|jpe?g|gif|otf|ttf|woff|woff2|ogg)$/,
        type: 'asset/resource',
      },
      {
        test: /\.svg$/,
        type: 'asset/inline',
      },
      {
        test: /\.m?js/,
        resolve: {
          fullySpecified: false
        }
      }
    ],
  },
  ```
  
  Any ideas would be appreciated! I am looking to move to vite soon but for now just trying to incorporate some of these latest changes which I think will help with stability

**Comment by andybalaam** [comment]
Should be fixed by https://github.com/matrix-org/matrix-js-sdk/pull/3150 (which is backported into 1.11.23, being released today)

**Comment by andybalaam** [comment]
We think this is fixed - please let us know if you continue to see problems.

**Comment by andybalaam** [comment]
Also, I update the description - please correct me if I'm wrong :-)

**Comment by 0xM4m4n** [comment]
Thank you very much!
