### ISSUE TITLE
Please redact passwords from debug output

### ISSUE THREAD

**Issue by AndrewJDR** [matrix-org/matrix-js-sdk#315]
When using functions such as loginWithPassword(), the debug output from sync.js ends up printing the password in plaintext on stdout. It looks like this:
```
POST https://matrix.org/_matrix/client/r0/login (AS) Body: {"user":"@exampleuser:matrix.org","password":"my password is right here in plaintext","type":"m.login.password"}
```
It would be preferable if the password were redacted from the output, which is how access tokens work. That looks more like this:
```PUT /transactions/480?access_token=<REDACTED>```

So the desired output for passwords would be:
```
POST https://matrix.org/_matrix/client/r0/login (AS) Body: {"user":"@exampleuser:matrix.org","password":"<REDACTED>","type":"m.login.password"}
```

**Comment by pbruna** [comment]
I think it's better to print the password from a developer point of view.
This info it's only visible to the person who is running the JS, no one else. And if you are debugging, it's safe to assume that you know what you are doing.

**Comment by AndrewJDR** [comment]
would you advocate for printing the access tokens as well then (currently they are redacted)?

**Comment by pbruna** [comment]
I don't think it would hurt either. But only for debugging purposes.
I think its safe to assume that anyone using this library in debugging mode, knows what its doing.

**Comment by AndrewJDR** [comment]
Ok. I respectfully disagree for the following reasons:
It's common to transmit logs to other developers across unsecure channels. Going through and manually redacting the passwords is an annoying extra step to actually take. At times, debug logs are actually being gathered by end-users who may not be super familiar with search/replace tools (sed, decent text editors, etc).

Additionally, it's common to store logs on a hard drive/ssd of some sort (for later debugging), and it's just a better security practice not to have tokens/passwords laying around on drive sectors in in plaintext.

**Comment by richvdh** [comment]
> When using functions such as loginWithPassword(), the debug output from sync.js ends up printing the password in plaintext on stdout. It looks like this:
> `POST https://matrix.org/_matrix/client/r0/login` ...

I've never seen logging like that. I don't think it would come from sync.js. Where are you seeing this? why do you think it comes from sync.js?

**Comment by AndrewJDR** [comment]
@richvdh Hmm, If it wasn't 4 months later I might have an answer, but I really don't know anymore :/

**Comment by AndrewJDR** [comment]
@richvdh Aha, looks like it's a matrix-appservice-node thing:
https://github.com/matrix-org/matrix-appservice-bridge/blob/master/lib/components/client-factory.js#L50

So I filed this under the project project, oopsie.
