### ISSUE TITLE
`createRoom` which has federation off?

### ISSUE THREAD

**Issue by woifes** [matrix-org/matrix-js-sdk#3164]
First let me thank you for your greate work! I want to create an Chatbot which offers sending notifications to specific alerting channels (rooms). The users on my homeserver shall freely join or leave the room depending when they want to receive the alert messages (e. g. leave during your vaction).
My software should create missing rooms automatically depending on the configuration. But since the alerts can have sensitive information in it the rooms shall not be federated.
This kind of rooms can be created for example via element but is it also possible via the sdk? The usecase is compareable to [this](https://github.com/matrix-org/synapse/issues/7568)

**Comment by t3chguy** [comment]
```
client.createRoom({
    creation_content: {
        "m.federate": false,
    },
});
```

This is described in spec.matrix.org
