### ISSUE TITLE
Client Prefix is set to V3 and we have no way to change it

### ISSUE THREAD

**Issue by larsonnn** [matrix-org/matrix-js-sdk#3188]
Instead of ClientPrefix.Unstable, since version 21, ClientPrefix.V3 is set as the version prefix to go. 

Example: https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/client.ts#L3135
Version 20: https://github.com/matrix-org/matrix-js-sdk/blob/v20.0.0/src/client.ts#L2673

It should be configureable to switch prefixes. We should be warned when we overwrite the prefix.

**Comment by t3chguy** [comment]
@larsonnn you can't just switch prefixes without changing the handling code. So given `getKeyBackupVersion` does things with the response (namely error handling and calling `BackupManager.checkBackupVersion(res);`) it has to refer to a version it knows how to properly handle. 

> We should be warned when we overwrite the prefix.

The whole point of unstable/experimental things is rapid development without needing to warn/deprecate.

**Comment by larsonnn** [comment]
> @larsonnn you can't just switch prefixes without changing the handling code. So given getKeyBackupVersion does things with the response (namely error handling and calling BackupManager.checkBackupVersion(res);) it has to refer to a version it knows how to properly handle.

I understand.
