### ISSUE TITLE
Module-level tsdoc doesn't work

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-js-sdk#3243]
It is useful to be able to add documentation at the module level. However:

 * TSDoc does not have an `@module` tag; https://github.com/microsoft/FluidFramework/wiki/TSDoc-Guidelines#documenting-modules recommends just adding an extra regular doc-comment at the top of the file. We use `eslint-plugin-tsdoc` which complains if an `@module` tag is included.
 * However, we actually use [typedoc](https://typedoc.org) to parse our documentation, and that requires an `@module` tag in module-level documentation.

This leaves us in a pickle. I am reluctant to just disable the eslint plugin, or even just the `tsdoc-undefined-tag` error, since it is useful to know if you have written a malformed tag.

Maybe we could disable the eslint check for `@module` with `// eslint-disable-next-line` ? (does that work inside comments?) Or switch to a doc parser that actually uses TSDoc?

**Comment by heyakyra** [comment]
Upstream report: https://github.com/microsoft/tsdoc/issues/296#issuecomment-898566841

**Comment by Gerrit0** [comment]
Note: `@packageDocumentation` is a builtin TSDoc tag, and so long as you don't need the renaming behavior that TypeDoc attaches to `@module`, works just as well. You could also create a `tsdoc.json` which declares the module tag, or extends `typedoc/tsdoc.json`, which will do it for you

**Comment by richvdh** [comment]
@Gerrit0 thanks very much for the insights, and sorry for not getting round to trying it any sooner!

I tried adding both `@module` and `@packageDocumentation` to a file, and couldn't find what I wrote anywhere in the generated output. Am I missing something obvious?

**Comment by Gerrit0** [comment]
Possibly? Does the example at https://typedoc.org/tags/packageDocumentation/ help?

**Comment by richvdh** [comment]
Hrm, I thought I replied to this, but either I'm going mad, or Github ate my reply.

Anyway, in short: no, the example doesn't really help: it demonstrates adding the tag to a file, but I've done that and the relevant comment still doesn't appear in the output.

**Comment by Gerrit0** [comment]
In that case, please point me at where you tried that; not sure what's wrong otherwise.

**Comment by richvdh** [comment]
Ahhh, I think I've got it working now.

I was hoping that I would be able to usefully add documentation to arbitrary modules within the project. However, I think maybe I was mistaken about the intended usage here. It does seem to work when added to a top-level entrypoint, listed in the `entryPoints` config setting.

Thanks for the help @Gerrit0 !
