### ISSUE TITLE
Quote block not displaying in WhatsApp

### ISSUE THREAD

**Issue by imding** [matrix-org/matrix-js-sdk#3313]
Hi, I noticed something about the reply event format that is incompatible with WhatsApp.

When I send a reply message using the following code: `client.sendEvent(roomId, eventType, content)`, it is displayed correctly in my own client as well as the [Element](https://github.com/vector-im/element-web) clients, however the quote block (where I should see the message to which I'm replying) is empty on WhatsApp clients.

I think this is because the `formatted_body` is not understood by WhatsApp

The `formatted_body` I'm working with:
`<mx-reply><blockquote><a href="https://matrix.to/#/room_id/event_id">In reply to</a> <a href="https://matrix.to/#/matrix_user_id">John</a><br>Hello</blockquote></mx-reply>Hello back.`

Does anyone know the proper format I should use for WhatsApp to recognise the block content?

Thanks!

**Comment by t3chguy** [comment]
It is up to the bridge to convert between the formats, I suggest seeking help with the specific bridge you are using.
