### ISSUE TITLE
We should strip trailing slash off HS url

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-js-sdk#334]
Otherwise create paths like https://foo.com//_matrix which can break some webservers

**Comment by t3chguy** [comment]
(and IS url)

**Comment by starling-ib** [comment]
As mentioned in #4505 this is causing trouble for many users who can't connect via riot-web (includes desktop ver) simply because they put a trailing slash on the end of a home server address. The error message returned by the client gives no clue this is the issue.

**Comment by t3chguy** [comment]
@starling-ib see #526

**Comment by t3chguy** [comment]
*This can now be closed :)*

**Comment by ara4n** [comment]
thanks @t3chguy!
