### ISSUE TITLE
createClient() breaks encryption (also, memory store is faulty)

### ISSUE THREAD

**Issue by zhaytee** [matrix-org/matrix-js-sdk#337]
The recommendation is that we use createClient() instead of instantiating MatrixClient directly:
https://github.com/matrix-org/matrix-js-sdk/blob/9c6973a46a7ce4e3b4001f1ce0bd8b1b782ee7a6/src/client.js#L55

However, createClient() passes the session store object to the MatrixClient constructor with the name "store":
https://github.com/matrix-org/matrix-js-sdk/blob/9c6973a46a7ce4e3b4001f1ce0bd8b1b782ee7a6/src/matrix.js#L129

This causes problems, because MatrixClient looks for "sessionStore" and, since it will never be present in the opts object, encryption can never be enabled:
https://github.com/matrix-org/matrix-js-sdk/blob/9c6973a46a7ce4e3b4001f1ce0bd8b1b782ee7a6/src/client.js#L155

Unfortunately, even after I fixed this issue locally just to see what would happen, the SDK crashes:
`TypeError: sessionStore.getEndToEndAccount is not a function`

So perhaps the memory store doesn't implement all of the required functions that the crypto code is expecting.

**Comment by zhaytee** [comment]
Some extra info uncovered here.
I set up a `WebStorageStore` instance to use for the "sessionStore" in place of the default `MatrixInMemoryStore` to see if it would work where the memory store fails. Unfortunately, it also seems to lack the `getEndToEndAccount()` function.

Then I saw that there's a different store called `WebStorageSessionStore` which *does* implement `getEndToEndAccount`. So, I instantiated one of those and plugged it in, but apparently this store lacks some *other* method(s):
`TypeError: this.client.store.getSyncToken is not a function`

This new error is emitted from here:
https://github.com/matrix-org/matrix-js-sdk/blob/9c6973a46a7ce4e3b4001f1ce0bd8b1b782ee7a6/src/sync.js#L364

So now I'm really stuck. I may be doing something wrong in terms of getting crypto working, in which case some documentation would be handy, but it does seem like there are some issues in the codebase here.

**Comment by ara4n** [comment]
WebStorageStore was only ever experimental and has since been deleted, and never worked - sorry for not making this clearer :/ @kegsay is working on an IndexedDbStore now. However the in memory store should be fine.

**Comment by Kegsay** [comment]
@zhaytee Thanks for explaining your steps/logic.

The SDK has **two** kinds of stores: a "session" store and a normal store. Crypto uses the "session" store. This makes this statement wrong:

> However, createClient() passes the session store object to the MatrixClient constructor with the name "store":

`createClient()` merely sets default values for `opts` keys if they don't exist, it doesn't rename anything. The API shape is the same.

**Comment by zhaytee** [comment]
@ara4n @Kegsay Thanks for the clarification! My project works now. 👍
