### ISSUE TITLE
Typescript limitations with MatrixClient.on and MatrixClient.once

### ISSUE THREAD

**Issue by jgarplind** [matrix-org/matrix-js-sdk#3395]
It seems to me that the typings are incomplete when it comes to `on` and `once` (and probably more).

Using an example from the README:

```
client.on("RoomMember.typing", function (event, member) {
    if (member.typing) {
        console.log(member.name + " is typing...");
    } else {
        console.log(member.name + " stopped typing.");
    }
});
```

This TS error message is displayed:

> Argument of type '"RoomMember.typing"' is not assignable to parameter of type 'EmittedEvents | EventEmitterEvents'.

The only way I've had any luck is by importing `import { EventEmitterEvents } from "matrix-js-sdk/lib/models/typed-event-emitter";` and then using `matrixClient.once(EventEmitterEvents.NewListener, ...` but this does not cover my use case at all.

Things seem to work fine, but the typings appear to be incomplete.

I would be happy to contribute if given some pointers, as `(type parameter) T in TypedEventEmitter<Events extends string, Arguments extends ListenerMap<Events>, SuperclassArguments extends ListenerMap<any> = Arguments>.once<T extends Events | EventEmitterEvents>(event: T, listener: Listener<Events, Arguments, T>): this` is not the most inviting type signature 😉

Thanks for any pointers, clarifications or guidance.

**Comment by t3chguy** [comment]
Those are Javascript examples, In typescript we use enums which you'll need to import.

**Comment by jgarplind** [comment]
Thanks a lot. Feel free to close the issue, and do let me know if you wish for any help in making this information even easier to obtain.

**Comment by ironoa** [comment]
FYI:

I just did `import {RoomMemberEvent} from 'matrix-js-sdk/lib/models/room-member'`

and then

`this.client.on(RoomMemberEvent.Typing, function (event, member) { ... }`
