### ISSUE TITLE
What is DeviceId and why is it empty in the session list when you specify it or start Matrix.client.start?

### ISSUE THREAD

**Issue by Doumor** [matrix-org/matrix-js-sdk#3396]
I need a minimal example of a bot that can work with encrypted rooms, ideally keeping its session, but this just does not exist, and in the documentation a lot of places that are simply empty. Can you help me or give me ready-made projects, please?

**Comment by t3chguy** [comment]
the device id is assigned to you by the server when you log in or register, you have to store that and feed it back into the app for encryption APIs to function. 

https://spec.matrix.org/v1.6/client-server-api/#relationship-between-access-tokens-and-devices
https://spec.matrix.org/v1.6/client-server-api/#post_matrixclientv3login

Example: https://github.com/matrix-org/matrix-js-sdk/blob/develop/examples/crypto-browser/olm-device-export-import.js#L21

**Comment by Doumor** [comment]
> the device id is assigned to you by the server when you log in or register, you have to store that and feed it back into the app for encryption APIs to function.

How can I set it when I first log in for sdk.createClient???

**Comment by t3chguy** [comment]
> How can I set it when I first log in for sdk.createClient???

See the example I linked you to previously https://github.com/matrix-org/matrix-js-sdk/blob/develop/examples/crypto-browser/olm-device-export-import.js#L17-L24

If you want to pass it to your login request then you do so as part of the data parameter, matching the request in the spec I linked above: https://spec.matrix.org/v1.6/client-server-api/#post_matrixclientv3login

> If I use these id's from current sessions, it doesn't work. If I don't, it doesn't work. This is already on an existing account, not when I created it.

You should never re-use deviceIds between multiple clients, I suggest reading https://spec.matrix.org/v1.6/client-server-api/#relationship-between-access-tokens-and-devices
