### ISSUE TITLE
/unban and /kick don't work

### ISSUE THREAD

**Issue by Zenexer** [matrix-org/matrix-js-sdk#341]
/unban appears to be the same thing as /leave

Likely cause: https://github.com/matrix-org/matrix-js-sdk/blob/9c6973a46a7ce4e3b4001f1ce0bd8b1b782ee7a6/src/client.js#L1300

**Comment by Zenexer** [comment]
Looks like /kick has the same bug.

**Comment by Zenexer** [comment]
My understanding, after a (very) brief read, is that each user has a state relative to a room.  `"leave"` is the state that results from /unban, /kick, and /part, which I assume means there's another state akin to `"banned"`.  There's a `leave` API call to set this state on a user; if not passed a user ID, it defaults to self.  Formerly, this handled all three commands that set the `"leave"` state, but more recently, they were split into separate API calls.  The functions mapped to the slash commands were never updated accordingly.

This would also explain why https://github.com/vector-im/riot-web/issues/1961 occurred: at one point in time, /unban and /kick were essentially the same command: `leave` plus an optional user ID.  It's probably worth checking to ensure users can't call `leave` without a user ID to unban themselves.

**Comment by Zenexer** [comment]
Moved to https://github.com/matrix-org/synapse/issues/1860

**Comment by fred-wang** [comment]
@Zenexer So shouldn't we also update https://github.com/matrix-org/matrix-js-sdk/blob/9c6973a46a7ce4e3b4001f1ce0bd8b1b782ee7a6/src/client.js#L1300 to to send "unban" instead of "leave"?

**Comment by Zenexer** [comment]
@fred-wang I believe so.  Also, I think https://github.com/matrix-org/matrix-js-sdk/blob/9c6973a46a7ce4e3b4001f1ce0bd8b1b782ee7a6/src/client.js#L1314 should be `kick`.  Both changes worked when I tested them, and are correct according to the current spec.

**Comment by Zenexer** [comment]
Actually, here's the exact changes that need to be made: https://github.com/matrix-org/matrix-js-sdk/pull/342/files  You can reopen that if you want.  I forget where I was told it wouldn't be accepted; I think it was in one of the development rooms.

**Comment by fred-wang** [comment]
I don't think I have the permission to reopen this, maybe we should ask to one matrix dev.

My guess is that it breaks compatibility with server using the old API but at some point it should really be taken.
