### ISSUE TITLE
State-changing commands like /unban should use new API calls

### ISSUE THREAD

**Issue by Zenexer** [matrix-org/matrix-js-sdk#343]
State-changing commands like /unban, /ban, and /kick should use the new(*) API calls `/rooms/{roomId}/{action}` instead of the state-changing API call `/rooms/{roomId}/state/{state}`.  This is necessary to fix https://github.com/matrix-org/synapse/issues/1860 without a regression of https://github.com/vector-im/riot-web/issues/1961.

_* I'm not actually sure that they're new, but they're necessary to differentiate between /unban and /kick._

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-js-sdk/pull/364 I think
