### ISSUE TITLE
Multiple matrix-js-sdk entrypoints detected in unit test

### ISSUE THREAD

**Issue by tiennguyen1293** [matrix-org/matrix-js-sdk#3446]
i updated the `matrix-js-sdk` to the latest, i run testing and face the issue.
I'm using the CRA and importing `matrix-js-sdk` in many places to get the Event, Room type from the library.

```
Multiple matrix-js-sdk entrypoints detected
```

<img width="544" alt="image" src="https://github.com/matrix-org/matrix-js-sdk/assets/26110369/62560124-0cbf-43b1-baaf-ded10dada840">

## Version

`matrix-js-sdk:^25.1.1`

## Expection

- Please help me review and resolve the issue

**Comment by tiennguyen1293** [comment]
I can't use import { MatrixEvent } from 'matrix-js-sdk/src/matrix'. 
I solved it by deleting all the import statements for 'matrix-js-sdk' and defining constants in another place.

**Comment by dayatz** [comment]
hi @tiennguyen1293 , I'm facing the same issu, how did you solved it ?

**Comment by tiennguyen1293** [comment]
Hi @dayatz, I solved it by deleting all the import statements for `matrix-js-sdk` and defining constants in another place.

Example:
`FolderA`
```
import { MatrixClient } from 'matrix-js-sdk/lib/client' 
...
```
`FolderB`
```
import { MatrixEvent } from 'matrix-js-sdk/lib/models/event'
...
```

You should move it to only one share folder and import it again
`shared/MatrixTypes`
```
export { MatrixClient } from 'matrix-js-sdk/lib/client' 
export { MatrixEvent } from 'matrix-js-sdk/lib/models/event'
...
```

`FolderA`
```
import { MatrixClient } from 'shared/MatrixTypes' 
...
```
`FolderB`
```
import { MatrixEvent } from 'shared/MatrixTypes'
...
```

**Comment by dayatz** [comment]
thanks @tiennguyen1293 , it's working

**Comment by DenisBessa** [comment]
In my case, since I’m using Next.js, adding 'matrix-js-sdk' to the "serverExternalPackages" key in the next.config.ts file solved my problem.

```typescript
serverExternalPackages: ['matrix-js-sdk']
```
