### ISSUE TITLE
Error with encryption

### ISSUE THREAD

**Issue by ghost** [matrix-org/matrix-js-sdk#3457]
With olm 3.2.0 I'm getting this error:
```
Error uploading one-time keys
TypeError: t.unpublished_fallback_key is not a function
    at https://cdn.jsdelivr.net/npm/matrix-js-sdk@25.1.1/dist/browser-matrix.min.js:18:302473
    at https://cdn.jsdelivr.net/npm/matrix-js-sdk@25.1.1/dist/browser-matrix.min.js:18:300109
    at i.onsuccess (https://cdn.jsdelivr.net/npm/matrix-js-sdk@25.1.1/dist/browser-matrix.min.js:18:454550)
```
If I using different version olm I'm getting error `OLM.UNKNOWN_PICKLE_VERSION`
Matrix-js-sdk from CDN https://cdn.jsdelivr.net/npm/matrix-js-sdk@25.1.1/dist/browser-matrix.min.js

**Comment by t3chguy** [comment]
package.json specifies Olm 3.2.14 - you must use that one.

https://github.com/matrix-org/matrix-js-sdk/blob/develop/package.json#L84

**Comment by doesnmisclown** [comment]
I can't find 3.2.14 on https://packages.matrix.org/npm/olm/

**Comment by t3chguy** [comment]
It got moved to gitlab at some point https://gitlab.matrix.org/matrix-org/olm

**Comment by doesnmisclown** [comment]
Thx, error with one-time keys disappear
