### ISSUE TITLE
Matrix notify on reconnect

### ISSUE THREAD

**Issue by msol98** [matrix-org/matrix-js-sdk#3511]
There is a room where events are being received in. By locking the phone, the listening connection is killed after a few minutes. After unlocking and connecting back to the matrix server, we start to receive new events as well as some of the previous events - **not all of the missed events**. 
1- I don't know if and how matrix has handled this scenario?
2- One solution would be to get an event or something the time the server reconnects and keeps sending events again to get previous events.

**Comment by msol98** [comment]
> 

Thank you for your answer.
I first create client by `const client = matrix.createClient(...)` and then listen to upcoming events by `client.on("Room.timeline", ...)`.
- Is this the best practice for receiving new events?
About your solution, how am I able to listen to the syncs? Would you please indicate the API I should use?

**Comment by t3chguy** [comment]
`client.on("sync", ...);`

As I said, `#matrix-dev:matrix.org` for support.
