### ISSUE TITLE
online documentation is outdated

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-js-sdk#3512]
http://matrix-org.github.io/matrix-js-sdk/index.html has not been updated in over a month:

![image](https://github.com/matrix-org/matrix-js-sdk/assets/1389908/18b049cd-03a4-4fe9-bcff-4e3ea100fe11)

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-js-sdk/actions/workflows/pages/pages-build-deployment indeed keeps failing

**Comment by justjanne** [comment]
Resolved by https://github.com/matrix-org/matrix-js-sdk/pull/3579
