### ISSUE TITLE
How to fetch a minimum number of m.room.message events during initialSync?

### ISSUE THREAD

**Issue by haardikk21** [matrix-org/matrix-js-sdk#3529]
I have a minimal web-client built on top of Matrix using the JS SDK. Our room is quite large with over 50k+ members in a single room on our server.

During the initial sync, sometimes the SDK is only able to fetch 1-2 `m.room.message` events because the rest are room membership events.

If there a way to force the SDK to fetch a minimum number, let's say 20, of `m.room.message` events regardless of the other types of events it may be fetching?

Thanks

**Comment by t3chguy** [comment]
The initialSync is a single `/sync` call. It fetches only the number of timeline events specified in `initialSyncLimit`. That will include more than just `m.room.message`. If you want just `m.room.message` set up `initialSyncLimit: 20` and a filter including a timeline filter to `m.room.message`. I suggest #matrix-dev:matrix.org for support. This is a bug tracker
