### ISSUE TITLE
The API `MatrixClient.roomInitialSync` uses is deprecated

### ISSUE THREAD

**Issue by farooqkz** [matrix-org/matrix-js-sdk#3535]
Currently the JS SDK uses [this API](https://spec.matrix.org/v1.7/client-server-api/#get_matrixclientv3roomsroomidinitialsync) in the specified method [here](https://github.com/matrix-org/matrix-js-sdk/blob/077da23/src/client.ts#L8103). But according to the spec, the API is deprecated.

**Comment by t3chguy** [comment]
Yup, see these spec issues

https://github.com/matrix-org/matrix-spec/issues/1592
https://github.com/matrix-org/matrix-spec/issues/261
https://github.com/matrix-org/matrix-spec/issues/214
https://github.com/matrix-org/matrix-spec/issues/213

`roomInitialSync` is needed to peek into rooms.

**Comment by farooqkz** [comment]
@t3chguy So from my understanding, the spec has made it deprecated but not replacement, yet?

**Comment by t3chguy** [comment]
Correct. I suggest #matrix-dev:matrix.org for further queries
