### ISSUE TITLE
Issue related to seen massage user list

### ISSUE THREAD

**Issue by suryakantgupta321** [matrix-org/matrix-js-sdk#3545]
let's say we've room with 10 members and have 100 messages in the room. I want to get which user has seen which message in the room and show user details beside the message and to achieve this I tried these codes. i need solution for expected result is shown below.

step 1 - first of all I tried to set capabilities :
client?.sendEvent(
        id,
        "m.room.capabilities",
        {
          capabilities: {
            "m.room.read_receipts": {
              state: {
                default: true
              }
            }
          }
        },
        ""
      )
      console.log("Read receipts enabled for the room")
    } catch (error) {
      console.error("Error enabling read receipts:", error)
    }

step-2 I am listening to the Roo.timeline event

const [messages, setMessages] = useState<any>([])
const [readReceipts, setReadReceipts] = useState({})
if (event.getType() === "m.room.message") {
        const message = event.getContent().body // Get the message content
        const messageId = event.getId() // Get the ID of the message
        const receipts = readReceipts[messageId] || [] // Get the read receipts for the message

        setMessages((prevMessages) => [
          ...prevMessages,
          { id: messageId, body: message }
        ])
        setReadReceipts((prevReceipts) => ({
          ...prevReceipts,
          [messageId]: receipts
        }))
}
step-3 then listening to m.receipt

if (event.getType() === "m.receipt") {
      const receipts = event.getContent() // Get the receipt content
      const readReceiptsData = {}

      // Process read receipts for each message
      for (const messageId in receipts) {
        console.log(
          "receiptsreceiptsreceipts",
          Object.keys(receipts[messageId]["m.read"])
        )
        const readByUserIds = Object.keys(receipts[messageId]["m.read"]) // Get the list of user IDs who have read the message
        readReceiptsData[messageId] = readByUserIds
      }

      setReadReceipts((prevReceipts) => ({
        ...prevReceipts,
        ...readReceiptsData
      }))
    }
}

output: readReceipts {
    "massageId": [
        "@userid"
    ]
}
I am getting only one userid for last massage

expected result : if 3 users and 2 massages and 2 massages are read by 2 users then
 readReceipts :{
    "massageId1": [
        "@userid1",
        "@userid2"
    ],
   "massageId2": [
        "@userid1",
        "@userid2"
    ]
}

**Comment by t3chguy** [comment]
Sorry what is `m.room.capabilities`? It isn't in the spec https://spec.matrix.org/v1.7/client-server-api/

Please use code blocks, your issue is currently unreadable.

**Comment by suryakantgupta321** [comment]
ignore the first step then even it is not working.
step-2 I am listening to the Roo.timeline event
const [messages, setMessages] = useState([])
const [readReceipts, setReadReceipts] = useState({})
if (event.getType() === "m.room.message") {
const message = event.getContent().body // Get the message content
const messageId = event.getId() // Get the ID of the message
const receipts = readReceipts[messageId] || [] // Get the read receipts for the message

    setMessages((prevMessages) => [
      ...prevMessages,
      { id: messageId, body: message }
    ])
    setReadReceipts((prevReceipts) => ({
      ...prevReceipts,
      [messageId]: receipts
    }))
`}`
```
step-3 then listening to m.receipt

if (event.getType() === "m.receipt") {
const receipts = event.getContent() // Get the receipt content
const readReceiptsData = {}

  // Process read receipts for each message
  for (const messageId in receipts) {
    console.log(
      "receiptsreceiptsreceipts",
      Object.keys(receipts[messageId]["m.read"])
    )
    const readByUserIds = Object.keys(receipts[messageId]["m.read"]) // Get the list of user IDs who have read the message
    readReceiptsData[messageId] = readByUserIds
  }

  setReadReceipts((prevReceipts) => ({
    ...prevReceipts,
    ...readReceiptsData
  }))
}
}

output: readReceipts {
"massageId": [
"@userid"
]
}
I am getting only one userid for last massage

expected result : if 3 users and 2 massages and 2 massages are read by 2 users then
readReceipts :{
"massageId1": [
"@Userid1",
"@userid2"
],
"massageId2": [
"@Userid1",
"@userid2"
]
}

**Comment by t3chguy** [comment]
Your code is once again unreadable. This feels more like a support query than a bug report so I suggest seeking help in #matrix-dev:matrix.org
