### ISSUE TITLE
Invite with login doesn't set up event handling properly for the member

### ISSUE THREAD

**Issue by wlinna** [matrix-org/matrix-js-sdk#369]
When I get invite and then join the room, my member doesn't get the events. 

Here's my example code:

```
client.on("RoomMember.membership", function (event, member) {
    if (member.userId != userId) {
        return;
    }
    if (member.membership === "invite") {
        client.joinRoom(member.roomId).done(function (room) {
            var member = room.currentState.members[userId];
            console.log("Auto-joined: %s. My member in currentState is: ", room.roomId, member);
            setTimeout(function () {
                console.log("Before leaving, let's check what kind of member I am");
                var roomBeforeLeaving = client.getRoom(room.roomId);
                var memberBeforeLeave = roomBeforeLeaving.currentState.members[userId];
                console.log(memberBeforeLeave);
                client.leave(roomBeforeLeaving.roomId).done();
            }, 2000);
        });
    }
    console.info("Membership event " + member.membership + " happened");
});
```
When I invite that user to some room with another account, I get roughly the following output:
```
Membership event invite happened 
EventTimelineSet.addLiveEvent: ignoring duplicate event $148719877790mpeee:mydomain  browser-
Auto-joined: !FAUAeRaLcRZhEtXSdO:mydomain. My member in currentState is:  undefined  
Before leaving, let's check what kind of member I am  main.js:73:21
Object { roomId: "!FAUAeRaLcRZhEtXSdO:mydomain", userId: "@tester:mydomain", typing: false, name: "TesterIsTheBest", powerLevel: 0, powerLevelNorm: 0, user: null, membership: "join", events: Object, _modified: 1487198777217, 1 more… }
```
the room supplied by joinRoom's promise doesn't have the invited member in its currentState.members at all. The program never outputs "Membership event leave happened".

And when I examine the _events of memberBeforeLeave -object, it doesn't contain any event handlers.

However, when I join / create the room without invite, events work fine.

https://www.refheap.com/c7e7616a80a8e4d55975d92c3

I'm testing on Synapse v0.19.1 and matrix-js-sdk v0.7.5. I've encountered the same problem with both Firefox and Chromium. I'm not completely sure, but I think I encountered the same problem with an older version (I don't which version).

(I tried to upload a  complete example as zip file but it failed to upload)

Thanks

EDIT: Mention that events work fine when joining / creating a room without invite

**Comment by wlinna** [comment]
I decided to test this with the latest matrix-js-sdk (without updating Synapse), and it seems that upon leaving I get the leave-event.  Closing the issue.

**Comment by kishandaka** [comment]
> I decided to test this with the latest matrix-js-sdk (without updating Synapse), and it seems that upon leaving I get the leave-event. Closing the issue.

hello sir i m facing this issue last few day any solution of this bug ?
