### ISSUE TITLE
Chat received & read receipts

### ISSUE THREAD

**Issue by KolissnikBogdan** [matrix-org/matrix-js-sdk#3724]
Hi all, I'm currently having a problem with the 'Room.receipt' listener, although it's possible that I've misunderstood the flow of sending and receiving receipts.

The 'Room.receipt' listener works for the user who sends the m.read (sendReadReceipt) recipe. As far as I understand, this listener should trigger for another chat participant, so that later we can update the user interface elements that are responsible for displaying the status of the message (read or unread).

My listener currently looks like this:
```
client.on('Room.receipt', (event: MatrixEvent, room: any) => {
  const readReceipts = event.getContent();

  console.log('in Room.receip --->', readReceipts);
  ....
});
```

The function responsible for sending the receipt:
```
@action setRoomMsg = async () => {
 ...
  const lastMessage = room.timeline[room.timeline.length - 1];
  const sender = lastMessage.event.sender;
  const ev = sender !== this.matrixData.userId ? lastMessage : null;

  if (ev) {
    console.log('in if --->');
    // await this.client.sendReceipt(ev, 'm.read');
    await this.client.sendReadReceipt(ev);
  }

  if (lastMessage?.event) {
    this.client.setRoomReadMarkers(this.currRoom.roomId, lastMessage.event.event_id);
  }
};
```

Current flow:
1. User 1 sends a message
2. User 2 receives the message
3. User 2 enters the chat
4. User 2 sends a receipt (sendReadReceipt) about reading the message
5. User 2 has the 'Room.receipt' listener triggered

In step 5, this listener should trigger for user 1, not user 2.

What am I doing wrong?

**Comment by Kurioni** [comment]
Hello! Perhaps you need to send a read event in this form, it helped me:
`client.sendReadReceipt(messages[messages.length - 1].event, ReceiptType.Read)`

And then, where you accept the read status, you need to exclude your userId from the list of people who read the message:
```
const isRead = readersList.some((user) => {
    return user !== client?.credentials.userId;
  });
```

I think this should help you)

**Comment by KolissnikBogdan** [comment]
@Kurioni Can you provide a little more code? Your implementation is quite interesting
