### ISSUE TITLE
Cors policy error

### ISSUE THREAD

**Issue by Ashk3000** [matrix-org/matrix-js-sdk#3750]
How do I fix this?
```
Access to fetch at 'http://matrix.org/_matrix/client/v3/pushrules/' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
```

**Comment by t3chguy** [comment]
Use `https` - or ask matrix.org to send CORS headers on their http->https redirect. Or use a fetcher which can bypass CORS via fetchFn.

**Comment by Ashk3000** [comment]
> Use `https` - or ask matrix.org to send CORS headers on their http->https redirect. Or use a fetcher which can bypass CORS via fetchFn.

tysm, setting the baseUrl to http**s**://matrix.org/ helped
