### ISSUE TITLE
globalErrorOnUnknownDevices not accessible from CryptoApi

### ISSUE THREAD

**Issue by marekvospel** [matrix-org/matrix-js-sdk#3802]
Looking at MatrixClient.setGlobalErrorOnUnknownDevices(boolean) I've noticed it's deprecated, saying to use
```ts
client.getCrypto().globalBlacklistUnverifiedDevices = value
```
https://github.com/matrix-org/matrix-js-sdk/blob/884bd2585ab47ee3038433580eadc7600bbd6285/src/client.ts#L2684-L2690

Using the suggested line I get `UnverifiedDeviceError` when trying to send a message to a room that has unverified devices, I got an error.
I began looking into things and noticed the function was actually changing `cryptoBackend.globalErrorOnUnknownDevices`, doing something else than what the deprecation message said. Later when I tried
```ts
client.getCrypto().globalErrorOnUnknownDevices = value
```
I got a typescript error telling me that this property doesn't exist, but the error in runtime has dissapeared.

Looking at CryptoApi, it only exposes `globalBlacklistUnverifiedDevices`, not `globalErrorOnUnknownDevices`.
https://github.com/matrix-org/matrix-js-sdk/blob/4ce837b20e638a185f9002b2388fbaf48975ee6e/src/crypto-api.ts#L32-L41
`globalErrorOnUnknownDevices` does exist on CryptoBackend but when casted to CryptoApi in getCrypto(), this property is lost.

**Comment by richvdh** [comment]
The documentation on this method has been updated, sorry about that. Basically, for now you just need to continue to use `MatrixClient.setGlobalErrorOnUnknownDevices`. Once we remove the legacy crypto stack (https://github.com/element-hq/element-web/issues/26922), `setGlobalErrorOnUnknownDevices(false)` will become a no-op.
