### ISSUE TITLE
matri.js file

### ISSUE THREAD

**Issue by venkatmanojkumar** [matrix-org/matrix-js-sdk#3828]
in matrix.js file "../../../dist/browser-matrix.js" this path has been provided but in the matrix-js-sdk this file is not available i have followed this steps 
"
To provide the Olm library in a browser application:

download the transpiled libolm (from https://packages.matrix.org/npm/olm/).
load olm.js as a <script> before browser-matrix.js.
To provide the Olm library in a node.js application:

yarn add https://packages.matrix.org/npm/olm/olm-3.1.4.tgz (replace the URL with the latest version you want to use from https://packages.matrix.org/npm/olm/)
global.Olm = require('olm'); before loading matrix-js-sdk.
"

even dough  I'm facing the same issue

**Comment by t3chguy** [comment]
See https://github.com/matrix-org/matrix-js-sdk/releases/tag/v29.0.0 release notes.
