### ISSUE TITLE
"Read-only" errors

### ISSUE THREAD

**Issue by vractal** [matrix-org/matrix-js-sdk#3850]
Hi, I am experiencing an error in a react (typescript, vite) application that I had not encountered before (have been using this sdk for years):
When sending messages, I was seeing a 'TypeError: status is 'read-only' error. It was solved when I changed `pendingEventOrdering: PendingEventOrdering.Detached`. 

But now I get this when editing messages:
```
TypeError: "_replacingEvent" is read-only
    makeReplaced event.ts:1421
    addEvent relations.ts:110
    aggregateChildEvent relations-container.ts:144
    addEventToTimeline event-timeline-set.ts:726
    handleRemoteEcho event-timeline-set.ts:865
    handleRemoteEcho room.ts:2614
    addLiveEvents room.ts:2818
    injectRoomEvents sync.ts:1839
    processSyncResponse sync.ts:1452
    promiseMapSeries utils.ts:425
    processSyncResponse sync.ts:1305
    doSync sync.ts:913
    sync
    [etc]
 ```
    
  Any ideas? I can provide more info, but will wait  since this maybe something known that im just not aware of.

**Comment by t3chguy** [comment]
We don't mark it as read-only, so something is strange with your environment. 

https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/models/event.ts#L243C13-L243C28

Also your stack trace doesn't line up with latest versions of the SDK - `event.ts:1421` is not within `makeReplaced` - https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/models/event.ts#L1453-L1470

**Comment by vractal** [comment]
hey @t3chguy, thanks for the reply. I am using `"matrix-js-sdk": "^29.1.0"`, but I updated from `"matrix-js-sdk": "^25.0.0",` after I started seeing this error to see if it would fix it

Any aditional info I can give you? I honestly have no idea how my enviroment could cause something like this (but I do know I use similar code on a svelte and a vue application and they work fine, so I agree)

**Comment by t3chguy** [comment]
More details like Typescript version and a Minimum reproduction example would be a start

L1421 from your stack trace at 25.0.0 points to https://github.com/matrix-org/matrix-js-sdk/blob/v25.0.0/src/models/event.ts#L1421 which is also not in `makeReplaced` - including the exact version which corresponds to a given stack trace is necessary. `^25.0.0` is a range

**Comment by vractal** [comment]
hey, took me a little longer then I expected but here is the reproduction repo, tried to make it minimum but still trying to keep similar logic as much as I could
Just navigate to localhost:3000/chat, the default homeserver is set to matrix.org, otherwise can be changed in `matrix.utils.ts`
let me know if you have any doubts, thanks!
https://github.com/vractal/mx-bug-reproduction-repo/

**Comment by vractal** [comment]
> L1421 from your stack trace at 25.0.0 points to https://github.com/matrix-org/matrix-js-sdk/blob/v25.0.0/src/models/event.ts#L1421 which is also not in `makeReplaced` - including the exact version which corresponds to a given stack trace is necessary. `^25.0.0` is a range

btw on the version, I meant to say I was using 29.1.0 now, but still happened in 25.0.0

**Comment by vractal** [comment]
hey, were you able to see the same errors on your end?

**Comment by t3chguy** [comment]
@vractal I'm not the maintainer so not actively looking at issues this week.

**Comment by vractal** [comment]
Thanks @t3chguy , we just find out the issue.
For anyone who comes from searching:
We are using recoil, and storing MatrixEvents in an array there. Even if we were just storing them for display, since they are the same objects we got from 'timelinewindow.getevents()', they were getting marked as immutable and erroring out inside the sdk too

**Comment by t3chguy** [comment]
So yeah if you mutate objects from the SDK they will misbehave, they have their own expectations and making them immutable breaks those unfortunately. Supporting immutable objects is not something we're interested in at this time. Related https://github.com/matrix-org/matrix-js-sdk/pull/1049
