### ISSUE TITLE
How to use (CRUD) arbitrary key/value data associated with a user account profile

### ISSUE THREAD

**Issue by 4www** [matrix-org/matrix-js-sdk#3856]
On this page https://spec.matrix.org/latest/#profiles it mentions:

> Users may publish arbitrary key/value data associated with their account; such as a human-readable display name, a profile photo URL, contact information (email address, phone numbers, website URLs etc).

From the spec, it seems it should work… not sure if "just not implemented yet" or if the spec has changed not to allow this.

Here https://spec.matrix.org/v1.8/client-server-api/#profiles it mentions only GET and PUT for `profile/${user_id}/{avatar,displayname}`, and when trying for an other "profile key" (than avatar and display name), it errors.

Any idea how one does add new "arbitrary key/value" to their user profile? With the matrix-js-sdk, or the HTTP API?

**Comment by t3chguy** [comment]
This is a question for #matrix-dev:matrix.org - this isn't a support forum but a bug tracker.

**Comment by 4www** [comment]
Thought that since it is written in the spec but not part of the sdk, it might be a bug or a missing feature. Sorry then.

**Comment by 4www** [comment]
Just as side notes:
- have been asking this question in the `#matrix-dev:matrix.org` multiple times (since 1+ year).
- maybe open the `discussion` tab on the github repo, [it works having the community ask and answer questions](https://github.com/withastro/roadmap/discussions/434)
Thanks anyways and sorry again for the spam at the wrong place
