### ISSUE TITLE
sender is redacted

### ISSUE THREAD

**Issue by lukebarnard1** [matrix-org/matrix-js-sdk#387]
When an event is redacted, the `sender` of the event is stripped out when it should in-fact be kept. `sender`  should be added to `_REDACT_KEEP_KEY_MAP` in client.js.

**Comment by lampholder** [comment]
If I understand this correctly, and if redacting senders is not allowed under the Matrix spec, does this represent a bug in Synapse?

I would have thought that it shouldn't be possible for even a malfunctioning client to redact the sender.

**Comment by lukebarnard1** [comment]
The client-side redaction does strip off the sender, but this change stays on the client. The spec refers to keeping `user_id` (https://matrix.org/docs/spec/client_server/r0.2.0.html#redactions) which apparently was changed to `sender` at some point. @erikjohnston informs me that Synapse keeps `sender`, but this isn't reflected in the spec.

So the bug is with the js-sdk and the spec really.

**Comment by richvdh** [comment]
The spec is fixed in HEAD: http://matrix.org/speculator/spec/HEAD/client_server/unstable.html#redactions
