### ISSUE TITLE
local store not syncing LEAVE ?

### ISSUE THREAD

**Issue by bloor** [matrix-org/matrix-js-sdk#3895]
![image](https://github.com/matrix-org/matrix-js-sdk/assets/1420653/5dbeb8d2-4d80-4330-b0a0-5f37a1058c2c)

The rooms get synced only on refresh .. when the store is synced.
Room creation works flawlessly. The issue is just when leaving.

However I notice the room's timeline is updated:
![image](https://github.com/matrix-org/matrix-js-sdk/assets/1420653/82ab5acd-e439-424e-8afe-148fdfca1df4)

So the issue is with `getRooms()` ?

"matrix-js-sdk": "^30.0.0",

**Comment by t3chguy** [comment]
You gave almost no information. Try again with minimum reproduction steps, what you expected, what happened instead. 

> The issue is just when leaving.

What issue...?

**Comment by bloor** [comment]
Shouldn't reading the store with `client.getRooms()` return `[]` , zero rooms after I leave room ?

**Comment by t3chguy** [comment]
This isn't a support forum, its an issue tracker, if you need help using the SDK try #matrix-dev:matrix.org

**Comment by bloor** [comment]
Ok. 
**ISSUE:** the store state is not synced with server state.

**Comment by t3chguy** [comment]
> Try again with minimum reproduction steps, what you expected, what happened instead.

**Comment by t3chguy** [comment]
https://matrix-org.github.io/matrix-js-sdk/stable/classes/MatrixClient.html#getRooms doesn't say anything about only joined rooms, it says 

> Retrieve all known rooms.
