### ISSUE TITLE
How to integrate matrix-js-sdk in Cocos Creator 2.4.10?

### ISSUE THREAD

**Issue by 471625837** [matrix-org/matrix-js-sdk#3903]
I created a new project named 'testMatrix' using[ Cocos Creator 2.4.10](https://www.cocos.com/). In the project's root directory。
I used the npm command 

> 'npm install matrix-js-sdk --save' 

to add matrix-js-sdk, which is located in the project root at './node_modules/matrix-js-sdk'. 
However, when I import '

> import * as sdk from "matrix-js-sdk";

' in the project, the Cocos Creator editor shows an error：
SyntaxError: Unexpected token (281:29) while parsing F:/Users/admin/Desktop/testMatrix/node_modules/matrix-js-sdk/lib/models/room.js
SyntaxError: Unexpected token (105:8) while parsing F:/Users/admin/Desktop/testMatrix/node_modules/matrix-js-sdk/lib/crypto/backup.js
SyntaxError: Unexpected token (258:18) while parsing F:/Users/admin/Desktop/testMatrix/node_modules/oidc-client-ts/dist/umd/oidc-client-ts.js
SyntaxError: Unexpected token (7536:12) while parsing F:/Users/admin/Desktop/testMatrix/node_modules/@matrix-org/matrix-sdk-crypto-wasm/pkg/matrix_sdk_crypto_wasm.js
Error: Parsing file F:\Users\admin\Desktop\testMatrix\node_modules\matrix-js-sdk\lib\embedded.js: Unexpected token (275:10).
I don't know how to correctly import matrix-js-sdk into my Cocos Creator project. Please help me.

**Comment by t3chguy** [comment]
Cocos Creator is not a supported environment. Based on https://github.com/cocos/cocos-engine#prerequisite it looks to be based on a very outdated NodeJS version

**Comment by 471625837** [comment]
> Cocos Creator is not a supported environment. Based on https://github.com/cocos/cocos-engine#prerequisite it looks to be based on a very outdated NodeJS version

Thank you for your reply. May I achieve compatibility in Cocos Creator by downgrading the version of matrix-js-sdk?

**Comment by t3chguy** [comment]
Possibly, but that old versions are unsupported and may not be compatible with some Matrix servers.

**Comment by 471625837** [comment]
> Possibly, but that old versions are unsupported and may not be compatible with some Matrix servers.

Thank you very much! I wish you a joyful life. I'll give it a try.

**Comment by 471625837** [comment]
After trying it out, the highest supported version of matrix-js-sdk for Cocos Creator 2.4.10 is v12.0.0. Friends facing similar issues can use '`npm install matrix-js-sdk@v12.0.0`' to install.
