### ISSUE TITLE
Trying to create a client but am overwhelmed with the number of functions and classes

### ISSUE THREAD

**Issue by SNJnet** [matrix-org/matrix-js-sdk#3908]
Hi I'm relatively new to Software development and try to make a small client just to chat in one room on the web. I get the client started and can log myself in, after this I'm a bit lost and don't know how and what to do next.  Is there a good Tutorial or Example that i can use to build my own client?

Hope you can help me.

ps. I put this here because there was no Discussions Tab and I didn't know where to put it instead.

**Comment by t3chguy** [comment]
> ps. I put this here because there was no Discussions Tab and I didn't know where to put it instead.

This is just a bug & enhancement tracker, for support use #matrix-dev:matrix.org
