### ISSUE TITLE
Retrieving message count?

### ISSUE THREAD

**Issue by Timst** [matrix-org/matrix-js-sdk#3936]
Hi! I'm trying to retrieve the total count of messages in a room. I've been looking through the API docs and I can't seem to find anything that does just that. 

The search endpoint does return a result count, but you have to pass in a search term and it doesn't seem to accept wildcards or empty searches, so that doesn't work. 

If there is no better solution, I can call /rooms/id/messages and iterate until I have listed every single message, but that sounds pretty resource- and time-intensive. Is there a better way?

**Comment by t3chguy** [comment]
That isn't a thing the Matrix API supports, you would indeed need to backpaginate an entire room, also keep in mind with the eventual consistency of Matrix there may be gaps if your server wasn't in the room since its inception.
