### ISSUE TITLE
matrix_sdk_crypto_wasm_bg.wasm is part of bundle when build for browser.

### ISSUE THREAD

**Issue by fasergeyte** [matrix-org/matrix-js-sdk#3941]
We have browser app and use webpack as builder. We discovered that bundle includes huge file - matrix_sdk_crypto_wasm_bg.wasm, is it required for browser bundle? 

![image](https://github.com/matrix-org/matrix-js-sdk/assets/6638983/fd687c98-461e-4d65-978e-1ffd13820bed)

**Comment by fasergeyte** [comment]
I also created a repo with example https://github.com/fasergeyte/matrix-sdk-issue-str

**Comment by t3chguy** [comment]
This isn't the place for questions. Use #matrix-dev:matrix.org for queries next time. You can strip it in your bundler if you're not using Rust Crypto but in the future it'll be the only supported crypto.

**Comment by t3chguy** [comment]
Element Web uses it if you have that feature enabled, e.g. develop.element.io does

**Comment by richvdh** [comment]
To be clear: Element-Web puts the `matrix_sdk_crypto_wasm_bg.wasm.js` into a separate chunk which is only downloaded once Rust crypto is enabled (currently https://develop.element.io/bundles/e7951d5c676552b67da7/6984.js). As far as I know this is just default behaviour for Webpack, so I'm not really sure why it's not working for you.
