### ISSUE TITLE
get the room (hash) adress?

### ISSUE THREAD

**Issue by coderofsalvation** [matrix-org/matrix-js-sdk#3992]
My client is joining a room based on an input field (value `#my-room:myserver.org` e.g.).
However, how can I match against that adress?<br><br>
I'm using:

```
roominput = myinput.value  // '#my-room:myserver.org'

matrixClient.on(RoomEvent.Timeline, function (event, room, toStartOfTimeline) {
    if (toStartOfTimeline) {
        return; // don't print paginated results
    }
    if (event.getType() !== "m.room.message") {
        return; // only print messages
    }
    console.log(
        // the room name will update with m.room.name events automatically
        "(%s) %s :: %s",
        room.name,     // 'My room'  != roominput
        event.getSender(),
        event.getContent().body,
    );
    // roomId != roominput
});
```

How can I easily filter on roominput?

**Comment by t3chguy** [comment]
This is an issue tracker, not a support forum. Try #matrix-dev:matrix.org

**Comment by coderofsalvation** [comment]
@t3chguy nice to meet you, thank you for your warm reply.
I guess it would not hurt to re-familiarize yourself with the community guidelines of Matrix & opensource in general.

**Comment by t3chguy** [comment]
That isn't related to this project. matrix.org != matrixprofile.org

**Comment by coderofsalvation** [comment]
here you go: https://www.matrix.org/legal/code-of-conduct/
