### ISSUE TITLE
@matrix-org/olm should be a regular dependency

### ISSUE THREAD

**Issue by jolting** [matrix-org/matrix-js-sdk#4058]
I'm using matrix-js-sdk version 30.3.0
I'm getting the following error.

```
node_modules/matrix-js-sdk/lib/crypto/CrossSigning.d.ts:4:32 - error TS2307: Cannot find module '@matrix-org/olm' or its corresponding type declarations.

4 import type { PkSigning } from "@matrix-org/olm";
                                 ~~~~~~~~~~~~~~~~~


node_modules/matrix-js-sdk/lib/crypto/olmlib.d.ts:1:32 - error TS2307: Cannot find module '@matrix-org/olm' or its corresponding type declarations.

1 import type { PkSigning } from "@matrix-org/olm";
```

The root of the problem appears to be that @matrix-org/olm is incorrectly specified as a dev dependency instead of a regular dependency.

https://github.com/matrix-org/matrix-js-sdk/blob/f94dbdec0fd8fa2043f04a06bdeb9a02665841c9/package.json#L85

I can work around the issue by specifying `skipLibCheck` in my tsconfig to skip the type checking.

Is skipLibCheck required to use matrix-js-sdk?

**Comment by t3chguy** [comment]
Olm is an optional dependency but this isn't something feasible to do in typescript though it is in Javascript. Olm support is going away in favour of Rust Crypto so closing this.
