### ISSUE TITLE
Chat roles/rights can't be properly assigned and "admin" role is getting assigned back to the creator of the chat

### ISSUE THREAD

**Issue by serhii8nahornyi** [matrix-org/matrix-js-sdk#4073]
User1 is creator of the chat. Admin role initially. 
User2 is participant. Default role initially.

Description:
The participant gets moderator rights after creating and leaving the chat by the creator. 
Creator lost his rights from the chat because he left it and the participant gained the role.

The participant invites the creator of the chat, who left it. The participant automatically loses his moderator rights and the creator gets admin rights automatically, although he has left the chat and re-joined.

Incorrect behaviour with the chat rights. Why the person, who left the chat and lost his rights, gets it automatically back and can do whatever he wants with the chat? Another participant, who received the rights, loses it automatically as soon as the person-creator joins back.

Steps to reproduce:
    - 1. Create a group chat from User1 with the name “my new group chat”
    - 2. User1 invites user2
    - 3. User1 changes the chat name to “My new group chat”. The first letter is camel now. 
    - 4. User1 leaves the chat.
    - 5. User2 is getting automatically assigned as moderator
    - 6. View from User1: User1 sees that he left the chat and not a member of it anymore.
    - 7. [this is unexpected behaviour. View from User1 and User2 are not synchronized]View from User2: User2 sees the message in the chat that “User1 left the chat” but “User1” is still in the chat and has moderator rights. 
    - 8. User2 tries to invite the User1 back. It is impossible since the User1 is still displayed in the room.
    - 9. User2 does “hard refresh of the page”.
    - 10. User2 doesn’t see User1 in the chat anymore.
    - 11. User2 invites User1.
    - 12. User1 accepts the invite. 
    - 13. [this is unexpected because User2 is the new moderator] The moderator role will be automatically assigned to User1 and User2 will be assigned “default” role
    - 14. [this is unexpected. View from User1 and User2 are not synchronized] View from User1: the chat name has the first initial name. User1 is displayed as a normal user (default role)
    - 15. View from User2: the chat has the correct changed name. User1 is displayed as admin (moderator role)
    - 16. User1 does “hard refresh of the page”.
    - 17. User1 sees the same view as User2

Best regards

**Comment by richvdh** [comment]
This sounds like a client bug. Suggest reporting it against whichever client you're using.

(Alternatively, please provide a minimal test case in javascript/typescript which demonstrates how this is a bug in matrix-js-sdk, and we can reopen this)
