### ISSUE TITLE
Improve documentation of Rust crypto

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-js-sdk#4132]
* [ ] Update the [README](https://github.com/matrix-org/matrix-js-sdk/blob/develop/README.md#end-to-end-encryption-support)
* [x] Update the examples (probably blocked on https://github.com/matrix-org/matrix-js-sdk/issues/4287)

**Comment by richvdh** [comment]
We might want to make `initCrypto` an alias for `initRustCrypto` first, to save updating the docs twice

**Comment by t3chguy** [comment]
> 
We might want to make initCrypto an alias for initRustCrypto first, to save updating the docs twice


Rust Crypto hasn't reached feature parity yet, so I'm against this.

**Comment by t3chguy** [comment]
One that has massively impacted me personally due to switching HS:

+ Lack of historical key sharing on invite https://github.com/element-hq/element-web/issues/26867

**Comment by matthintosh** [comment]
Hi ! Any news about this issue. I have multiple blocking point with rust crypto like "One time key signed_curve25519:AAAAAAAAAA8 already exists" and unable to decrypt message. Maybe I'm missing something on client creation side or whatever but the documentation related to e2ee is very poor actually and the README explain that the old fashionned way for encryption is deprecated. Any help is welcome. Thank you !

**Comment by saul-jb** [comment]
> I have multiple blocking point with rust crypto like **"One time key signed_curve25519:AAAAAAAAAA8 already exists"** and unable to decrypt message.

Just been through the headache of updating matrix-js-sdk and getting e2e encryption working again with the rust crypto... I was running into that error when I had disabled indexedDB in initRustCrypto:

```js
const client = sdk.createClient({
  // ...
  cryptoStore: new LocalStorageCryptoStore(path)
})

await client.initRustCrypto({ useIndexedDB: false })
```

To fix this you need to enabled indexedDB and provide an implementation as your crypto store using: `IndexedDBCryptoStore`, i.e. :
```js
// @ts-expect-error Missing types.
import dbManager from 'node-indexeddb/dbManager'
async function loadModule (): Promise<void> {
  await dbManager.loadCache().catch(console.error)

  // @ts-expect-error Missing types.
  await import('node-indexeddb/auto')
}
await loadModule()

const idbFactory = new IDBFactory()

const client = sdk.createClient({
  // ...
  cryptoStore: new IndexedDBCryptoStore(idbFactory, path)
})

await client.initRustCrypto()
```
