### ISSUE TITLE
Disable Crypto Logger

### ISSUE THREAD

**Issue by saul-jb** [matrix-org/matrix-js-sdk#4190]
I've disabled most logging using the normal matrix-js-sdk logger:

```
import { logger } from 'matrix-js-sdk/lib/logger.js'

logger.setLevel('error')
```

However this doesn't seem to disable encryption/olm logs.

Is there a way to disable these?

**Comment by dbkr** [comment]
I'd suggest https://matrix.to/#/#element-dev:matrix.org for code level support. This is for software defects.

**Comment by ChrisKlp** [comment]
I have the same issue. I would appreciate any help.

**Comment by richvdh** [comment]
Duplicate of https://github.com/matrix-org/matrix-js-sdk/issues/4177
