### ISSUE TITLE
Are we planning to develop `RoomSummary`? 

### ISSUE THREAD

**Issue by tiennguyen1293** [matrix-org/matrix-js-sdk#4191]
https://github.com/matrix-org/matrix-js-sdk/blob/ef9490c7b14e6d3e8f3e36c7e7904ed192ab16d9/src/models/room-summary.ts#L42

Are we planning to develop `RoomSummary`?
I think it's quite useful to store summarized attributes instead of fetching each one from the database like lastEvent, member, room name, room avatar...

Thanks

**Comment by dbkr** [comment]
https://matrix.to/#/#element-dev:matrix.org is probably a better place for this. I'm entirely sure what you mean.
