### ISSUE TITLE
Fix generated documentation

### ISSUE THREAD

**Issue by DomNomNom** [matrix-org/matrix-js-sdk#421]
Public methods are not visible in the documentation. eg.
https://matrix-org.github.io/matrix-js-sdk/0.7.6/module-models_event.MatrixEvent.html
https://matrix-org.github.io/matrix-js-sdk/0.7.6/models_event.js.html#line132

The [landing page for the documentation](https://matrix-org.github.io/matrix-js-sdk/0.7.6/index.html) has a link labelled "working example" which currently points to https://matrix-org.github.io/matrix-js-sdk/0.7.6/examples/browser which is a a 404 page.

**Comment by Ryuno-Ki** [comment]
Can only partially confirm that.
The first half is fixed by now (v0.12.1).

However, I can confirm that the „working example” is a dead link.

**Comment by Johennes** [comment]
Doesn't appear to be an issue anymore: https://matrix-org.github.io/matrix-js-sdk/stable/classes/MatrixEvent.html
