### ISSUE TITLE
POST `/keys/upload` gives error 400

### ISSUE THREAD

**Issue by Gulianrdgd** [matrix-org/matrix-js-sdk#4213]
Currently I am trying to setup e2ee with the new `initRustCrypto()` everything works as far as I can see however my console is filled with POST requests to `/client/v3/keys/upload` with recieves error code 400: 

`{"errcode":"M_UNKNOWN","error":"One time key signed_curve25519:AAAAAAAAAA0 already exists ... "}`

It tries to upload the keys everytime we do a SYNC request

![Screenshot from 2024-05-22 12-26-48](https://github.com/matrix-org/matrix-js-sdk/assets/45941668/e53b3ff3-7309-4ae0-8f58-c41fec933912).

I am starting the client like this:

```ts
this.client.initRustCrypto().then( 
() => {
	this.client.startClient({
		initialSyncLimit: settings.pagination,
		includeArchivedRooms: false,
	})
```

For me it is always the same curve and the same string behind the curve, regardless of which account is logged in. In issue #4132  a user reports the same issue but with AAA...8

**Comment by richvdh** [comment]
Can you tell us more about how you are creating the `MatrixClient`? Perhaps you could share a [Short, Self Contained, Correct, Example](http://www.sscce.org/).

It looks like the rust crypto library has forgotten that it has already created a one-time-key for this device with that ID, but this information should be stored in indexeddb.

This could happen if:
 * you initialise two `MatrixClient` instances with the same access token, but your indexeddb isn't working (or you have cleared it out somehow), or:
 * you have called the `/login` REST API, passing a device ID for a device that already exists.

**Comment by Gulianrdgd** [comment]
It was indeed that I deleted my indexdb. Removing all my cookies, sessions storage etc... Did the trick.
