### ISSUE TITLE
Register via email workflow

### ISSUE THREAD

**Issue by nikiforos-dev** [matrix-org/matrix-js-sdk#4251]
What is the chain of function required to register a user via the email verification step? Do you somehow have to string together `client.requestRegisterEmailToken()`,  `client.requestEmailToken()`, and something else? There is a lack of documentation on complex workflows.

**Comment by t3chguy** [comment]
`requestRegisterEmailToken` is indeed relevant, `requestEmailToken` is not, as that's for adding an email to an existing account. During the registration UIA you do call `requestRegisterEmailToken` then after the link in the email has been clicked that phase of UIA will be completed and the API will be successful. This is not a support forum, if you need help visit `#matrix-dev:matrix.org`
