### ISSUE TITLE
How can I use it with any frontend framework that using webpack?

### ISSUE THREAD

**Issue by C0deZLee** [matrix-org/matrix-js-sdk#433]
I cannot include it in my index.html because my frontend framework does't support that, but I also cannot import the package because I'm using webpack and I'm on frontend not backend(I'm not using Node.js).

So how should I include this package to my project?

**Comment by Christilut** [comment]
Same question here.

I fixed it last time by cloning this repo and referencing the build version but that was a workaround.

**Comment by Christilut** [comment]
This actually just seems to work:

```js
import Matrix from 'matrix-js-sdk'

const matrixClient = null

const matrixLogin = async function (user, password) {
  matrixClient = await Matrix.createClient({
    baseUrl: MATRIX_HOST
  })

  const res = await matrixClient.loginWithPassword(user, password)

  const accessToken = res.access_token

  matrixClient = await Matrix.createClient({
    baseUrl: MATRIX_HOST,
    accessToken,
    userId: user
  })
}
```

And use `matrixClient.startClient()` after setting your listeners.

**Comment by Johennes** [comment]
Assuming fixed given the last message
