### ISSUE TITLE
Add joined_rooms and joined_members endpoints

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-js-sdk#440]
Currently a spec omission in https://github.com/matrix-org/matrix-doc/issues/734 because the endpoints were added in https://github.com/matrix-org/synapse/pull/1680

It would be nice if the two new endpoints from https://github.com/matrix-org/synapse/pull/1680 were supported in the js-sdk.

**Comment by t3chguy** [comment]
BUMP
no longer a spec-omission

**Comment by turt2live** [comment]
This happened: https://github.com/matrix-org/matrix-js-sdk/pull/779
