### ISSUE TITLE
Bundle size is too big because of the @matrix-org/matrix-sdk-crypto-wasm/pkg

### ISSUE THREAD

**Issue by romanicandrea** [matrix-org/matrix-js-sdk#4424]
Bundle size of matrix-js-sdk is too big because of the @matrix-org/matrix-sdk-crypto-wasm/pkg, is there any way to fix this?
Captured with matrix-js-sdk@34.5.0

<img width="1190" alt="image" src="https://github.com/user-attachments/assets/24da6fcd-49af-49f6-98d2-2d8f89a04ee5">

**Comment by richvdh** [comment]
Duplicate of https://github.com/matrix-org/matrix-js-sdk/issues/3941
