### ISSUE TITLE
error types from oidc/validate.ts when build in the local using pnpm

### ISSUE THREAD

**Issue by docd-dev** [matrix-org/matrix-js-sdk#4470]
i found a error when im build in local with pnpm, actually when first time build, its have error from tsconfig,json and already resolve, but this error, i cant resolve, help me
![image](https://github.com/user-attachments/assets/74dd5938-a49a-4ca9-9baa-70f7c5d75462)

because i need upload this to the server, and i know when build on the server its gonna error too

**Comment by t3chguy** [comment]
Seems like your build isn't including the package's own `@types` typeroot, your tsconfig likely needs amending. https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/%40types/oidc-client-ts.d.ts#L22

This is a bug tracker not a support forum, I suggest `#matrix-dev:matrix.org`

**Comment by docd-dev** [comment]
but when im install using yarn, its have same error ? im running on nextjs 14

**Comment by docd-dev** [comment]
> Seems like your build isn't including the package's own `@types` typeroot, your tsconfig likely needs amending. https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/%40types/oidc-client-ts.d.ts#L22
> 
> This is a bug tracker not a support forum, I suggest `#matrix-dev:matrix.org`

but when im install using yarn, its have same error ? im running on nextjs 14 @t3chguy

**Comment by t3chguy** [comment]
yarn vs pnpm has nothing to do with your tsconfig.
