### ISSUE TITLE
verify not verified sessions/devices

### ISSUE THREAD

**Issue by cmakasy** [matrix-org/matrix-js-sdk#4523]
Hi, after I have created a new session/device using 
```
client = sdk.createClient({
    baseUrl: homeserverUrl,
    userId: userId,
    deviceId: deviceId,
    accessToken: accessToken,
  });
```
With the command 
`const deviceList = await client.getDevices();`
I get all devices for the current user. And now I want to verify all non verified devices programmatically.

I have no idea how to do.  Does someone know how to do that ? Many thanks in advance

**Comment by richvdh** [comment]
You can try [`#matrix-dev:matrix.org`](https://matrix.to/#/#matrix-dev:matrix.org) for support in using this library.

Short answer: it sounds like you want [`CryptoApi.requestDeviceVerification`](http://matrix-org.github.io/matrix-js-sdk/interfaces/crypto_api.CryptoApi.html#requestDeviceVerification).
