### ISSUE TITLE
Trouble with imports

### ISSUE THREAD

**Issue by clickjamper** [matrix-org/matrix-js-sdk#4545]
I updated matrix-js-sdk from 33.1 to 34.12 and all of my imports was broken. I start explore problem, and it turned out it was related with https://github.com/matrix-org/matrix-js-sdk/pull/4377. After this issue in matrix.d.ts all imports with .ts. And I can't realize why they in my project looks with .ts. How can I fix it?  I just want use you library

**Comment by richvdh** [comment]
This isn't an actionable bug report. Please post some sample code demonstrating the problem.

**Comment by clickjamper** [comment]
![Снимок экрана от 2024-1](https://github.com/user-attachments/assets/351f6622-c20c-4cdb-99d0-d589778a104f)
This error in my code

![Снимок экрана от 2024-1124](https://github.com/user-attachments/assets/e5e39925-c46d-4acf-b3db-9cb8bffe8c1e)
And in lib within my node modules

If I delete .ts in lib it works

**Comment by clickjamper** [comment]
import * as sdk from "matrix-js-sdk";
const { Room } = sdk;

Doesn't works too

**Comment by clickjamper** [comment]
And I use pnpm to build the project

**Comment by clickjamper** [comment]
It was connected with ts version/ Closed.

**Comment by richvdh** [comment]
Glad you got it fixed. Could you share which version of `tsc` you were using before, and what version you found fixed it, as a helper for other people who might have the same problem? 

Also: reminder that it's helpful if you paste the error messages themselves, rather than screenshots of the error, so that anyone searching for the error message will find your issue. In this case, the useful error messages seem to be:

> TS2614: Module `"matrix-js-sdk"` has no exported member `SearchOrderBy`. Did you mean to use `import SearchOrderBy from "matrix-js-sdk"` instead?
> TS2691: An import path cannot end with a `.ts` extension.

**Comment by clickjamper** [comment]
> Glad you got it fixed. Could you share which version of `tsc` you were using before, and what version you found fixed it, as a helper for other people who might have the same problem?
> 
> Also: reminder that it's helpful if you paste the error messages themselves, rather than screenshots of the error, so that anyone searching for the error message will find your issue. In this case, the useful error messages seem to be:
> 
> > TS2614: Module `"matrix-js-sdk"` has no exported member `SearchOrderBy`. Did you mean to use `import SearchOrderBy from "matrix-js-sdk"` instead?
> > TS2691: An import path cannot end with a `.ts` extension.

4.9ю5 -> 5.7.0
