### ISSUE TITLE
room.summary has only title

### ISSUE THREAD

**Issue by t3chguy** [matrix-org/matrix-js-sdk#463]
with the docs suggesting more keys it confused someone trying to use the lib

**Comment by Johennes** [comment]
@t3chguy I'm not fully grasping the context here. Is this still an issue?

**Comment by t3chguy** [comment]
![image](https://github.com/matrix-org/matrix-js-sdk/assets/2403652/1439c137-ffe3-4905-9db9-68abd62c9dc8)

https://matrix-org.github.io/matrix-js-sdk/stable/classes/Room.html#summary

Yeah not sure what this is meant to do or what even happened to whatever title I saw in 2017 - closing for now
