### ISSUE TITLE
Get room history messages

### ISSUE THREAD

**Issue by hlogeon** [matrix-org/matrix-js-sdk#494]
Hello! We are trying to build an app using your SDK.
I didn't find any documentation about using timelines and filters. I tried to find it out in the source code of SDK but it didn't help.
What I want to do is the following:
When user scrolls chat window up, I'd like to load only message events from the timeline and paginate. I managed only getting of all the events.

**Comment by moeinrahimi** [comment]
@hlogeon 
you can use messages endpoint like this 
``` javasript 
let allMessages = baseUrl +  `/_matrix/client/r0/rooms/${roomId}/messages?limit=10&from=${nextSyncToken}&access_token=${accessToken}&dir=b`
let result = await axios.get(allMessages)
```
where nextSyncToken is 'end' key recived from calling above endpoint for the first time without `from` parameter

**Comment by hlogeon** [comment]
Thanks a lot! That really helps

**Comment by krombel** [comment]
@hlogeon Have you checked out [the examples](https://github.com/matrix-org/matrix-js-sdk/tree/master/examples/browser)?
After building it you will find in lib/matrix.js a function 
`MatrixClient.prototype.paginateEventContext = function (eventContext, opts)`
I think that would be more interesting to you

**Comment by turt2live** [comment]
I think the question has been answered here. If not, please visit [#matrix-dev:matrix.org](https://matrix.to/#/#matrix-dev:matrix.org) for assistance.

**Comment by dsrawat4u** [comment]
> Hello! We are trying to build an app using your SDK.
> I didn't find any documentation about using timelines and filters. I tried to find it out in the source code of SDK but it didn't help.
> What I want to do is the following:
> When user scrolls chat window up, I'd like to load only message events from the timeline and paginate. I managed only getting of all the events.



> @hlogeon
> you can use messages endpoint like this
> 
> ```
> let allMessages = baseUrl +  `/_matrix/client/r0/rooms/${roomId}/messages?limit=10&from=${nextSyncToken}&access_token=${accessToken}&dir=b`
> let result = await axios.get(allMessages)
> ```
> 
> where nextSyncToken is 'end' key recived from calling above endpoint for the first time without `from` parameter

Is this API working ?
Can you share a postmen request of it as its gives below error 

baseURLtypehere /_matrix/client/r0/rooms/ room_id_typehere /messages?limit=10&access_token=access_token_typehere&dir=b

 
{
    "errcode": "M_UNRECOGNIZED",
    "error": "Unrecognized request"
}

**Comment by mmeksasi** [comment]
how we can decrypt messages received or get them decrypted immediatly from chat history 
here's an example of the object
{
age: 5897752
content:
algorithm: "m.megolm.v1.aes-sha2"
ciphertext: "AwgCEoABxzKmJK/yNNub25/MmomoWlKnhjbefBrKJWALubEKHrixvxC8wA5X+LPGLuO3TCtXpkO23JgXdZc15d4zMkjBUNWR1LKhwQrLb7XgHNHrL80Pdi5Uy7pWy2IAQnF0sClssb8d+fcbUxGvae4Sk1ynnsE8idFx84sCIfSAmbimXx9p/mZ9Uje9i9ejKyawRQXc5sbkTNsQ0sAR95M+rBMn3Fh9ZKVdykyS8YtNwIYQRiQQmvk/YXeU/rDdaBa7UnpC1+0huLE+oQ8"
device_id: "ZQIPFEMWXS"
sender_key: "goS3GYQqOCZ871MML/7PESb7/HYnh7nFQqwyodgLJHI"
session_id: "O/X4bSyQ7kaodHVQXjDFuYxryOQrvofkRyHK4J3PSpg"
__proto__: Object
event_id: "$EXfrz3Sdacltj3G6aN5vz2joBKac0yusjkOet7IgTFo"
origin_server_ts: 1623234849647
room_id: "!trVoHMlckXSYXWlUjA:my.matrix.host"
sender: "@dtp3:my.matrix.host"
type: "m.room.encrypted"
unsigned: {age: 5897752}
user_id: "@dtp3:my.matrix.host"
}
