### ISSUE TITLE
How to disable console.log's is Produciton?

### ISSUE THREAD

**Issue by fletcherist** [matrix-org/matrix-js-sdk#516]
Hello! I want to turn off all Matrix console logs in my production build.
What is the most efficient way to do this?

Thanks a lot.

**Comment by danilaplee** [comment]
rewrite console.log function in the window

**Comment by fletcherist** [comment]
thanks a lot for a fast reply! 👍

**Comment by murshudov** [comment]
Try this

```js
import { logger } from 'matrix-js-sdk/lib/logger';

logger.disableAll();
```
