### ISSUE TITLE
How to create a client with matrix?

### ISSUE THREAD

**Issue by bzhfloriane** [matrix-org/matrix-js-sdk#574]
I implemented the matrix package in my IM project.
Is it possible to then create a client in my project to discuss with a registered customer on riot.com ?

I do this : 

```
var sdk = require("matrix-js-sdk");
    var matrixClient = sdk.createClient({
      baseUrl : "http://localhost:8008",
      accessToken : "example",
      userId : "@example:my.domain.name"
    });
     // affiche discussions publics
    matrixClient.publicRooms(function(err, data) {
      console.log("Public Rooms: %s", JSON.stringify(data));
    });
    
    matrixClient.startClient();
```

But I can't connect. I have this error : `GET http://localhost:8008/_matrix/client/r0/pushrules/?access_token=example 403 (Forbidden)`

Thanks for yout help :)

**Comment by jaller94** [comment]
Are you sure you are using the correct Access Token? It's a string that has approximately 270 characters (lower- & upper-letter as well as numbers).

**Comment by Ryuno-Ki** [comment]
The second code block in [the announcement](https://matrix.org/docs/guides/usage-of-the-matrix-js-sdk#login-with-an-access-token) shows some credentials object:

```js
const client = sdk.createClient("https://matrix.org");
client.login("m.login.password", {"user": "USERID", "password": "hunter2"}).then((response) => {
    console.log(response.access_token);
});
```

@bzhfloriane Does that work for you?

**Comment by turt2live** [comment]
I assume the issue has either been fixed or the person has moved on. If the issue persists, please visit us in [#matrix-dev:matrix.org](https://matrix.to/#/#matrix-dev:matrix.org) for troubleshooting.
