### ISSUE TITLE
Please include a changelog with new releases

### ISSUE THREAD

**Issue by jaller94** [matrix-org/matrix-js-sdk#640]
The "full changelog" link should be called "all changes". I wish very release would come with a bullet point list of **added**, **changed**, **deprecated** and **removed** featured.

As the library is getting more mature and increased adoption (108 repos on GitHub), documenting those changes becomes more important.

As a developer I want an indicator if it is safe to update this dependency to my project without reading all changes.

**Comment by Johennes** [comment]
Releases do have changelogs these days: https://github.com/matrix-org/matrix-js-sdk/releases
