### ISSUE TITLE
get notification when new message arrives

### ISSUE THREAD

**Issue by moeinrahimi** [matrix-org/matrix-js-sdk#701]
i know i can use unread_notification in sync request but that way it does not always return new notification .
is there a way to get notif when new unread message arrives ?

**Comment by krombel** [comment]
you could add an listener for "Room.timeline" events as mentioned in [the README](https://github.com/matrix-org/matrix-js-sdk/blob/master/README.md#print-out-messages-for-all-rooms)

**Comment by select** [comment]
here is an example
```js
import Matrix from 'matrix-js-sdk';
const client = Matrix.createClient({
  ...credentials,
  baseUrl: 'https://matrix.org',
  timelineSupport: true,
});

this.client.on('sync', (syncState, a, event) => {
 if (syncState === 'PREPARED') {
    client.on('Room.timeline', event => {
      const eventId = event.getId();
      const roomId = event.getRoomId();
      const sender = event.getSender();
      const createdAt = event.getTs();
      const type = event.getType();
      if (type === 'm.room.message') {
        const content = event.getContent();
        const { body, msgtype } = content;
        console.log(body);
      }
    });
  }
}
```

**Comment by krombel** [comment]
I don't think, that this is the right way. The point I am worrying about is the `client.on('sync',...`.
Every time you are in the `PREPARED` state a new listener is added. This can happen, when the client switched to `ERROR` and back.
So is there a specific reason to not skip `on('sync',...` and simply have `client.on('Room.timeline',...`?

**Comment by select** [comment]
@krombel good point, this is actualy what I did but I tried to squeeze as much example into the example so I went a bit wrong on the way. Good point!

This is my client https://github.com/select/audius/blob/master/src/utils/matrixClient.js
any comments are more then welcome :D
