### ISSUE TITLE
npm warns about a security vulnerability 

### ISSUE THREAD

**Issue by select** [matrix-org/matrix-js-sdk#709]
# Run  npm update sshpk --depth 5  to resolve 3 vulnerabilities
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ sshpk                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ matrix-js-sdk                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ matrix-js-sdk > request > http-signature > sshpk             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/606

**Comment by Ryuno-Ki** [comment]
Can't reproduce without either package-lock.json or npm-shrinkwrap.json.

Best practice is to commit package-lock.json into version control anyways.
