### ISSUE TITLE
How to download mxc:// files

### ISSUE THREAD

**Issue by select** [matrix-org/matrix-js-sdk#713]
I know this is not the right place to ask but I have looked though the api docs and tried it in the chat for a couple of times and don't have an answer yet on how get mxc:// files with the js sdk. Would be really nice to have an example in the documentation somewhere.

**Comment by t3chguy** [comment]
@select https://matrix.org/speculator/spec/HEAD/client_server/unstable.html#get-matrix-media-r0-download-servername-mediaid

where the `mxc://` uri is `mxc://{serverName}/{mediaId}`

**Comment by t3chguy** [comment]
or via this SDK: http://matrix-org.github.io/matrix-js-sdk/0.10.8/module-client-MatrixClient.html#mxcUrlToHttp

**Comment by select** [comment]
Ok the problem was that I did not get that you have to fill all parameters of the transformation function
```
this.client.mxcUrlToHttp(content.url, window.innerWidth);
```
The above creates and URL that returns an error 
> {"errcode":"M_UNKNOWN","error":"Internal server error"}

It works when I pass all the parameters
```
this.client.mxcUrlToHttp(content.url, window.innerWidth, window.innerHeight, 'scale');
```

**Comment by toger5** [comment]
To clarify:
Not all parameters are needed! 
`this.client.mxcUrlToHttp(content.url);` does work as well.
When adding the width, the other params are required. Adding those will result in a link similar to:
`https://matrix-client.matrix.org/_matrix/media/r0/`**thumbnail**`/…SOME_MEDIA_ID?width=2448&height=3264&method=scale`
only the thumbnail versions of the image are acessible.

**Comment by vincentthequeer06** [comment]
i just need an mxc url so I can change my picture
