### ISSUE TITLE
stop receiving events from matrixClient

### ISSUE THREAD

**Issue by joeldhenry** [matrix-org/matrix-js-sdk#741]
I am listening to a matrix client event and am unable to stop listening without deleting the object. Is there a way to stop listening to this event after i have started listening?

this.matrixClient.on('Room.timeline', (message, room) => {

});

**Comment by select** [comment]
I guess `removeAllListeners(event)` will to the trick

**Comment by joeldhenry** [comment]
Thanks @select, I've created function now `private roomTimelineEvent(message, room) {}` and used it to add a listener `this.matrixClient.addListener('Room.timeline', this.roomTimelineEvent.bind(this));` If i use  `this.matrixClient.removeListener('Room.timeline', this.roomTimelineEvent.bind(this));` i still receive events, but if i use `this.matrixClient.removeAllListeners('Room.timeline');` there looks to be a bug with Matrix SDK where removeListener(event, listener) doesn't stop

**Comment by t3chguy** [comment]
When you bind you're creating a new method, so you must store the bound method.

E.g this.roomTimelineEvent = This.roomTimelineEvent.bind(this) in the constructor and then no binds on add and remove listener

This is not a bug with the sdk it's just that you're giving it two different functions technically

**Comment by joeldhenry** [comment]
@t3chguy great pickup! https://stackoverflow.com/questions/11565471/removing-event-listener-which-was-added-with-bind helped me solve my problem.
