### ISSUE TITLE
Extend logging to whole project

### ISSUE THREAD

**Issue by Ryuno-Ki** [matrix-org/matrix-js-sdk#772]
After #763 was merged, let's extend it to the rest of the code base, so we can get rid of `console.log` statements.

**Comment by Ryuno-Ki** [comment]
Then, `.eslintrc.js` should be updated: https://github.com/matrix-org/matrix-js-sdk/blob/develop/.eslintrc.js#L47

**Comment by jkasun** [comment]
Can i fix this issue @turt2live

**Comment by Ryuno-Ki** [comment]
Fine from my site :-)
(Forgot about this issue ^^")

**Comment by jryans** [comment]
@jkasun Feel free to work on this if you'd like to!

**Comment by jkasun** [comment]
Okay im on it

**Comment by jkasun** [comment]
Some spec files also have `console.log` statements. Do we change that also?

**Comment by jryans** [comment]
Might as well include spec files as well, if possible. If it's hard to do for some reason, then you could leave them out for now.

**Comment by Ryuno-Ki** [comment]
@jkasun Do you have something for me to look at?
Hard to tell off-hand.
As rule of thumb I'd say, yes. Because console.log is always written to STDOUT (thus spamming a log file if used).

**Comment by jkasun** [comment]
@Ryuno-Ki I change all the console.log to logger method in spec file and source files. But I kept example files and debuglog as it is for now, should we change them also? Here is a file from example and sample code of debug log.

This is the files that are using `console.log`, but I guess it might be okay since those are examples,
https://github.com/matrix-org/matrix-js-sdk/blob/develop/examples/browser/browserTest.js
https://github.com/matrix-org/matrix-js-sdk/blob/develop/examples/node/app.js

Here is a sample of debug log and should we change them to logger also,

Sample 01
````
const debuglog = DEBUG ? console.log.bind(console) : function() {};
````

Sample 02
````
function debuglog(...params) {
    if (!DEBUG) {
        return;
    }
    console.log(...params);
}
````
for now I just kept them as they were is it okay to change that to the logger also?

**Comment by jkasun** [comment]
Hi @Ryuno-Ki, can you help me with this?

**Comment by jryans** [comment]
I would suggest asking in #riot-dev:matrix.org if you need help. @Ryuno-Ki does not work on Riot full time, so I think you may get a faster answer in a room where many people can see you question.

**Comment by jkasun** [comment]
@jryans I already did. No one is replying

**Comment by jryans** [comment]
Ah okay. Unfortunately, the core team is quite busy at the moment, so that could explain it.

**Comment by jryans** [comment]
I tried to scan your question above... I'd say leave the examples alone. For `debuglog`, probably it does make sense to change these ones so that everything in actual SDK code (not examples, etc.) uses the same logging paht.

**Comment by Ryuno-Ki** [comment]
https://github.com/matrix-org/matrix-js-sdk/issues/772#issuecomment-491718619

Not full-time?
Not at all...
Currently I've got other prios.
Still need to create a new password due to that security issue earlier this year + pw reset. Let me look at this PR.

**Comment by Ryuno-Ki** [comment]
https://github.com/matrix-org/matrix-js-sdk/blob/6a5f5b249e2f2e821662918f1d1d8ec0e1ec0cd8/src/store/session/webstorage.js#L26

Can we try to use an environment variable?
`process && process.env && process.env ? process.env.NODE_ENV !== "production" || false".

If it runs in the process the value (debug on/off) might be stored in `localStorage`.
This way the developer could switch it without a rebuild.

https://github.com/matrix-org/matrix-js-sdk/blob/6a5f5b249e2f2e821662918f1d1d8ec0e1ec0cd8/src/timeline-window.js#L250

Is it possible to use template strings here?

https://github.com/matrix-org/matrix-js-sdk/blob/6a5f5b249e2f2e821662918f1d1d8ec0e1ec0cd8/src/timeline-window.js#L474

You aren't adding the `TimelineWindow` prefix here. As a pattern it might be possible to read the callee from `this.name` (empty in anonymous functions) and use that in the bind of `debuglog` so to not repeat it over and over. At the very least you could insert the class name there.

https://github.com/matrix-org/matrix-js-sdk/blob/6a5f5b249e2f2e821662918f1d1d8ec0e1ec0cd8/examples/browser/browserTest.js#L10

I believe this one isn't needed to be logged by default. The other `console.log` could be helpful. No strong opinions here.

https://github.com/matrix-org/matrix-js-sdk/blob/6a5f5b249e2f2e821662918f1d1d8ec0e1ec0cd8/examples/node/app.js#L4

@Kegsay I hope you recreated a new token by now...
Can this be read with `dotenv` from a `.env` as environment variable?

https://github.com/matrix-org/matrix-js-sdk/blob/6a5f5b249e2f2e821662918f1d1d8ec0e1ec0cd8/examples/node/app.js#L396

Maybe allow a loglevel as well. Then `console[loglevel].apply` it.

**Comment by Kegsay** [comment]
@Ryuno-Ki : This was an example access token, not a real one :) thanks though.

**Comment by jkasun** [comment]
@Ryuno-Ki, @jryans Thank you. I will obviously keep the example files as it is and change the debug log as required. :smile:
