### ISSUE TITLE
any guide on building matrix-js-sdk ? 

### ISSUE THREAD

**Issue by moeinrahimi** [matrix-org/matrix-js-sdk#782]
so I forked the repo and i want to required it in my project using npm install moeinrahimi@matrix-js-sdk , but i  think i have to build the library first, am i right ? any idea how to do that ?

**Comment by jryans** [comment]
The README in this repo provide links to various ways of getting started with this library. You could also look at existing clients like Riot to see how it's used.

For more specific questions about what you are trying to build, I would suggest asking in one of the Matrix rooms, such as [Matrix Client Developers](https://matrix.to/#/!lBbDUDayNiOPvtzMev:lain.haus?via=lain.haus&via=matrix.org&via=kamax.io&via=meshspace.de).
