### ISSUE TITLE
Use the same memorySet of Rest API

### ISSUE THREAD

**Issue by mingoarte** [matrix-org/matrix-js-sdk#870]
I had created some rooms trough the Rest API and when i retrieve them trough the API everythings looks good. But, when i retrieve the rooms with the SDK, there is no rooms. 

I think that i have to configure the sdk memorySet to use the same memory that the API uses but i don't know how. Can you help me?

Thanks!!

**Comment by t3chguy** [comment]
Did you run startClient? Rooms are not fetched on demand but synced in advance

**Comment by mingoarte** [comment]
I'm running it this way: const client = sdk.createClient('http://localhost:8008');

how do i have to run it?

Thanks for your response!!

**Comment by t3chguy** [comment]
See the end of the first snippet in https://github.com/matrix-org/matrix-js-sdk#emitted-events

**Comment by mingoarte** [comment]
If i run it like this:  client.startClient();

I get the following error: **TypeError**: Cannot read property 'request' of undefined . 

How can i sync all data i had created using the API with the SDK?? Like rooms, users, etc

**Comment by t3chguy** [comment]
Github Issues are not for debugging support. They are for bugs and feature requests.

You have given 0 information about your environment, I suggest you write up as much information as you can and also everything you have tried into a message and send it in `#matrix-dev:matrix.org`
