### ISSUE TITLE
login using jwt gives access token error

### ISSUE THREAD

**Issue by poernahi** [matrix-org/matrix-js-sdk#876]
Related to #130, logging in with JWT does not automatically update the client with the returned access token and user_id. A new client has to be created instead.

This doesn't work:
```js
const matrixClient = createClient({ baseUrl: BASE_URL });
await matrixClient.login('m.login.jwt', { token: jwtToken });
await matrixClient.startClient();
```

Workaround:
```js
const tempClient = createClient({ baseUrl: BASE_URL });
const { access_token, user_id } = await tempClient.login('m.login.jwt', { token: jwtToken });
const matrixClient = createClient({
  baseUrl: BASE_URL,
  accessToken: access_token,
  userId: user_id,
});
await matrixClient.startClient();
```

Fix likely similar to PR https://github.com/matrix-org/matrix-js-sdk/pull/778

**Comment by jryans** [comment]
Thanks for the report! I agree it does sound similar to https://github.com/matrix-org/matrix-js-sdk/pull/778.

**Comment by poernahi** [comment]
I am assuming the intention of the login function is to update the internal `access_token` and `user_id`  regardless of login type. Is this correct? If so, I can write a PR.

**Comment by jryans** [comment]
Yes, I would expect the client to update its internal state, rather requiring the use of a temp client. Feel free to submit a PR! 😁

**Comment by stalniy** [comment]
@jryans created a fix, please review
