### ISSUE TITLE
Olm is missing 

### ISSUE THREAD

**Issue by frankgerhardt** [matrix-org/matrix-js-sdk#896]
Olm can not be retrieved from any URL any more. Not the released versions nor the pre-release versions, just try https://matrix.org/packages/npm/olm/olm-3.1.0-pre3.tgz 

It leads to a 404. 

Either put the olm downloads into a better place or put it back on the servers where it was before

See #301 #731

**Comment by jryans** [comment]
Thanks for the report. We're aware of the missing Olm packages. We need to review the package content after the [security incident](https://matrix.org/blog/2019/04/11/security-incident/) and will repost them once that's done.

See also https://github.com/vector-im/riot-web/issues/9441

**Comment by turt2live** [comment]
I'm actually going to close this in favour of https://github.com/vector-im/riot-web/issues/9441 to avoid forgetting about it.
