### ISSUE TITLE
Document that client.setRoomEncryption doesn't actually modify the room state

### ISSUE THREAD

**Issue by uhoreg** [matrix-org/matrix-js-sdk#905]
or maybe get rid of the function completely, as it doesn't seem useful

**Comment by cedricvanrompay** [comment]
@uhoreg not sure it's useless: it seems to start all the key synchronization routines.
Here is what is printed on the console when it's invoked:

    Enabling encryption in !sghZIehjFsiBsWAyOU:localhost; starting to track device lists for all users therein

It's just confusing that it does actually set encryption server-side

**Comment by cedricvanrompay** [comment]
I would suggest to create a “wrapper” function that calls it after having set up encryption server-side

**Comment by uhoreg** [comment]
I think it's useless because starting the device tracking happens automatically when it encounters a room encryption event, so there doesn't really seem to be any reason for anyone to be calling this function.

**Comment by cedricvanrompay** [comment]
Actually,  `await setRoomEncryption` is the only way that I found for waiting for crypto to be ready before I try to send messages (otherwise it ... sends non-encrypted messages).

See issue https://github.com/matrix-org/matrix-js-sdk/issues/906
