### ISSUE TITLE
VoIP in React Native

### ISSUE THREAD

**Issue by nikhiltechzillaindiacom** [matrix-org/matrix-js-sdk#909]
How can I use `createNewMatrixCall` to make video call or audio call with React Native?
It works with React (Web) project but not with React Native, the function call returns null which is valid as mentioned in [docs](http://matrix-org.github.io/matrix-js-sdk/0.2.0/global.html#createNewMatrixCall)

Any work around or suggestion to make it work with react native?

Related #718, but solution was not provided.

Thank You!

**Comment by nikhiltechzillaindiacom** [comment]
I was able to achieve this by adding all the code needed for **VoIP** on a **web page** and accessing that page through `web view` in `react native`.

You still need to modify web view, you can find the code [here](https://github.com/marcusbelcher/rn-getUserMedia-test)

You need to get users permission for camera and audio before they access the web view (In my case on app load)

**Comment by urbanoex** [comment]
> I was able to achieve this by adding all the code needed for **VoIP** on a **web page** and accessing that page through `web view` in `react native`.
> 
> You still need to modify web view, you can find the code [here](https://github.com/marcusbelcher/rn-getUserMedia-test)
> 
> You need to get users permission for camera and audio before they access the web view (In my case on app load)

Do you have any example of how you made it work with this code in react native? I've been trying for weeks but I can't get it to work.
