### ISSUE TITLE
File uploads are broken on latest Firefox Nightly

### ISSUE THREAD

**Issue by dnaf** [matrix-org/matrix-js-sdk#949]
Under the latest version of Firefox Nightly, upon uploading a file, the following text is always uploaded in place of the files real contents
```
function stream() {
    [native code]
}
```

This seems to be caused by [http-api.js:70](https://github.com/matrix-org/matrix-js-sdk/blob/a0456dc43041af4528e57dfd393da701a4692732/src/http-api.js#L170):
```js
const body = file.stream ? file.stream : file;
```

On other browsers, `File.stream` will be undefined; however, Firefox Nightly now adheres to the latest draft of the [File API](https://w3c.github.io/FileAPI/) which defines a [`.stream()` method](https://w3c.github.io/FileAPI/#stream-method-algo), meaning this line is swapping the content of the file for this `stream` method and later stringifying and uploading that method.

The original purpose of this line seems to be to keep compatibility with older code, which was supposedly encouraged to set `file.stream` to the stream to be uploaded. I'm not sure if this is still necessary, especially considering this is apparently undocumented behavior. Deleting this line entirely solves the issue.

If it is necessary to keep compatibility, we could just ensure the `file` isn't a `File` before checking for `file.stream`.

This may be the same issue as #908, as the description of that issue sounds similar.

**Comment by turt2live** [comment]
Highly related (by error): https://github.com/vector-im/riot-web/issues/9924

Going to raise this as a fire because it looks like we aren't handling files correctly at all.
