### ISSUE TITLE
[TypeScript] Typing Support

### ISSUE THREAD

**Issue by huan** [matrix-org/matrix-js-sdk#983]
I had spent around two full days to study the document and write the typings for `matrix-js-sdk`.

With the typing system, it helped me a lot to learn the API and prevent lots of potential bugs. I think it's worth to publish them, the best will be integrated into our npm module.

The typing definition is still working in progress and heavy developing, you can watch it at <https://github.com/huan/matrix-appservice-wechaty/blob/master/src/typings/matrix-js-sdk.d.ts>.

I'll create a pull request to add the typing to this repository after I get my project done, and any suggestion will be welcome by leaving comments under this issue.

Link to <https://github.com/huan/matrix-appservice-wechaty/issues/13>

@Half-Shot 

Thanks!

**Comment by Jack-Works** [comment]
any progress on TypeScript declaration file?

I try to use TypeScript 3.7 new feature `--declaration` with `--allowJs` to automatically generate the typings from the code base.

I failed with tons of `any`.

The reason of failure of generating the typing is the matrix code base
- is mixing the commonjs and ES Modules
- is using `prototype` to create a class instead of the `class` syntax in ES6

**Comment by huan** [comment]
This new feature from TS 3.7 is really cool.

I'd like to suggest that you try to use my declaration file which is written by me handly from scratch at here: https://github.com/huan/matrix-appservice-wechaty/tree/master/src/typings

And if you think it is useable, I'd like to publish it to the `@types/matrix-js-sdk` so that we can use it easily, and attract more TS developers to improve it for a better TS integration.

**Comment by Jack-Works** [comment]
I have tried your declaration file before, but it might be missing some functions so not working well on our project. I think it is better to generate the types from the project since the project is typed by JSDoc. It will be easier to maintain the types for this huge project.

**Comment by huan** [comment]
Yes, It would be great if we can get the declaration from the source code automatically.

I hope you can figure it out, looking forward to the better version of the declaration files! 👍

**Comment by Jack-Works** [comment]
It need do have some codemods on the current code base like transform all commonjs style import/exports to ESModule, and transform all ES5 class to ES6 class.

**Comment by Jack-Works** [comment]
And there are lots of JSDoc style type refer like `@extends {module:crypto/algorithms/base.EncryptionAlgorithm}`, it is needed to parse the JSDoc style to TS style like `typeof import("../../crypto/algorithms/base").EncryptionAlgorithm`

**Comment by turt2live** [comment]
The TypeScript update is that our tests are a disaster and don't work with typescript. We're transitioning to TypeScript proper rather than supplying declarations.

**Comment by Jack-Works** [comment]
The Babel supports typescript doesn't means it will be typed by TS. I'm going to working on the .d.ts generation from the current codebase and release it as a separate package until the official codebase can provide a high quality typescript definition

Problems when generating dts
- [x] ES5 style classes
- [ ] mixed module system 
- [ ] jsdoc style type refer
-  [ ] global type refer

**Comment by turt2live** [comment]
@Jack-Works there's a plan to rewrite/port to typescript, and a stage 1 PR is not a final representation of all the work required. I would recommend holding off until we fix our tests so we can get TypeScript properly landed, which will have a stage 2 PR for typings of the stuff we don't port (assuming it doesn't break everything).

**Comment by Jack-Works** [comment]
https://github.com/Jack-Works/matrix-js-sdk-type

**Comment by Jack-Works** [comment]
Here is my auto generated type definitions. I will improve the generated files these days.

**Comment by Jack-Works** [comment]
Ok. https://github.com/Jack-Works/matrix-js-sdk-type

![image](https://user-images.githubusercontent.com/5390719/71707439-daa26e80-2e24-11ea-8d6c-ebc11da89914.png)

Finally my work ends. But the type is very, very incomplete and I have no patience to continue working on the typescript declaration generation. Wish matrix to offer their own declaration some day!

**Comment by huan** [comment]
Just sent the PR for typing for Matrix JS SDK (matrix-js-sdk) to DefinitelyTyped.

See: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42673

**Comment by huan** [comment]
The PR is merged to the DefinitelyTyped repository.

now we can use `@types/matrix-js-sdk` by `npm install`:

```sh
npm install @types/matrix-js-sdk -D
```

There are lots of parts will need to be improved, so please not be too surprised when you ran into any type of mismatch problems with this typing.

**Comment by andrevmatos** [comment]
@huan I can't get it to work with `matrix-js-sdk@5.1.0`, because it includes a `"typings": "./lib/index.d.ts"` entry in `package.json`, but this file is a very naive stub file which just shadows the `@types` one and makes TSC throws all over the place. Any way to ignore it and use the `@types` one?

**Comment by huan** [comment]
@andrevmatos Hi, I installed it and found that it only has an `any` typing for the whole module.

So I think maybe you can send a PR to matrix-js-sdk and to see if the author will accept removing the typing from it? However, that will break some existing projects, which will require them to install the `@types/matrix-js-sdk`, and with a very high probability run into some type mismatch problems, which is a very bad situation for them.

Another way to work around this, I think if I was you, I'd like to... run a `postinstall` script with a `sed` to remove the `typings` entry from `package.json`? It's really ugly but I think it is the fastest way to ... "fix" that.

**Comment by andrevmatos** [comment]
@huan I managed to get around the issue by adding `"paths": { "matrix-js-sdk": ["node_modules/@types/matrix-js-sdk/index.d.ts"] }` to my project's (and dependant's) `tsconfig.json` `compilerOptions`, which directed tsc to use the types directly from `@types`, even if `typings` is present in `matrix-js-sdk`'s `package.json`. 
I also took the freedom to make some extension to the typings, needed by our project, at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42861
Let me know if any change is needed, please.
The correct fix would be to eventually pull in the type definitions directly into `matrix-js-sdk`'s repo and replace the currently useless types (tsc throws with them here).
Thank you.

**Comment by Jack-Works** [comment]
> Finally my work ends. But the type is very, very incomplete and I have no patience to continue working on the typescript declaration generation. Wish matrix to offer their own declaration some day! (me on Jan 3 2020)

Note: I change my idea and I'm going to continue to maintain the generated type definition

Please check out https://github.com/Jack-Works/matrix-js-sdk-type

**Comment by berniezhao11** [comment]
Since we have a @types/matrix-js-sdk, can Matrix team either remove the typing inside the SDK, OR combine the typings from @types into the SDK?

**Comment by t3chguy** [comment]
Neither will happen, the long-term goal is to move the entire SDK over to TypeScript.

Current blocker: https://github.com/matrix-org/matrix-js-sdk/pull/1229

**Comment by berniezhao11** [comment]
@t3chguy understood!  Thanks.

**Comment by berniezhao11** [comment]
@t3chguy is this completed in V8?  I checked release notes but haven't found anything related to typing.  Thanks.

**Comment by t3chguy** [comment]
No otherwise this issue would be closed + you can see most of the files are still `.js`...

It is blocked on https://github.com/matrix-org/matrix-js-sdk/pull/1229

**Comment by bergben** [comment]
> @huan I managed to get around the issue by adding `"paths": { "matrix-js-sdk": ["node_modules/@types/matrix-js-sdk/index.d.ts"] }` to my project's (and dependant's) `tsconfig.json` `compilerOptions`, which directed tsc to use the types directly from `@types`, even if `typings` is present in `matrix-js-sdk`'s `package.json`.
> I also took the freedom to make some extension to the typings, needed by our project, at [DefinitelyTyped/DefinitelyTyped#42861](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42861)
> Let me know if any change is needed, please.
> The correct fix would be to eventually pull in the type definitions directly into `matrix-js-sdk`'s repo and replace the currently useless types (tsc throws with them here).
> Thank you.

@andrevmatos is this still working for you?

I am getting the following error:
```
Error: ./node_modules/@types/matrix-js-sdk/index.d.ts
[ng] Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
[ng] Error: [..]/node_modules/@types/matrix-js-sdk/index.d.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
[ng] The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
```

Note that I am using this within Angular, although that shouldn't case the issue.

I have also tried adding `"node_modules/@types/matrix-js-sdk/index.d.ts"` to the "include" array in tsconfig, but that does not seem to have any effect.

A workaround to use the DefinitelyTyped types for now would be really helpful

**Comment by andrevmatos** [comment]
@bergben [our current workaround](https://github.com/raiden-network/light-client/blob/master/package.json#L16) is to remove this package's borked definitions at prepare time so TS will pick up DefinitelyTyped's

**Comment by Jack-Works** [comment]
in case `@types/matrix-js-sdk` doesn't work well, https://github.com/Jack-Works/matrix-js-sdk-type has updated the generated types matching f547fa732f1c8261231ce4ca929fbbb7d4030560 (v9.7.0+)

**Comment by bergben** [comment]
@andrevmatos @Jack-Works thank you both for the quick answer. 

I'll go with @andrevmatos workaround for now - I prefer using a source from DefinitelyTyped if available, but thanks anyway @Jack-Works!

**Comment by mattboardman** [comment]
Another option that worked for me with the `@types/matrix-js-sdk` package:

```
// tsconfig.json
{
  "compilerOptions": {
    "paths": {
	"matrix-js-sdk": [
	  "node_modules/@types/matrix-js-sdk/index.d.ts"
	],
    }
   "exclude": ["node_modules/matrix-js-sdk/lib/*.d.ts"]
}
```

**Comment by ShadowJonathan** [comment]
Any progress with this? https://github.com/matrix-org/matrix-js-sdk/pull/1229 has been closed for unrelated reasons.

Could anyone start Just Converting this library into typescript? https://github.com/matrix-org/matrix-js-sdk/issues/1546#issuecomment-743344312 seems to suggest this is definitely possible.

**Comment by turt2live** [comment]
We're already most of the way through a typescript conversion - if there are gaps, please open PRs.

**Comment by ShadowJonathan** [comment]
Ah apologies, i had a very old version of js-sdk cloned locally, i forgot to update my comment.

There are some issues remaining wrt TS conversion, but yes, the majority has been done.
