### ISSUE TITLE
No Notification or Listener is receiving on Delete message.

### ISSUE THREAD

**Issue by shashi-kiwi** [matrix-org/matrix-js-sdk#985]
Hi,
   I am using redactEvent for deleting event from matrix server, but not receiving any notification or trigger in event listener.Even it is working fine for new messages.
Please suggest what to do.

**Comment by t3chguy** [comment]
Can you share the code you are trying?
What event are you listening for? http://matrix-org.github.io/matrix-js-sdk/2.1.0/module-client.html#~event:MatrixClient%2522Room.redaction%2522 or something else?

**Comment by shashi-kiwi** [comment]
Hi,
  I have functionality "Delete For everyone " and Delete For me" in my iOS App.
For delete message - i am using following code.
           if let room = self.mxSession?.room(withRoomId:roomId)
            {

                    room.redactEvent(eventIds, reason: "\(eventIds)", completion: { (response) in
                          _success(eventIds)
                    })
            }
and for listening all type of message events like image ,text,llike, delete  etc this code -
            _ = room.liveTimeline { (roomLive) in
                    _ =  roomLive?.listenToEvents([MXEventType.roomMessage], { (event, direction, roomState) in {
if ((content["reason"] as? String) != nil)
                            {
                                if  let deleteMessage =  Message.getMessageFor(eventId: (content["reason"] as? String)!)
                               {
                                  self.removeEventFromDb(message: deleteMessage)
                                }
                                // delete event from database and refresh UI
                                return
                            }
}

It was working fine until some time ago. Now i am not receiving listen for delete msg event only rest all are working fine.
Thanks in advance. please suggest something.

**Comment by t3chguy** [comment]
Are you sure you're not using https://github.com/matrix-org/matrix-ios-sdk given that its an ios app and `MXEventType` is not a thing in the js-sdk

**Comment by jryans** [comment]
Fairly sure this is the wrong SDK as stated above, so I'll close for now. Please reopen if this is indeed somehow about the JS SDK.
